create_source ::=
  'CREATE SOURCE' ('IF NOT EXISTS')? src_name 'FROM' source_url
  'FORMAT' format_spec
  ('ENVELOPE' ('NONE'|'DEBEZIUM'))?
  ('WITH' '(' ( field '=' val ) ( ( ',' field '=' val ) )* ')')?
