create_source ::=
  'CREATE SOURCE' src_name 'FROM'
  (
      kafka_src 'USING SCHEMA' ( 'REGISTRY' registry_src | avro_schema ) |
      local_file 'WITH' '(' ( field '=' val ) ( ( ',' field '=' val ) )* ')'
  )
