create_view ::=
  'CREATE' 'MATERIALIZED VIEW' view_name 'AS' select_stmt |
  'CREATE' 'MATERIALIZED VIEW' 'IF NOT EXISTS' view_name 'AS' select_stmt |
  'CREATE' 'OR REPLACE' 'MATERIALIZED VIEW' view_name 'AS' select_stmt
