join_expr ::=
    select_pred 'CROSS' 'JOIN' table_ref select_post
	| select_pred join_type? 'JOIN' table_ref ( 'USING' '(' ( ( col_ref ) ( ( ',' col_ref ) )* ) ')' | 'ON' expression ) select_post
	| select_pred 'NATURAL' join_type? 'JOIN' table_ref select_post
