#!/usr/bin/env bash

# Copyright 2019-2020 Materialize Materialize, Inc. All rights reserved.
#
# This file is part of Materialize. Materialize may not be used or
# distributed without the express permission of Materialize, Inc.


set -euo pipefail

# ShellCheck cannot follow this path, as it is only valid inside the Docker
# container.
# shellcheck disable=SC1091
. /usr/local/share/shlib/shlib.bash

ci_init

while read -r binary cwd; do
    cd "$cwd"
    ci_try "/tests/$binary"
    cd "$OLDPWD"
done < /tests/manifest

ci_status_report
