#!/usr/bin/env bash

# Copyright 2019 Materialize, Inc. All rights reserved.
#
# This file is part of Materialize. Materialize may not be used or
# distributed without the express permission of Materialize, Inc.


set -euo pipefail

. /usr/local/share/shlib/shlib.bash

ci_init

while read binary cwd; do
    cd "$cwd"
    ci_try "/tests/$binary"
    cd "$OLDPWD"
done < /tests/manifest

ci_status_report
