#!/usr/bin/env bash

# Copyright Materialize, Inc. All rights reserved.
#
# Use of this software is governed by the Business Source License
# included in the LICENSE file at the root of this repository.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0.


set -euo pipefail

# ShellCheck cannot follow this path, as it is only valid inside the Docker
# container.
# shellcheck disable=SC1091
. /usr/local/share/shlib/shlib.bash

ci_init

while read -r binary cwd; do
    cd "$cwd"
    ci_try "/tests/$binary"
    cd "$OLDPWD"
done < /tests/manifest

ci_status_report
