// Copyright Materialize, Inc. and contributors. All rights reserved.
//
// Use of this software is governed by the Business Source License
// included in the LICENSE file.
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0.

//! Compiles `grammar/sql.g` into a Rust rule table (`$OUT_DIR/grammar.rs`) that
//! the `grammar` fuzz target walks. Running this at build time keeps the grammar
//! file the single source of truth. There is no checked-in generated file to
//! drift. See `grammar/sql.g` for the format.

use std::env;
use std::fs;
use std::path::Path;

#[derive(Clone)]
enum Item {
    Lit(String),
    Ref(String),
    Ident,
    Kw,
    Int,
    Str,
}

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let grammar_path = Path::new(&manifest).join("grammar/sql.g");
    println!("cargo:rerun-if-changed={}", grammar_path.display());
    let src = fs::read_to_string(&grammar_path)
        .unwrap_or_else(|e| panic!("reading {}: {e}", grammar_path.display()));

    // Drop comment lines, keep the rest as one stream.
    let mut text = String::new();
    for line in src.lines() {
        if line.trim_start().starts_with('#') {
            continue;
        }
        text.push_str(line);
        text.push('\n');
    }

    // Each rule is `name = body` terminated by an unquoted `;`.
    let mut names: Vec<String> = Vec::new();
    let mut bodies: Vec<String> = Vec::new();
    for chunk in split_unquoted(&text, ';') {
        let chunk = chunk.trim();
        if chunk.is_empty() {
            continue;
        }
        let eq = find_unquoted(chunk, '=').unwrap_or_else(|| panic!("rule has no `=`: {chunk:?}"));
        names.push(chunk[..eq].trim().to_string());
        bodies.push(chunk[eq + 1..].to_string());
    }
    if names.is_empty() {
        panic!("grammar has no rules");
    }

    let index_of = |name: &str| -> usize {
        names
            .iter()
            .position(|n| n == name)
            .unwrap_or_else(|| panic!("reference to undefined rule `{name}`"))
    };

    // Parse each body into alternatives of items.
    let rules: Vec<Vec<Vec<Item>>> = bodies
        .iter()
        .map(|body| split_unquoted(body, '|').iter().map(|a| tokenize(a)).collect())
        .collect();

    // Emit the rule table.
    let mut out = String::new();
    out.push_str("// @generated by build.rs from grammar/sql.g, do not edit.\n");
    out.push_str("#[derive(Clone, Copy)]\n");
    out.push_str("pub enum Item { Lit(&'static str), Rule(usize), Ident, Kw, Int, Str }\n");
    out.push_str("pub struct Rule { pub alts: &'static [&'static [Item]], pub leaf_alt: usize }\n");
    out.push_str("pub static RULES: &[Rule] = &[\n");
    for alts in &rules {
        // The "leaf" alternative (fewest rule references, then fewest items) is
        // used once the recursion-depth budget is spent, so generation always
        // winds down to terminals.
        let leaf_alt = alts
            .iter()
            .enumerate()
            .min_by_key(|(_, a)| {
                let refs = a.iter().filter(|i| matches!(i, Item::Ref(_))).count();
                (refs, a.len())
            })
            .map(|(i, _)| i)
            .unwrap_or(0);
        out.push_str("    Rule { alts: &[\n");
        for alt in alts {
            out.push_str("        &[");
            for item in alt {
                match item {
                    Item::Lit(s) => out.push_str(&format!("Item::Lit({s:?}), ")),
                    Item::Ref(n) => out.push_str(&format!("Item::Rule({}), ", index_of(n))),
                    Item::Ident => out.push_str("Item::Ident, "),
                    Item::Kw => out.push_str("Item::Kw, "),
                    Item::Int => out.push_str("Item::Int, "),
                    Item::Str => out.push_str("Item::Str, "),
                }
            }
            out.push_str("],\n");
        }
        out.push_str(&format!("    ], leaf_alt: {leaf_alt} }},\n"));
    }
    out.push_str("];\n");
    out.push_str(&format!("pub static START: usize = {};\n", index_of("statement")));

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    fs::write(Path::new(&out_dir).join("grammar.rs"), out).expect("write grammar.rs");
}

/// Split `s` on `sep`, ignoring `sep` inside double-quoted literals (so a `|` or
/// `;` inside a `"..."` terminal is not a separator). Honors `\`-escapes inside
/// quotes.
fn split_unquoted(s: &str, sep: char) -> Vec<String> {
    let mut parts = Vec::new();
    let mut cur = String::new();
    let mut in_quote = false;
    let mut chars = s.chars();
    while let Some(c) = chars.next() {
        if c == '"' {
            in_quote = !in_quote;
            cur.push(c);
        } else if c == '\\' && in_quote {
            cur.push(c);
            if let Some(n) = chars.next() {
                cur.push(n);
            }
        } else if c == sep && !in_quote {
            parts.push(std::mem::take(&mut cur));
        } else {
            cur.push(c);
        }
    }
    parts.push(cur);
    parts
}

/// Byte index of the first `ch` not inside a double-quoted literal.
fn find_unquoted(s: &str, ch: char) -> Option<usize> {
    let mut in_quote = false;
    let mut escaped = false;
    for (i, c) in s.char_indices() {
        if escaped {
            escaped = false;
        } else if c == '\\' && in_quote {
            escaped = true;
        } else if c == '"' {
            in_quote = !in_quote;
        } else if c == ch && !in_quote {
            return Some(i);
        }
    }
    None
}

/// Tokenize one alternative into items: `"literal"` terminals, `@builtin`s, and
/// bare rule references.
fn tokenize(alt: &str) -> Vec<Item> {
    let chars: Vec<char> = alt.chars().collect();
    let mut items = Vec::new();
    let mut i = 0;
    while i < chars.len() {
        if chars[i].is_whitespace() {
            i += 1;
            continue;
        }
        if chars[i] == '"' {
            i += 1;
            let mut lit = String::new();
            while i < chars.len() && chars[i] != '"' {
                if chars[i] == '\\' && i + 1 < chars.len() {
                    lit.push(chars[i + 1]);
                    i += 2;
                } else {
                    lit.push(chars[i]);
                    i += 1;
                }
            }
            i += 1; // consume closing quote
            items.push(Item::Lit(lit));
        } else {
            let start = i;
            while i < chars.len() && !chars[i].is_whitespace() {
                i += 1;
            }
            let word: String = chars[start..i].iter().collect();
            items.push(match word.as_str() {
                "@ident" => Item::Ident,
                "@kw" => Item::Kw,
                "@int" => Item::Int,
                "@str" => Item::Str,
                _ => Item::Ref(word),
            });
        }
    }
    items
}
