{
 "title": "Materialize Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "command",
    "query": "label_values(mz_command_durations_bucket, command)"
   },
   {
    "name": "client_query",
    "label": "Client queries",
    "query": "label_values(mz_client_peek_seconds_hist, query)"
   },
   { "name": "build_info", "label": "Build Info", "query": "--->" },
   {
    "name": "built_at",
    "label": "Built at",
    "query": "label_values(mz_server_metadata_seconds, build_time)"
   },
   {
    "name": "build_version",
    "label": "Version",
    "query": "label_values(mz_server_metadata_seconds, build_version)"
   },
   {
    "name": "build_sha",
    "label": "Git commit",
    "query": "label_values(mz_server_metadata_seconds, build_sha)"
   }
  ]
 },
 "panels": [
  { "title": "Server side latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "command=$command server latency heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(mz_command_durations_hist{command=~\"$command\",status=\"success\"}[10s])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "command=$command server latency quantiles",
   "type": "graph",
   "description": "the view of how long things took, from inside pgwire",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(mz_command_durations_bucket{command=~\"$command\",status=\"success\"}[30s])) by (le))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(mz_command_durations_bucket{command=~\"$command\",status=\"success\"}[30s])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(mz_command_durations_bucket{command=~\"$command\",status=\"success\"}[30s])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(mz_command_durations_bucket{command=~\"$command\",status=\"success\"}[30s])) by (le))",
     "legendFormat": "median"
    },
    {
     "expr": "histogram_quantile(0.001, sum(rate(mz_command_durations_bucket{command=~\"$command\",status=\"success\"}[30s])) by (le))",
     "legendFormat": "p001"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(mz_command_durations_bucket{command=~\"$command\",status=\"error\"}[30s])) by (le))",
     "legendFormat": "error p99"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(mz_command_durations_bucket{command=~\"$command\",status=\"error\"}[30s])) by (le))",
     "legendFormat": "error max"
    }
   ]
  },
  {
   "title": "dataflow internal latency heatmap",
   "type": "heatmap",
   "description": "from mz_peek_durations",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(mz_perf_peek_durations[10s])) by (duration_ns)",
     "legendFormat": "{{duration_ns}}"
    }
   ]
  },
  {
   "title": "dataflow internal latency quantiles",
   "type": "graph",
   "description": "from mz_peek_durations",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(mz_perf_peek_durations_bucket[30s])) by (le))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(mz_perf_peek_durations_bucket[30s])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(mz_perf_peek_durations_bucket[30s])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(mz_perf_peek_durations_bucket[30s])) by (le))",
     "legendFormat": "median"
    },
    {
     "expr": "histogram_quantile(0.001, sum(rate(mz_perf_peek_durations_bucket[30s])) by (le))",
     "legendFormat": "p001"
    }
   ]
  },
  {
   "title": "Frontier lags",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms", "label": "Lag (from -> to)" }
   ],
   "targets": [
    { "expr": "mz_perf_dependency_frontiers", "legendFormat": "{{source}} -> {{dataflow}}" }
   ]
  },
  {
   "title": "Worker queue sizes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mz_worker_command_queue_size",
     "legendFormat": "pending commands worker={{worker}}"
    },
    {
     "expr": "mz_worker_pending_peeks_queue_size",
     "legendFormat": "pending peeks worker={{worker}}"
    }
   ]
  },
  { "title": "Client-side latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "client side latency heatmap (client query=$client_query)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(mz_client_peek_seconds_hist{query=~\"$client_query\"}[10s])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "client side latency quantiles ($client_query)",
   "type": "graph",
   "description": "generated by the src/peeker crate",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(mz_client_peek_seconds_bucket{query=~\"$client_query\"}[30s])) by (le))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(mz_client_peek_seconds_bucket{query=~\"$client_query\"}[30s])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(mz_client_peek_seconds_bucket{query=~\"$client_query\"}[30s])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(mz_client_peek_seconds_bucket{query=~\"$client_query\"}[30s])) by (le))",
     "legendFormat": "median"
    },
    {
     "expr": "histogram_quantile(0.001, sum(rate(mz_client_peek_seconds_bucket{query=~\"$client_query\"}[30s])) by (le))",
     "legendFormat": "p001"
    }
   ]
  },
  {
   "title": "per-query responses/sec (query=$client_query)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(mz_client_peek_seconds_count{query=~\"$client_query\"}[10s])",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "per-query rows/sec (query=$client_query)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "rate(mz_client_pg_rows_total{query=~\"$client_query\"}[10s])",
     "legendFormat": "{{query}}"
    }
   ]
  },
  { "title": "Input and Output event rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "queries/second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(mz_command_durations_count[2s])",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "query rows|bytes/second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    { "expr": "rate(mz_pg_sent_rows[10s])", "legendFormat": "rows/sec" },
    { "expr": "rate(mz_pg_sent_bytes[10s])", "legendFormat": "bytes/sec" }
   ]
  },
  {
   "title": "Ingest Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "rate(mz_dataflow_events_read_total[2s])",
     "legendFormat": "{{format}} events {{status}}"
    },
    {
     "expr": "mz_dataflow_events_read_total",
     "legendFormat": "{{format}} events total {{status}}"
    }
   ]
  },
  {
   "title": "Kafka bytes read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(mz_kafka_bytes_read_total[2s])",
     "legendFormat": "rate"
    },
    { "expr": "mz_kafka_bytes_read_total", "legendFormat": "total" }
   ]
  },
  {
   "title": "Time behind external source",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "mz_kinesis_shard_millis_behind_latest",
     "legendFormat": "{{ stream_name }} {{ shard_id }}"
    }
   ]
  },
  { "title": "Resource Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "materialized: resident memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "materialized: CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"materialized\"}[2s])",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "rate(process_cpu_seconds_total{job=\"mz_client_peek\"}[30s])",
     "legendFormat": "{{job}} (doesn't show subprocesses)"
    }
   ]
  },
  {
   "title": "Arrangement Batches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mz_perf_arrangements_batches", "legendFormat": "w={{worker}} op={{operator}}" }
   ]
  },
  {
   "title": "Arrangement Records",
   "type": "graph",
   "description": "Uncompacted records in each arrangement",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mz_perf_arrangement_records",
     "legendFormat": "w={{worker}} op={{operator}} name={{name}}"
    }
   ]
  },
  {
   "title": "Shared Arrangements",
   "type": "heatmap",
   "description": "Heatmap, each value is the sum over 10 seconds, which matches the grafana update interval, so should be the actual number of shared arangements in that bucket.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "targets": [
    { "expr": "mz_perf_shared_arrangements", "legendFormat": "w={{worker}} op={{operator}}" }
   ]
  },
  {
   "title": "MySQL TPCCH Table Row Counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mysql_tpcch_table_rows", "legendFormat": "{{table_name}}" }
   ]
  },
  {
   "title": "materialized: open fds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=\"materialized\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}