# Copyright 2019 Materialize, Inc. All rights reserved.
#
# This file is part of Materialize. Materialize may not be used or
# distributed without the express permission of Materialize, Inc.

FROM rust:1.36

RUN apt-get update && apt-get -qy install wait-for-it

COPY testdrive /usr/local/bin

CMD ["testdrive"]
