# Copyright 2019 Materialize, Inc. All rights reserved.
#
# This file is part of Materialize. Materialize may not be used or
# distributed without the express permission of Materialize, Inc.

FROM rust:1.36

COPY sqllogictest /usr/local/bin

WORKDIR /workdir

CMD ["sqllogictest"]
