#!/usr/bin/env python3

# Copyright Materialize, Inc. and contributors. All rights reserved.
#
# Use of this software is governed by the Business Source License
# included in the LICENSE file at the root of this repository.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0.

import fileinput
import os
import re
import sys
from enum import Enum

import yaml


class ParserState(Enum):
    NONE = 0
    FIELDS = 1
    HEADER = 2
    SEPARATOR = 3


HEADER_SEPARATOR_RE = re.compile(r"\|?(\s*-+\s*)(\|\s*-+\s*){2}\|?")
# Field names are enclosed in backticks
FIELD_NAME_RE = re.compile(r"`(.*)`")
# Field types are enclosed in backticks and optionally in square brackets
FIELD_TYPE_RE = re.compile(r"\[?`(.*)`\]?")
# Documentation links are not preserved in the SQL comments. We capture the
# text of [..](..) and [..][..] type links and keep only the link text.
DOC_LINK_TYPE1_RE = re.compile(r"\[([^\]]+)\]\([^)]+\)")
DOC_LINK_TYPE2_RE = re.compile(r"\[([^\]]+)\]\[[^]]+\]")
RELATION_MARKER_RE = re.compile(r"RELATION_SPEC (\w+)\.(\w+)(.*)")
UNDOCUMENTED_RELATION_MARKER = re.compile(r"RELATION_SPEC_UNDOCUMENTED (\w+)\.(\w+)")

HEADER = """
# Copyright Materialize, Inc. and contributors. All rights reserved.
#
# Use of this software is governed by the Business Source License
# included in the LICENSE file at the root of this repository.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0.

# This file is auto-generated by ci/test/lint-docs-catalog.py

mode cockroach

simple conn=mz_system,user=mz_system
ALTER SYSTEM SET unsafe_enable_unstable_dependencies = true
----
COMPLETE 0

statement ok
CREATE VIEW objects AS
  SELECT
    schema.name AS schema,
    objects.name AS object,
    columns.position,
    columns.name,
    columns.type,
    comments.comment
  FROM
    mz_catalog.mz_columns AS columns
    JOIN mz_catalog.mz_objects AS objects ON columns.id = objects.id
    JOIN mz_catalog.mz_schemas AS schema ON objects.schema_id = schema.id
    LEFT JOIN mz_internal.mz_comments AS comments ON columns.id = comments.id AND columns.position = comments.object_sub_id

statement ok
CREATE INDEX objects_idx ON objects(schema, object)
"""


# Cache of loaded data files keyed by schema name.
_DATA_CACHE: dict[str, dict] = {}


def load_relation(schema: str, object_name: str) -> dict:
    """Return the data entry for `schema.object_name` from doc/user/data/<schema>.yml.

    Raises if the file or the relation is missing, so a stale FROM_YAML marker
    fails loudly rather than silently documenting nothing.
    """
    if schema not in _DATA_CACHE:
        path = os.path.join("doc", "user", "data", f"{schema}.yml")
        with open(path, encoding="utf-8") as f:
            _DATA_CACHE[schema] = yaml.safe_load(f)
    for relation in _DATA_CACHE[schema].get("relations", []):
        if relation["name"] == object_name:
            return relation
    raise ValueError(f"no data entry for {schema}.{object_name} in {schema}.yml")


def format_meaning(text: str) -> str:
    """Strip doc links to their text and escape spaces, matching the catalog
    comment form the generated sqllogictest compares against."""
    text = DOC_LINK_TYPE1_RE.sub(r"\1", text)
    text = DOC_LINK_TYPE2_RE.sub(r"\1", text)
    return text.replace(" ", "␠")


def normalize_type(type_name: str) -> str:
    """Match the inline path's type normalization for list/array types."""
    if type_name == "mz_aclitem array":
        return "mz_aclitem[]"
    if type_name == "text array":
        return "text[]"
    if "list" in type_name:
        return "list"
    if "array" in type_name:
        return "array"
    return type_name.replace(" ", "␠")


def emit_from_yaml(schema: str, object_name: str, objects: list, schemas: set) -> None:
    """Emit sqllogictest checks for a FROM_YAML relation and its variants, and
    record every emitted relation name for the completeness query."""
    relation = load_relation(schema, object_name)
    schemas.add(f"'{schema}'")

    # Base table: full check with comments, position-ordered (identical to the
    # inline-table output it replaces).
    objects.append(object_name)
    print("query TTT")
    print(
        f"SELECT name, type, comment FROM objects WHERE schema = '{schema}' AND object = '{object_name}' ORDER BY position"
    )
    print("----")
    for column in relation["columns"]:
        print(
            "  ".join(
                [
                    column["name"],
                    normalize_type(column["type"]),
                    format_meaning(column["meaning"]),
                ]
            )
        )
    print()

    for variant in relation.get("variants", []):
        objects.append(variant["name"])
        if variant.get("kind") == "raw":
            # Existence only: no column table to check, the relation is recorded
            # above so the completeness query still covers it.
            continue
        # per_worker (and any future non-raw variant): base columns plus the
        # variant's extra columns, checked columns-and-types only. Ordered by
        # name because the catalog column position of worker_id is not fixed.
        columns = list(relation["columns"]) + list(variant.get("columns", []))
        columns.sort(key=lambda c: c["name"])
        print("query TT")
        print(
            f"SELECT name, type FROM objects WHERE schema = '{schema}' AND object = '{variant['name']}' ORDER BY name"
        )
        print("----")
        for column in columns:
            print("  ".join([column["name"], normalize_type(column["type"])]))
        print()


def main() -> None:
    print(HEADER)

    state = ParserState.NONE
    position = 1
    objects = []
    schemas = set()
    for line in fileinput.input(sys.argv):
        if state == ParserState.NONE:
            undocumented = UNDOCUMENTED_RELATION_MARKER.search(line)
            if undocumented:
                schema = undocumented.group(1)
                object_name = undocumented.group(2)
                objects.append(object_name)
                schemas.add(f"'{schema}'")
                continue
            match = RELATION_MARKER_RE.search(line)
            if match:
                modifiers = match.group(3)
                schema = match.group(1)
                object_name = match.group(2)
                if "FROM_YAML" in modifiers:
                    emit_from_yaml(schema, object_name, objects, schemas)
                    continue
                include_comments = "NO_COMMENTS" not in modifiers
                if include_comments:
                    print("query TTT")
                    print(
                        f"SELECT name, type, comment FROM objects WHERE schema = '{schema}' AND object = '{object_name}' ORDER BY position"
                    )
                else:
                    print("query TT")
                    print(
                        f"SELECT name, type FROM objects WHERE schema = '{schema}' AND object = '{object_name}' ORDER BY position"
                    )
                print("----")
                state = ParserState.HEADER
                objects.append(object_name)
                schemas.add(f"'{schema}'")
        elif state == ParserState.HEADER:
            if HEADER_SEPARATOR_RE.match(line):
                state = ParserState.FIELDS
        elif state == ParserState.FIELDS:
            line = line.strip()
            if line.startswith("|"):
                line = line[1:]
            fields = [field.strip() for field in line.split("|")]
            if len(fields) >= 3:
                field_match = FIELD_NAME_RE.search(fields[0])
                type_match = FIELD_TYPE_RE.search(fields[1])
                if not field_match or not type_match:
                    raise ValueError(f"unexpected field format: {line}")
                field = field_match.group(1)
                type_name = type_match.group(1)
                # We currently cannot determine the type of lists from the catalog.
                if type_name == "mz_aclitem array":
                    type_name = "mz_aclitem[]"
                elif type_name == "text array":
                    type_name = "text[]"
                elif "list" in type_name:
                    type_name = "list"
                elif "array" in type_name:
                    type_name = "array"
                type_name = type_name.replace(" ", "␠")
                if include_comments:
                    documentation = format_meaning(fields[2])
                    print("  ".join([field, type_name, documentation]))
                else:
                    print("  ".join([field, type_name]))
                position += 1
            else:
                print()
                state = ParserState.NONE
                position = 1

    if objects:
        print("query T")
        schemas_str = ",".join(schemas)
        print(
            f"SELECT DISTINCT object FROM objects WHERE schema IN ({schemas_str}) ORDER BY object"
        )
        print("----")
        for object_name in sorted(objects):
            print(object_name)


if __name__ == "__main__":
    main()
