#!/usr/bin/env bash
#
# Copyright 2016 Confluent Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# shellcheck disable=SC1091
. /etc/confluent/docker/bash-config

if [[ -n "${SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL-}" ]]
then
    echo "===> Check if Zookeeper is healthy ..."
    cub zk-ready "$SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL" "${SCHEMA_REGISTRY_CUB_ZK_TIMEOUT:-40}"
fi

echo "===> Check if Kafka is healthy ..."

if [[ -n "${SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL-}" ]] && [[ $SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL != "PLAINTEXT" ]]
then
    cub kafka-ready \
        "${SCHEMA_REGISTRY_CUB_KAFKA_MIN_BROKERS:-1}" \
        "${SCHEMA_REGISTRY_CUB_KAFKA_TIMEOUT:-40}" \
        -b "${SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS}" \
        --config /etc/"${COMPONENT}"/admin.properties
else
    if [[ -n "${SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL-}" ]]
    then
        cub kafka-ready \
            "${SCHEMA_REGISTRY_CUB_KAFKA_MIN_BROKERS:-1}" \
            "${SCHEMA_REGISTRY_CUB_KAFKA_TIMEOUT:-40}" \
            -z "$SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL"
    elif [[ -n "${SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS-}" ]]
    then
        cub kafka-ready \
            "${SCHEMA_REGISTRY_CUB_KAFKA_MIN_BROKERS:-1}" \
            "${SCHEMA_REGISTRY_CUB_KAFKA_TIMEOUT:-40}" \
            -b "${SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS}"
    fi
fi
