#!/usr/bin/env bash

# Copyright Materialize, Inc. All rights reserved.
#
# Use of this software is governed by the Business Source License
# included in the LICENSE file at the root of this repository.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0.

# Point of this test: Assert Metabase and related containers
# can run.
#   - If we see a successful curl, Metabase is up and working!
#   - If we don't see a successful curl, Buildkite will time out
#     and fail this test.

passed=false
while ! $passed; do
    echo "Curl-ing localhost:3000"
    out=$(curl -s -o /dev/null -w "%{http_code}" host.docker.internal:3000)
    if [ "$out" == 200 ]; then
        passed=true
    else
        echo "Got status code: $out. Sleeping..."
        sleep 15
    fi
done

echo "Successfully pinged Metabase!"
