[package]
name = "mz-durable-cache"
description = "A durable cache built on top of a persist shard"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
differential-dataflow.workspace = true
mz-ore = { path = "../ore", features = ["process"] }
mz-persist-types = { path = "../persist-types" }
mz-persist-client = { path = "../persist-client" }
timely.workspace = true
tokio.workspace = true
tracing.workspace = true

[features]
default = []
