#!/usr/bin/env bash

# Copyright Materialize, Inc. All rights reserved.
#
# Use of this software is governed by the Business Source License
# included in the LICENSE file at the root of this repository.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0.

if [[ "$#" -ne 1 ]]; then
    echo "usage: $0 SQL" >&2
    exit 1
fi

while :; do
    out=$(psql -q -h materialized -p 6875 sslmode=disable -c '\timing' -c "$1")
    clear
    echo "$out"
done
