// Copyright Materialize, Inc. and contributors. All rights reserved.
//
// Use of this software is governed by the Business Source License
// included in the LICENSE file.
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0.

//! Decode helper for the Prometheus protobuf scrape format.
//!
//! We encapsulate this in its own crate since we've banned direct use of the `protobuf`
//! crate due to it being unmaintained. However, we use it out of convenience since
//! `prometheus::proto::MetricFamily` is already generated by `protobuf`.
use protobuf::{CodedInputStream, Message};

pub use prometheus::proto;

/// Decodes the wire format produced by [`prometheus::ProtobufEncoder`]
/// (and what callers receive from a Prometheus `/metrics` endpoint with
/// `Accept: application/vnd.google.protobuf`).
pub fn decode_length_delimited(bytes: &[u8]) -> Result<Vec<proto::MetricFamily>, String> {
    let mut families = Vec::new();
    let mut input = CodedInputStream::from_bytes(bytes);

    loop {
        match input.eof() {
            Ok(true) => break,
            Ok(false) => {}
            Err(e) => return Err(format!("checking eof: {e}")),
        }
        // Read the length of the next message and push it as a limit to know
        // what to read upto. Also keep track of the previous limit to restore later.
        let len = input
            .read_raw_varint32()
            .map_err(|e| format!("reading length prefix: {e}"))?;
        let previous_limit = input
            .push_limit(len.into())
            .map_err(|e| format!("pushing limit: {e}"))?;

        let mut family = proto::MetricFamily::new();
        family
            .merge_from(&mut input)
            .map_err(|e| format!("decoding MetricFamily: {e}"))?;
        families.push(family);

        // Restore the previous limit.
        input.pop_limit(previous_limit);
    }

    Ok(families)
}

#[cfg(test)]
mod tests {
    use prometheus::Encoder;

    use super::*;

    #[mz_ore::test]
    fn roundtrip_through_protobuf_encoder() {
        let registry = prometheus::Registry::new();
        let counter =
            prometheus::IntCounter::new("test_counter", "a counter").expect("create counter");
        counter.inc_by(7);
        registry
            .register(Box::new(counter))
            .expect("register counter");

        let original = registry.gather();
        let mut encoded = Vec::new();
        prometheus::ProtobufEncoder::new()
            .encode(&original, &mut encoded)
            .expect("encode");

        let decoded = decode_length_delimited(&encoded).expect("decode");

        let text = |fams: &[proto::MetricFamily]| {
            let mut buf = Vec::new();
            prometheus::TextEncoder::new()
                .encode(fams, &mut buf)
                .expect("text encode");
            String::from_utf8(buf).expect("utf-8")
        };
        assert_eq!(text(&original), text(&decoded));
    }
}
