#!/usr/bin/env bash

# Copyright Materialize, Inc. All rights reserved.
#
# Use of this software is governed by the Business Source License
# included in the LICENSE file at the root of this repository.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0.

temp_file=/tmp/auto_authorized_keys

if fetch-ssh-keys github --organization MaterializeInc > "$temp_file"
then
	echo "Installing new auto_authorized_keys"
	mv "$temp_file" ~/.ssh/auto_authorized_keys
fi
