// Copyright Materialize, Inc. and contributors. All rights reserved.
//
// Use of this software is governed by the Business Source License
// included in the LICENSE file.
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0.

use std::{collections::VecDeque, iter};

use rand::prelude::{Rng, SmallRng};
use rand::seq::SliceRandom;
use rand::SeedableRng;

use mz_expr::func::cast_timestamp_tz_to_string;
use mz_ore::now::{to_datetime, NowFn};
use mz_repr::{Datum, RelationDesc, Row, ScalarType};

use crate::types::sources::encoding::DataEncodingInner;
use crate::types::sources::Generator;

/// CREATE TABLE organizations
///   (
///      id   BIGINT PRIMARY KEY,
///      NAME VARCHAR
///   );
///
/// CREATE TABLE users
///   (
///      id      BIGINT PRIMARY KEY,
///      org_id  BIGINT,
///      name    VARCHAR,
///      FOREIGN KEY (org_id) REFERENCES organizations(id)
///   );
///
/// CREATE TABLE accounts
///   (
///      id      BIGINT PRIMARY KEY,
///      org_id  BIGINT,
///      balance BIGINT,
///      FOREIGN KEY (org_id) REFERENCES organizations(id)
///   );
///
/// CREATE TABLE auctions
///   (
///      id       BIGINT PRIMARY KEY,
///      seller   BIGINT,
///      item     VARCHAR,
///      end_time TIMESTAMP WITH time zone,
///      FOREIGN KEY (seller) REFERENCES users(id)
///   );
///
/// CREATE TABLE bids
///   (
///      id         BIGINT PRIMARY KEY,
///      buyer      BIGINT,
///      auction_id BIGINT,
///      amount     BIGINT,
///      bid_time   TIMESTAMP WITH time zone,
///      FOREIGN KEY (buyer) REFERENCES users(id),
///      FOREIGN KEY (auction_id) REFERENCES auctions(id)
///   );
pub struct Auction {}

impl Generator for Auction {
    fn data_encoding_inner(&self) -> DataEncodingInner {
        DataEncodingInner::RowCodec(
            RelationDesc::empty()
                .with_column("table", ScalarType::String.nullable(false))
                .with_column(
                    "row_data",
                    ScalarType::List {
                        element_type: Box::new(ScalarType::String),
                        custom_id: None,
                    }
                    .nullable(false),
                ),
        )
    }

    fn views(&self) -> Vec<(&str, RelationDesc)> {
        vec![
            (
                "organizations",
                RelationDesc::empty()
                    .with_column("id", ScalarType::Int64.nullable(false))
                    .with_column("name", ScalarType::String.nullable(false)),
            ),
            (
                "users",
                RelationDesc::empty()
                    .with_column("id", ScalarType::Int64.nullable(false))
                    .with_column("org_id", ScalarType::Int64.nullable(false))
                    .with_column("name", ScalarType::String.nullable(false)),
            ),
            (
                "accounts",
                RelationDesc::empty()
                    .with_column("id", ScalarType::Int64.nullable(false))
                    .with_column("org_id", ScalarType::Int64.nullable(false))
                    .with_column("balance", ScalarType::Int64.nullable(false)),
            ),
            (
                "auctions",
                RelationDesc::empty()
                    .with_column("id", ScalarType::Int64.nullable(false))
                    .with_column("seller", ScalarType::Int64.nullable(false))
                    .with_column("item", ScalarType::String.nullable(false))
                    .with_column("end_time", ScalarType::TimestampTz.nullable(false)),
            ),
            (
                "bids",
                RelationDesc::empty()
                    .with_column("id", ScalarType::Int64.nullable(false))
                    .with_column("buyer", ScalarType::Int64.nullable(false))
                    .with_column("auction_id", ScalarType::Int64.nullable(false))
                    .with_column("amount", ScalarType::Int32.nullable(false))
                    .with_column("bid_time", ScalarType::TimestampTz.nullable(false)),
            ),
        ]
    }

    fn by_seed(&self, now: NowFn, seed: Option<u64>) -> Box<dyn Iterator<Item = Vec<Row>>> {
        let mut pending = VecDeque::new();
        let mut rng = SmallRng::seed_from_u64(seed.unwrap_or_default());
        let mut counter = 0;

        let organizations = COMPANIES.iter().enumerate().map(|(offset, name)| {
            let mut company = Row::with_capacity(2);
            let mut packer = company.packer();
            packer.push(Datum::String("organizations"));
            packer.push_list(&[
                // Start ids at 1, not 0
                Datum::String(&(offset + 1).to_string()), // org id
                Datum::String(*name),
            ]);

            company
        });

        let users = CELEBRETIES.iter().enumerate().map(|(offset, name)| {
            let mut user = Row::with_capacity(2);
            let mut packer = user.packer();
            packer.push(Datum::String("users"));
            packer.push_list(&[
                // Start ids at 1, not 0.
                Datum::String(&(offset + 1).to_string()), // user id
                Datum::String(&((offset % COMPANIES.len()) + 1).to_string()), // org id
                Datum::String(*name),
            ]);

            user
        });

        let accounts = (1..=COMPANIES.len()).map(|org_id| {
            let mut org = Row::with_capacity(2);
            let mut packer = org.packer();
            packer.push(Datum::String("accounts"));
            packer.push_list(&[
                Datum::String(&(org_id + 42).to_string()), // account id
                Datum::String(&(org_id).to_string()),      // org id
                Datum::String("10000"),                    // balance
            ]);

            org
        });

        let bootstrap = organizations.chain(users).chain(accounts).collect();

        pending.push_back(bootstrap);

        Box::new(iter::from_fn(move || {
            {
                if pending.is_empty() {
                    counter += 1;
                    let now = to_datetime(now());
                    let mut auction = Row::with_capacity(2);
                    let mut packer = auction.packer();
                    packer.push(Datum::String("auctions"));
                    packer.push_list(&[
                        Datum::String(&counter.to_string()), // auction id
                        Datum::String(&rng.gen_range(1..=CELEBRETIES.len()).to_string()), // seller
                        Datum::String(AUCTIONS.choose(&mut rng).unwrap()), // item
                        Datum::String(&cast_timestamp_tz_to_string(
                            now + chrono::Duration::seconds(10),
                        )), // end time
                    ]);
                    pending.push_back(vec![auction]);
                    const MAX_BIDS: i64 = 10;
                    for i in 0..rng.gen_range(2..MAX_BIDS) {
                        let bid_id = (counter * MAX_BIDS + i).to_string();
                        let bid_id = Datum::String(&bid_id);
                        let bid = {
                            let mut bid = Row::with_capacity(2);
                            let mut packer = bid.packer();
                            packer.push(Datum::String("bids"));
                            packer.push_list(&[
                                bid_id,
                                Datum::String(&rng.gen_range(1..=CELEBRETIES.len()).to_string()), // buyer
                                Datum::String(&counter.to_string()), // auction id
                                Datum::String(&rng.gen_range(1..100).to_string()), // amount
                                Datum::String(&cast_timestamp_tz_to_string(
                                    now + chrono::Duration::seconds(i),
                                )), // bid time
                            ]);
                            bid
                        };
                        pending.push_back(vec![bid]);
                    }
                }
                pending.pop_front()
            }
        }))
    }
}

const AUCTIONS: &[&str] = &[
    "Signed Memorabilia",
    "City Bar Crawl",
    "Best Pizza in Town",
    "Gift Basket",
    "Custom Art",
];

const CELEBRETIES: &[&str] = &[
    "Adele",
    "Alf",
    "Aristotle",
    "Attenborough",
    "Abigail Adams",
    "Adam Arkin",
    "Alan Alda",
    "Alan Arkin",
    "Alan Autry",
    "Alvin Ailey",
    "Amedeo Avogadro",
    "Amy Adams",
    "Andre Agasi",
    "Andre Agassi",
    "Ansel Adams",
    "Army Archerd",
    "Art Alexakis",
    "Arthur Ashe",
    "Ashley Angel",
    "Aaron Burr",
    "Abigail Breslin",
    "Abigail Van Buren",
    "Adam Brody",
    "Adrien Brody",
    "Adrienne Barbeau",
    "Alan Bates",
    "Alan Beckwith",
    "Albert Brooks",
    "Alec Baldwin",
    "Alex Baldwin",
    "Alexander Graham Bell",
    "Alexis Bledel",
    "Amanda Bynes",
    "Ambrose Bierce",
    "Amy Brenneman",
    "Andrea Bocelli",
    "Angela Bassett",
    "Anita Bryant",
    "Ann Blyth",
    "Anne Bancroft",
    "Anne Bronte",
    "Annette Bening",
    "Anthony Burgess",
    "Antonio Banderas",
    "Art Bell",
    "Art Blakey",
    "Art Buchwald",
    "Aubrey Beardsley",
    "August Anheuser Busch",
    "Aaron Copland",
    "Adam Carolla",
    "Agatha Christie",
    "Al Capone",
    "Al Capp",
    "Alexander Calder",
    "Alice Cooper",
    "Alistair Cooke",
    "Angela Cartwright",
    "Anton Chekhov",
    "Art Carney",
    "Arthur C. Clarke",
    "Augustus Caesar",
    "Abner Doubleday",
    "Adam Duritz",
    "Adelle Davis",
    "Alberto Santos Dumont",
    "Alexandre Dumas",
    "Andrea Dromm",
    "Andy Devine",
    "Angela Davis",
    "Angie Dickinson",
    "Ann B. Davis",
    "Annie Duke",
    "Arlene Dahl",
    "Abby Elliott",
    "Albert Einstein",
    "Amelia Earhart",
    "Anita Ekberg",
    "A.J. Foyt",
    "Ace Frehley",
    "Agnetha F�ltskog",
    "Albert Finney",
    "Alice Faye",
    "Allen Funt",
    "America Ferrera",
    "Anne Frank",
    "Annette Funicello",
    "Anthony Franciosa",
    "Aretha Franklin",
    "Arthur Fiedler",
    "Al Gore",
    "Al Green",
    "Alan Greenspan",
    "Alec Guinness",
    "Alexander Godunov",
    "Alexander the Great",
    "Allen Ginsberg",
    "Allen Greenspan",
    "Amy Grant",
    "Andre the Giant",
    "Andrew Greeley",
    "Andy Garcia",
    "Andy Gibb",
    "Andy Griffith",
    "Anthony Geary",
    "Anthony Glise",
    "Art Garfunkel",
    "Arthur Godfrey",
    "Arye Gross",
    "Astrud Gilberto",
    "Ava Gardner",
    "Abbie Hoffman",
    "Adolf Hitler",
    "Al Hirschfeld",
    "Al Hirt",
    "Aldous Huxley",
    "Alex Haley",
    "Alex Harvey",
    "Alexander Hamilton",
    "Alfred Hitchcock",
    "Alger Hiss",
    "Anjelica Huston",
    "Anthony Hopkins",
    "Arsenio Hall",
    "Audrey Hepburn",
    "Aga Khan IV",
    "Allen Iverson",
    "Amy Irving",
    "Agnelina Jolie",
    "Al Jarreau",
    "Al Jolson",
    "Alan Jackson",
    "Amy Jo Johnson",
    "Andrew Jackson",
    "Andrew Johnson",
    "Ann Jillian",
    "Anne Jeffreys",
    "Arte Johnson",
    "Ashley Judd",
    "Akira Kurosawa",
    "Al Kaline",
    "Alan King",
    "Albert King",
    "Alex Karras",
    "Alfred Kinsey",
    "Alicia Keys",
    "Andy Kaufman",
    "Arthur Kennedy",
    "Ashton Kutcher",
    "Abraham Lincoln",
    "Alan Jay Lerner",
    "Alan Ladd",
    "Alex Lifeson",
    "Allen Ludden",
    "Alvin Lee",
    "Amy Locane",
    "Amy Lowell",
    "Angela Lansbury",
    "Ann Landers",
    "Annie Leibovitz",
    "Annie Lennox",
    "Art Linkletter",
    "Avril Lavigne",
    "A.A. Milne",
    "Abraham Maslow",
    "Agnes Moorehead",
    "Al Michaels",
    "Ali MacGraw",
    "Amadeus Mozart",
    "Andie Macdowell",
    "Andre Michelin",
    "Ann Margret",
    "Ann Miller",
    "Anne McCaffrey",
    "Anne Meara",
    "Anne Murray",
    "Archie Moore",
    "Ari Meyers",
    "Arthur Miller",
    "Arthur Murray",
    "Audie Murphy",
    "Audrey Meadows",
    "Aaron Neville",
    "Alfred Nobel",
    "Anthony Newley",
    "Anita ODay",
    "Annie Oakley",
    "Aristotle Onassis",
    "Ashley Olsen",
    "Adrian Paul",
    "Al Pacino",
    "Alain Prost",
    "Albert Pujols",
    "Alex Pettyfer",
    "Amy Poehler",
    "Andre Previn",
    "Anthony Perkins",
    "Arnold Palmer",
    "Arthur Penn",
    "Audrina Patridge",
    "Austin Peck",
    "Aidan Quinn",
    "Anthony Quinn",
    "Al Roker",
    "Alan Rickman",
    "Alan Ruck",
    "Alex Rodriguez",
    "Alfonso Ribeiro",
    "Am�lia Rodrigues",
    "Andy Roddick",
    "Andy Rooney",
    "Anika Noni Rose",
    "Anne Rice",
    "Anne Robinson",
    "Arthur Rimbaud",
    "Arthur Rubenstein",
    "Auguste Rodin",
    "Axl Rose",
    "Ayn Rand",
    "Aaron Spelling",
    "Adam Sandler",
    "Alan Shepard",
    "Albert Schweitzer",
    "Alberto Santos-Dumont",
    "Aleksandr Solzhenitsyn",
    "Alicia Silverstone",
    "Ally Sheedy",
    "Alyson Stoner",
    "Amy Smart",
    "Andres Segovia",
    "Andrew Shue",
    "Andy Summers",
    "Ann Sothern",
    "Anna Nicole Smith",
    "Anwar Sadat",
    "Ariel Sharon",
    "Arion Salazar",
    "Arnold Schwartineger",
    "Arnold Stang",
    "Arthur Sullivan",
    "Artie Shaw",
    "Ashley Simpson",
    "Avery Schreiber",
    "Ayrton Senna da Silva",
    "Aida Turturro",
    "Aisha Tyler",
    "Alan Thicke",
    "Alan Trammell",
    "Alan Turing",
    "Alex Trebek",
    "Alexandre Tansman",
    "Alvin Toffler",
    "Amanda Tapping",
    "Anthony Trollope",
    "Arthur Treacher",
    "Arturo Toscanini",
    "Ashley Tisdale",
    "Al Unser",
    "Abe Vigoda",
    "Alessandro Volta",
    "Alexa Vega",
    "Amerigo Vespucci",
    "Antonio Villaraigosa",
    "Antonio Vivaldi",
    "Adam West",
    "Alice Walker",
    "Amy Winehouse",
    "Andrew Lloyd Webber",
    "Andrew Wyeth",
    "Andy Warhol",
    "Andy Williams",
    "Adam Yauch",
    "Al Yankovic",
    "Al Yankovick",
    "Andrew Young",
    "Anthony Zerbe",
    "Bach",
    "Batman",
    "Beck",
    "Beethoven",
    "Beyonce",
    "Bono",
    "Boone",
    "Borat",
    "Branagh",
    "Brandy",
    "Beatrice Arthur",
    "Ben Affleck",
    "Benedict Arnold",
    "Benny Andersson",
    "Bibi Andersson",
    "Billie Joe Armstrong",
    "Brooks Atkinson",
    "Bryan Adams",
    "Bud Abbott",
    "Buzz Aldrin",
    "Barbara Bach",
    "Barbara Bush",
    "Barry Bonds",
    "Bear Bryant",
    "Beau Bridges",
    "Ben Blue",
    "Ben Bradlee",
    "Benjamin Britten",
    "Bertolt Brecht",
    "Big Bird",
    "Big Bopper",
    "Bill Berry",
    "Bill Bixby",
    "Bill Bradley",
    "Billie Burke",
    "Billy Barty",
    "Bix Beiderbecke",
    "Bob Barker",
    "Bonnie Bedelia",
    "Bonnie Blair",
    "Brendan Behan",
    "Brian Boitano",
    "Brigitte Bardot",
    "Buffalo Bill",
    "Burt Bacharach",
    "Busby Berkeley",
    "B�la Bart�k",
    "Barbara Carrera",
    "Ben Crenshaw",
    "Bert Convy",
    "Bill Clinton",
    "Bill Cosby",
    "Bill Cullen",
    "Billy Corgan",
    "Billy Crystal",
    "Billy Ray Cyrus",
    "Bing Crosby",
    "Bob Costas",
    "Bob Crane",
    "Bruce Catton",
    "Bud Collyer",
    "Bud Cort",
    "Butch Cassidy",
    "Barney the Dinosaur",
    "Barry Van Dyke",
    "Bette Davis",
    "Bo Derek",
    "Bo Diddley",
    "Bob Denver",
    "Bob Dole",
    "Bob Dorough",
    "Bob Dylan",
    "Bobby Darin",
    "Brad Dourif",
    "Brian DePalma",
    "Brooklyn Decker",
    "Bruce Dern",
    "Barbara Eden",
    "Bill Engvall",
    "Billy Eckstine",
    "Blake Edwards",
    "Bob Edwards",
    "Bob Eubanks",
    "Britt Ekland",
    "Buddy Ebsen",
    "Barbara Feldon",
    "Ben Franklin",
    "Benjamin Franklin",
    "Betty Ford",
    "Betty Friedan",
    "Bill C.W. McCall Fries",
    "Bob Fosse",
    "Bobby Fischer",
    "Bobby Flay",
    "Bonnie Franklin",
    "Brendan Fraser",
    "Barry Gibb",
    "Barry Goldwater",
    "Ben Gazzara",
    "Benny Goodman",
    "Berry Gordy",
    "Betty Grable",
    "Bill Gates",
    "Billy Gibbons",
    "Billy Graham",
    "Bob Geldof",
    "Bob Greene",
    "Bob Guccione",
    "Bobbie Gentry",
    "Bobby Goldsboro",
    "Boy George",
    "Brad Garrett",
    "Buddy Guy",
    "Barbara Harris",
    "Barbara Hershey",
    "Barbara Hutton",
    "Beck Hansen",
    "Ben Hogan",
    "Benjamin Harrison",
    "Benny Hill",
    "Betty Hutton",
    "Bill Haley",
    "Bill Hickok",
    "Bill Hicks",
    "Billie Holiday",
    "Bob Hope",
    "Bob Hoskins",
    "Bobby Hatfield",
    "Bobby Hull",
    "Bret Hart",
    "Brett Hull",
    "Bryan Dexter Holland",
    "Buck Henry",
    "Buddy Hackett",
    "Buddy Holly",
    "Billy Idol",
    "Burl Ives",
    "Barbara Jordan",
    "Bianca Jagger",
    "Billy Joel",
    "Bo Jackson",
    "Brian Jones",
    "Bruce Jenner",
    "B.B. King",
    "Bela Karolyi",
    "Ben Kingsley",
    "Beyonce Knowles",
    "Billie Jean King",
    "Billy the Kid",
    "Bob Captain Kangaroo Keeshan",
    "Bobby Knight",
    "Boris Karloff",
    "Brian Keith",
    "Buster Keaton",
    "Bela Lugosi",
    "Bert Lahr",
    "Brandon Lee",
    "Brenda Lee",
    "Brian Lamb",
    "Brooke Langton",
    "Bruce Lee",
    "Bucky Lasek",
    "Burt Lancaster",
    "Barbara Mandrell",
    "Barry Manilow",
    "Bat Man",
    "Bat Masterson",
    "Benito Mussolini",
    "Bernard Madoff",
    "Bernie Mac",
    "Bess Myerson",
    "Bette Midler",
    "Bill Maher",
    "Bill Mauldin",
    "Bill Medley",
    "Bill Moyers",
    "Bill Mumy",
    "Bill Murray",
    "Billy Mitchell",
    "Bob Marley",
    "Bob Monkhouse",
    "Bradley McIntosh",
    "Branford Marsalis",
    "Brent Musburger",
    "Brian McKnight",
    "Burgess Meredith",
    "Butterfly McQueen",
    "Barry Nelson",
    "Bebe Neuwirth",
    "Bob Newhart",
    "Brad Nowell",
    "Barack Obama",
    "Bobby Orr",
    "Beatrix Potter",
    "Bernadette Peters",
    "Bert Parks",
    "Bill Paxton",
    "Bill Pullman",
    "Billy Preston",
    "Blaise Pascal",
    "Bonnie Parker",
    "Boris Pasternak",
    "Brad Pitt",
    "Babe Ruth",
    "Bertrand Russell",
    "Betsy Ross",
    "Bill Russell",
    "Bobby Rydell",
    "Brandon Routh",
    "Brooks Robinson",
    "Buddy Rich",
    "Burt Reynolds",
    "B. F. Skinner",
    "B.F. Skinner",
    "Barbara Stanwyck",
    "Barbara Streisand",
    "Barbra Streisand",
    "Barry Sanders",
    "Bart Simpson",
    "Bedrich Smetana",
    "Ben Stiller",
    "Benjamin Spock",
    "Bessie Smith",
    "Beverly Sills",
    "Bo Schembechler",
    "Bob Saget",
    "Bob Schieffer",
    "Bob Segar",
    "Bob Seger",
    "Bobby Sherman",
    "Boris Spassky",
    "Bram Stoker",
    "Brendan Shanahan",
    "Britney Spears",
    "Brittany Spears",
    "Brooke Shields",
    "Bruce Springsteen",
    "Buffalo Bob Smith",
    "Bess Truman",
    "Betty Thomas",
    "Billy Bob Thornton",
    "Bishop Desmond Tutu",
    "Booker T",
    "Bj�rn Ulvaeus",
    "Bob Uecker",
    "Bobby Unser",
    "Brendon Urie",
    "Ben Vereen",
    "Bobby Vinton",
    "Brenda Vaccaro",
    "Barbara Walters",
    "Barry White",
    "Betty White",
    "Billy Dee Williams",
    "Billy Wilder",
    "Bob Weir",
    "Bob Wian",
    "Bob Woodward",
    "Booker T. Washington",
    "Bow Wow",
    "Brian Williams",
    "Brian Wilson",
    "Bruce Willis",
    "Bryan White",
    "Burt Ward",
    "Boris Yeltsin",
    "Burt Young",
    "Billy Zane",
    "Cantinflas",
    "Carew",
    "Cher",
    "Christo",
    "Cleopatra",
    "Colette",
    "Coolio",
    "Culkin",
    "Charles Addams",
    "Charles Atlas",
    "Chester A. Arthur",
    "Chet Atkins",
    "Christina Aguilara",
    "Claude Akins",
    "Cliff Arquette",
    "Criss Angel",
    "Camilla Parker Bowles",
    "Candace Bergen",
    "Candice Bergen",
    "Carl Bernstein",
    "Carla Bruni",
    "Carlos Bernard",
    "Carol Burnett",
    "Carroll Baker",
    "Chad Brannon",
    "Charles Babbage",
    "Charles Barkley",
    "Charles Boyer",
    "Charles Bronson",
    "Charles Bukowski",
    "Charlie Brown",
    "Charlotte Bronte",
    "Chris Brown",
    "Christian Bale",
    "Christie Brinkley",
    "Chuck Berry",
    "Claire Bloom",
    "Clara Barton",
    "Clara Bow",
    "Cliff Burton",
    "Clyde Barrow",
    "Corbin Bernsen",
    "Count Basie",
    "Cab Calloway",
    "Calvin Coolidge",
    "Candace Cameron",
    "Carlos Castaneda",
    "Carol Channing",
    "Cathy Lee Crosby",
    "Celia Cruz",
    "Cesar Chavez",
    "Charisma Carpenter",
    "Charlie Chaplin",
    "Chevy Chase",
    "Chick Corea",
    "Chris Carter",
    "Chris Cooper",
    "Christopher Columbus",
    "Christopher Cuomo",
    "Chubby Checker",
    "Chuck Connors",
    "Cindy Crawford",
    "Claudette Colbert",
    "Claudia Cardinale",
    "Clive Cussler",
    "Connie Chung",
    "Cris Collinsworth",
    "Cyd Charisse",
    "Cameron Diaz",
    "Catherine Deneuve",
    "Cecil B. DeMille",
    "Celine Dion",
    "Charles Dance",
    "Charles Darwin",
    "Charles Dickens",
    "Charles Durning",
    "Charlie Daniels",
    "Christian Doppler",
    "Chuck Daly",
    "Claire Danes",
    "Clarence Darrow",
    "Claude Debussy",
    "Colleen Dewhurst",
    "Count Dracula",
    "Courtnee Draper",
    "Carmen Electra",
    "Cedric the Entertainer",
    "Chad Everett",
    "Chris Elliott",
    "Chris Evert",
    "Clint Eastwood",
    "Calista Flockhart",
    "Carrie Fisher",
    "Chris Farley",
    "Colin Firth",
    "Connie Francis",
    "Carl XVI Gustav",
    "Carla Gugino",
    "Cary Grant",
    "Catherine the Great",
    "Cathy Guisewite",
    "Charles Goodyear",
    "Charles Grodin",
    "Charles de Gaulle",
    "Che Guevara",
    "Chief Dan George",
    "Chris Gaines",
    "Christopher Guest",
    "Chuck Greenburg",
    "Clark Gable",
    "Crystal Gayle",
    "Cuba Gooding",
    "Curt Gowdy",
    "C. Thomas Howell",
    "Celeste Holm",
    "Charleton Heston",
    "Charlton Heston",
    "Chet Huntley",
    "Chick Hearn",
    "Chrissie Hynde",
    "Clint Howard",
    "Coleman Hawkins",
    "Conrad Hilton",
    "Curly Howard",
    "Charles Ives",
    "Chris Isaak",
    "Christopher Isherwood",
    "C. G. Jung",
    "Carl Jung",
    "Carolyn Dawn Johnson",
    "Cherry Jones",
    "Chipper Jones",
    "Chris Jericho",
    "Chuck Jones",
    "Calvin Klein",
    "Captain Kangaroo",
    "Carol Kane",
    "Carole King",
    "Caroline Kennedy",
    "Casey Kasem",
    "Chaka Khan",
    "Charles Everett Koop",
    "Charles Kuralt",
    "Chiang Kai-Shek",
    "Clinton Kelly",
    "Coretta Scott King",
    "Craig Kilborn",
    "C. S. Lewis",
    "C.S. Lewis",
    "Carl Lewis",
    "Carol Lawrence",
    "Carole Lombard",
    "Charles Laughton",
    "Charles Lindbergh",
    "Charles Lucky Luciano",
    "Cheryl Ladd",
    "Christine Lahti",
    "Christopher Lee",
    "Christopher Lloyd",
    "Claude Lelouch",
    "Cleo Laine",
    "Cloris Leachman",
    "Courtney Love",
    "Cyndi Lauper",
    "Carlos Saul Menem",
    "Carmen Miranda",
    "Chad Michael Murray",
    "Charlie Musselwhite",
    "Chico Marx",
    "Chris Matthews",
    "Christa McAuliffe",
    "Christine McVie",
    "Chuck Mangione",
    "Claude Monet",
    "Clayton Moore",
    "Connie Mack",
    "Constance Moore",
    "Curtis Mayfield",
    "Cyrus McCormick",
    "Carry Nation",
    "Chester W. Nimitz",
    "Chris Noth",
    "Chuck Norris",
    "Craig T. Nelson",
    "Cynthia Nixon",
    "Cardinal John OConnor",
    "Carroll OConnor",
    "Charles Osgood",
    "Chris ODonnell",
    "Conan OBrien",
    "Conan Obrien",
    "Carlo Ponti",
    "Charles Perrault",
    "Charlie Bird Parker",
    "Charlie Pride",
    "Chris Pine",
    "Claude Pepper",
    "Cole Porter",
    "Colin L. Powell",
    "Colin Powell",
    "Cal Ripken",
    "Carl Reiner",
    "Cathy Rigby",
    "Cesar Romero",
    "Charles Ringling",
    "Charlie Rich",
    "Chita Rivera",
    "Chris Rock",
    "Christina Ricci",
    "Christopher Reeve",
    "Christopher Reeves",
    "Claude Rains",
    "Cliff Richard",
    "Cliff Robertson",
    "Cokie Roberts",
    "Condoleezza Rice",
    "Cyril Ritchard",
    "Carl Alfalfa Switzer",
    "Carl Sagan",
    "Carl Sandburg",
    "Carly Simon",
    "Carrie Snodgress",
    "Carroll Spinney",
    "Casey Stengel",
    "Cat Stevens",
    "Charles Schulz",
    "Charles Tom Thumb Stratton",
    "Charlie Sheen",
    "Chesley Sully Sullenberger",
    "Chiang Kai Shek",
    "Chris Schenkel",
    "Chris Squire",
    "Christian Slater",
    "Claudia Schiffer",
    "Cole Sprouse",
    "Colonel Harland Sanders",
    "Connie Stevens",
    "Craig Sheffer",
    "Cree Summer",
    "Curtis Sliwa",
    "Cybill Shepherd",
    "Carrot Top",
    "Charlize Theron",
    "Cheryl Tiegs",
    "Chris Tucker",
    "Cicely Tyson",
    "Claire Trevor",
    "Clyde W. Tombaugh",
    "Concetta Tomei",
    "Conway Twitty",
    "Carrie Underwood",
    "Cassie Ventura",
    "Charlie Watts",
    "Chris Wallace",
    "Christopher Walken",
    "Christopher Wren",
    "Cindy Williams",
    "Cornel Wilde",
    "Carl Yastrzemski",
    "Charles Yeager",
    "Chuck Yeager",
    "Cy Young",
    "Dan",
    "Dilbert",
    "Divine",
    "Dominique",
    "Donovan",
    "Dorothy",
    "Dracula",
    "Dan Aykroyd",
    "Danny Aiello",
    "Darrell Abbott",
    "Debbie Allen",
    "Desi Arnaz",
    "Devon Aoki",
    "Dianna Agron",
    "Dimebag Darrell Abbott",
    "Don Adams",
    "Don Ameche",
    "Douglas Adams",
    "Duane Allman",
    "Dan Blocker",
    "Dan Brown",
    "Daniel Boone",
    "Danny Bonaduce",
    "Danny Boyle",
    "Dante Basco",
    "Dave Brubeck",
    "David Beckham",
    "David Blaine",
    "David Boreanaz",
    "David Bowie",
    "David Brenner",
    "David Brinkley",
    "David Byrne",
    "Daws Butler",
    "Debby Boone",
    "Delta Burke",
    "Dennis Banks",
    "Dewey Bunnell",
    "Dick Butkus",
    "Dick Button",
    "Dirk Benedict",
    "Dirk Bogarde",
    "Don Bendell",
    "Doyle Brunson",
    "Drew Barrymore",
    "Drew Barymore",
    "Drew Bledsoe",
    "Drew Brees",
    "Dabney Coleman",
    "Dale Carnegie",
    "Dan Castellaneta",
    "Dana Carvey",
    "Darva Conger",
    "Dave Chappelle",
    "Dave Clark",
    "Dave Coulier",
    "David Carradine",
    "David Caruso",
    "David Cassidy",
    "David Clayton-Thomas",
    "David Copperfield",
    "David Crosby",
    "Davy Crockett",
    "Deepak Chopra",
    "Diahann Carroll",
    "Dick Cavett",
    "Dick Cheney",
    "Dick Clark",
    "Doug Clifford",
    "Drew Carey",
    "Dyan Cannon",
    "Daniel Day-Lewis",
    "Danny DeVito",
    "Daryl Dragon",
    "Dave Davies",
    "David Duchovney",
    "David Duchovny",
    "Dennis Day",
    "Diana DeGarmo",
    "Dick Van Dyke",
    "Dimebag Darrell",
    "Dizzy Dean",
    "Dom DeLuise",
    "Dom DiMaggio",
    "Don Drysdale",
    "Doris Day",
    "Dr. Charles Drew",
    "Dr. Dre",
    "Dr. Drew",
    "Dale Earnhardt",
    "Dale Earnhart",
    "Dale Evans",
    "Danny Elfman",
    "Dave The Edge Evans",
    "David James Elliott",
    "Denholm Elliott",
    "Don Everly",
    "Duane Eddy",
    "Duke Ellington",
    "Dwight D. Eisenhower",
    "Dwight Eisenhower",
    "Daisy Fuentes",
    "Dakota Fanning",
    "David Frost",
    "Dawn French",
    "Dennis Franz",
    "Diane von Furstenburg",
    "Don Francisco",
    "Donna Fargo",
    "Douglas Fairbanks",
    "Douglas Fraser",
    "D.W. Griffith",
    "Dan George",
    "Dann Gillen",
    "Danny Glover",
    "David Gavurin",
    "David Geffen",
    "David Gilmour",
    "Deborah Gibson",
    "Dick Gregory",
    "Dizzy Gillespie",
    "Duff Goldman",
    "Dwight Gooden",
    "Dana Hamm",
    "Daryl Hannah",
    "Dashiell Hammett",
    "David Hasselhoff",
    "Deborah Harry",
    "Dennis Hastert",
    "Dennis Hopper",
    "Doc Holliday",
    "Dolores Hope",
    "Don Henley",
    "Don Hewitt",
    "Don Ho",
    "Don Mr. Wizard Herbert",
    "Dorothy Hamill",
    "Doug Henning",
    "Dustin Hoffman",
    "Dwayne Hickman",
    "Dwight Howard",
    "Don Imus",
    "Dan Jansen",
    "Daniel Johns",
    "David Janssen",
    "David Jason",
    "Davy Jones",
    "Dean Jagger",
    "Dean Jones",
    "Derek Jeter",
    "Dr. J",
    "Dwayne Johnson",
    "Danny Kaye",
    "Daren Kagasoff",
    "DeForest Kelley",
    "Deborah Kerr",
    "Diane Keaton",
    "Don Knotts",
    "Donna Karan",
    "Duke Kahanamoku",
    "Durward Kirby",
    "D.H. Lawrence",
    "Dalai Lama",
    "Daniel Day Lewis",
    "Dave Letterman",
    "David Lean",
    "David Letterman",
    "David Lynch",
    "Demi Lovato",
    "Denis Leary",
    "Diane Ladd",
    "Diane Lane",
    "Dino De Laurentiis",
    "Dorothea Lange",
    "Dorothy Lamour",
    "Dr. Laura",
    "Drew Lachey",
    "Dan Marino",
    "Dan Millman",
    "Darren McGavin",
    "Dave Matthews",
    "David Mamet",
    "David McCallum",
    "Dean Martin",
    "Demi Moore",
    "Dennis Miller",
    "Dick Martin",
    "Dickie Moore",
    "Dina Merrill",
    "Don Mattingly",
    "Don McLean",
    "Donna Mills",
    "Donny Most",
    "Dorothy Malone",
    "Douglas MacArthur",
    "Dr. Phil McGraw",
    "Dudley Moore",
    "David Nelson",
    "David Niven",
    "Dirk Nowitzky",
    "Don Novello",
    "Dr. No",
    "David Ossman",
    "Dick ONeill",
    "Donald OConnor",
    "Donny Osmond",
    "Dan Peek",
    "Dana Plato",
    "Danica Patrick",
    "David Hyde Pierce",
    "David Paterson",
    "Dev Patel",
    "Dick Powell",
    "Dick Van Patten",
    "Dolly Parton",
    "Donald Pleasence",
    "Dorothy Parker",
    "Dorothy Provine",
    "Dr. Drew Pinsky",
    "Dr. Phil",
    "Dan Quayle",
    "Dennis Quaid",
    "Dale Robertson",
    "Damon Runyon",
    "Dan Rather",
    "Dan Rowan",
    "Dave Ramsey",
    "David Lee Roth",
    "David Robinson",
    "Debbie Reynolds",
    "Della Reese",
    "Denise Richards",
    "Diana Rigg",
    "Diana Ross",
    "Diego Rivera",
    "Django Reinhardt",
    "Don Rickles",
    "Donna Reed",
    "Doris Roberts",
    "Dr. Ruth",
    "Daniel Schorr",
    "Daniel Stern",
    "Danielle Steel",
    "Darryl Strawberry",
    "Daryl Strawberry",
    "David O. Selznick",
    "David Sarnoff",
    "David Schwimmer",
    "David Silveria",
    "David Soul",
    "David Spade",
    "David Susskind",
    "Dean Stockwell",
    "Dee Snider",
    "Deion Sanders",
    "Del Shannon",
    "Diane Sawyer",
    "Dick Smothers",
    "Dinah Shore",
    "Dmitri Shostakovich",
    "Doc Severinsen",
    "Don Shula",
    "Donald Sutherland",
    "Donna J. Stone",
    "Donna Summer",
    "Dr. Benjamin Spock",
    "Dr. Laura Schlessinger",
    "Dr. Seuss",
    "Duke Snider",
    "Dusty Springfield",
    "Dylan Sprouse",
    "Danny Thomas",
    "David Clayton Thomas",
    "Donald Trump",
    "Dylan Thomas",
    "Darth Vader",
    "Dick Vitale",
    "Damon Wayans",
    "Daniel Hale Williams",
    "Daniel Webster",
    "Dawn Wells",
    "Debra Winger",
    "Dennis Weaver",
    "Dennis Wilson",
    "Denzel Washington",
    "Dianne Wiest",
    "Dionne Warwick",
    "Doc Watson",
    "Donnie Wahlberg",
    "Dr. Daniel Hale Williams",
    "Dr. Ruth Westheimer",
    "Dwayne Wade",
    "Dwyane Wade",
    "Deng Xiaoping",
    "Dwight Yoakam",
    "Daphne Zuniga",
    "Eisenhower",
    "Elmo",
    "Eminem",
    "Earl Anthony",
    "Ed Ames",
    "Ed Asner",
    "Ed Autry",
    "Eddie Albert",
    "Eddy Arnold",
    "Edie Adams",
    "Edward Albee",
    "Edwin Buzz Aldrin",
    "Elvis Andrus",
    "Erin Andrews",
    "Eve Arden",
    "Ed Begley",
    "Ed Bradley",
    "Edd Kookie Byrnes",
    "Eddie Belfour",
    "Eddie Bracken",
    "Edgar Bergen",
    "Edgar Rice Burroughs",
    "Eileen Brennan",
    "Elizabeth Barrett Browning",
    "Ellen Barkin",
    "Ellen Burstyn",
    "Emily Bronte",
    "Eric Bana",
    "Eric Burdon",
    "Erik Bruhn",
    "Erma Bombeck",
    "Ernest Borgnine",
    "Ernie Banks",
    "Ethel Barrymore",
    "Earl Campbell",
    "Eddie Cantor",
    "Eldridge Cleaver",
    "Elvis Costello",
    "Enrico Caruso",
    "Eric Clapton",
    "e.e. cummings",
    "Edgar Degas",
    "Elizabeth Dole",
    "Ellen DeGeneres",
    "Ellen Degenerous",
    "Emily Dickinson",
    "Edward Elgar",
    "Elizabeth Edwards",
    "Emilio Estavez",
    "Emilio Estevez",
    "Eric Estrada",
    "Erik Estrada",
    "Eddie Fisher",
    "Edward Furlong",
    "Eileen Farrell",
    "Eileen Ford",
    "Ella Fitzgerald",
    "Emerson Fittipaldi",
    "Enrico Fermi",
    "Errol Flynn",
    "Eddie Guerrero",
    "Edmund Gwenn",
    "Elliott Gould",
    "Erroll Garner",
    "Estelle Getty",
    "Eva Gabor",
    "Evan Grant",
    "Evonne Goolagong",
    "Eydie Gorme",
    "Earl Fatha Hines",
    "Ed Harris",
    "Edd Hall",
    "Eddie Van Halen",
    "Edmund Hillary",
    "Edwin Hubble",
    "Elizabeth Hurley",
    "Emmylou Harris",
    "Erin Hershey",
    "Ernest Hemingway",
    "Ernie Harwell",
    "Estelle Halliwell",
    "Enrique Iglesias",
    "Eugene Ionesco",
    "Earvin Magic Johnson",
    "Ellen Johnson-Sirleaf",
    "Elton John",
    "Erica Jong",
    "Ervin Magic Johnson",
    "Eartha Kitt",
    "Edward M. Kennedy",
    "Elia Kazan",
    "Emmett Kelly",
    "Ernie Kovacs",
    "Ethel Kennedy",
    "Evel Knievel",
    "Elmore Leonard",
    "Eric Lindros",
    "Eugene Levy",
    "Eva Longoria",
    "E.G. Marshall",
    "Ed McMahon",
    "Eddie Money",
    "Eddie Murphey",
    "Eddie Murphy",
    "Eddie Murray",
    "Edouard Manet",
    "Edward R. Murrow",
    "Elaine May",
    "Elijah Muhammad",
    "Elizabeth Montgomery",
    "Elle Macpherson",
    "Ethel Merman",
    "Eugene McCarthy",
    "Eva Mendes",
    "Ewan McGregor",
    "Ed Norton",
    "Edward Norton",
    "Edwin Newman",
    "Ed ONeill",
    "Ed Oneill",
    "Emily Osment",
    "Eugene ONeill",
    "Eugene Ormandy",
    "Edgar Allan Poe",
    "Edgar Allen Poe",
    "Edith Piaf",
    "Eleanor Parker",
    "Elvis Presley",
    "Emily Post",
    "Estelle Parsons",
    "Eva Peron",
    "Ezra Pound",
    "Eddie Rabbit",
    "Eleanor Roosevelt",
    "Emily Robison",
    "Eric Roberts",
    "Esther Rolle",
    "Earl DMX Simmons",
    "Earl Scheib",
    "Ed Sullivan",
    "Edward Steichen",
    "Elisabeth Shue",
    "Elizabeth Ann Seton",
    "Elke Sommer",
    "Ellen Johnson Sirleaf",
    "Emmitt Smith",
    "Engineer Bill Stulla",
    "Eric Sevareid",
    "Eric Stoltz",
    "Eric Szmanda",
    "Erich Segal",
    "Erik Everlast Schrody",
    "Eva Marie Saint",
    "E T",
    "Elizabeth Taylor",
    "Emma Thompson",
    "Eddie Cleanhead Vinson",
    "Eddie Van-Halen",
    "Eddie Vedder",
    "E.B. White",
    "Edgar Winter",
    "Edith Wharton",
    "Edward D. Wood",
    "Edward Woodward",
    "Eli Wallach",
    "Elijah Wood",
    "Emma Watson",
    "Esther Williams",
    "Ethel Waters",
    "Eudora Welty",
    "Fabian",
    "Fabio",
    "Fergie",
    "Flea",
    "Fogelberg",
    "F. Murray Abraham",
    "Fiona Apple",
    "Frank Abagnale",
    "Frankie Avalon",
    "Fred Allen",
    "Fred Astaire",
    "Frederick Ashton",
    "F Lee Bailey",
    "F. Lee Bailey",
    "Fanny Brice",
    "Foster Brooks",
    "Foxy Brown",
    "Francis Bacon",
    "Frank Borman",
    "Freddie Blassie",
    "Felipe Calder�n",
    "Fidel Castro",
    "Francis Coppala",
    "Francis Coppola",
    "Frank Caliendo",
    "Frank Capra",
    "Fred Couples",
    "Frederic Chopin",
    "F.W. deKlerk",
    "Fats Domino",
    "Faye Dunaway",
    "Fran Drescher",
    "Fran Dresher",
    "Fred Durst",
    "Frederick Douglass",
    "Fyodor Dostoevsky",
    "Fedor Emelianenko",
    "Farrah Fawcett",
    "Federico Fellini",
    "Flavor Flav",
    "Francisco Franco",
    "Farley Granger",
    "Forrest Gump",
    "Frank Gifford",
    "Frank Gorshin",
    "Fred Gwynne",
    "Faith Hill",
    "Felicity Huffman",
    "Friedensreich Hundertwasser",
    "Francis Scott Key",
    "Franz Kafka",
    "Frida Kahlo",
    "Frances Langford",
    "Frank Langella",
    "Frankie Laine",
    "Franz Liszt",
    "Frederick Loewe",
    "Ferdinand Jelly Roll Morton",
    "Frank Tug McGraw",
    "Frankie Manning",
    "Fred MacMurray",
    "Freddie Mercury",
    "Fayard Nicholas",
    "Fred Norris",
    "Frank Oz",
    "Fess Parker",
    "Floyd Patterson",
    "Franklin Pierce",
    "Freddie Prinze",
    "Frank Rizzo",
    "Frank Robinson",
    "Franklin D. Roosevelt",
    "Fred Rogers",
    "Frank Sinatra",
    "French Stewart",
    "Fran Tarkenton",
    "Fernando Valenzuela",
    "Frankie Valli",
    "Fats Waller",
    "Fay Wray",
    "Flip Wilson",
    "Forest Whitaker",
    "Frank Lloyd Wright",
    "Florenz Ziegfeld",
    "Franco Zeffirelli",
    "Frank Zappa",
    "Galileo",
    "Gallagher",
    "Gandhi",
    "Geri",
    "Grover",
    "Gene Autry",
    "Gillian Anderson",
    "Giorgio Armani",
    "Gracie Allen",
    "Gregg Allman",
    "Garth Brooks",
    "Gary Burghoff",
    "Gary Busey",
    "Gary U.S. Bonds",
    "Gene Barry",
    "Genevieve Bujold",
    "George Balanchine",
    "George Benson",
    "George Blaha",
    "George Brett",
    "George Burns",
    "George Bush",
    "George W. Bush",
    "Georges Bizet",
    "Gerry Beckley",
    "Ginger Baker",
    "Glenn Beck",
    "Gordon Brown",
    "Grace Bumbry",
    "Gwendolyn Brooks",
    "G.K. Chesterton",
    "Gary Coleman",
    "Gary Cooper",
    "George Carlin",
    "George Clooney",
    "George Crockett",
    "George M. Cohan",
    "Geraldine Chaplin",
    "Glen Campbell",
    "Glenn Close",
    "Grover Cleveland",
    "Gary DellAbate",
    "Geena Davis",
    "George Dolenz",
    "Gina Davis",
    "Gloria Estefan",
    "George Foreman",
    "Gerald R. Ford",
    "Geraldine Ferraro",
    "Glenn Ford",
    "Glenn Frey",
    "Gracie Fields",
    "Guy Fieri",
    "Gale Gordon",
    "Galileo Galilei",
    "George Gershwin",
    "George Gobel",
    "Gilbert Godfried",
    "Gilbert Gottfried",
    "Glenn Gould",
    "Gloria Gaynor",
    "Greer Garson",
    "Greta Garbo",
    "Gabby Hayes",
    "Gene Hackman",
    "George Hamilton",
    "George Harrison",
    "George Roy Hill",
    "Goldie Hawn",
    "Gordie Howe",
    "Grant Hill",
    "Gregory Harrison",
    "Gregory Hines",
    "George Jones",
    "Glenda Jackson",
    "Glynis Johns",
    "Gordon Jump",
    "Gabe Kaplan",
    "Garrison Keillor",
    "Garry Kasparov",
    "Gene Kelly",
    "Gene Krupa",
    "George Kennedy",
    "George Machine Gun Kelly",
    "Gladys Knight",
    "Grace Kelly",
    "G. Gordon Liddy",
    "Gary Larson",
    "Gaston Leroux",
    "Geddy Lee",
    "George Lopez",
    "George Lucas",
    "Giada De Laurentiis",
    "Gina Lollobrigida",
    "Gordon Lightfoot",
    "Greg LeMond",
    "Guy Lombardo",
    "Gypsy Rose Lee",
    "Garrett Morgan",
    "Garrett Morris",
    "Garry Moore",
    "Gary Moore",
    "Gavin MacLeod",
    "George C. Marshall",
    "George Martin",
    "George McGovern",
    "George Murphy",
    "George Spanky McFarland",
    "Gisele MacKenzie",
    "Glenn Miller",
    "Golda Meir",
    "Gordon MacRae",
    "Grandma Moses",
    "Greg Morris",
    "Gregor Mendel",
    "Groucho Marx",
    "Guglielmo Marconi",
    "Gummo Marx",
    "Guy Madison",
    "George Noory",
    "Graham Nash",
    "Greg Norman",
    "Gary Oldman",
    "Gary Owens",
    "George Orwell",
    "Georgia OKeeffe",
    "Gary Player",
    "Gene De Paul",
    "George Patton",
    "George Peppard",
    "George Plimpton",
    "Georges Pompidou",
    "Giacomo Puccini",
    "Gordon Parks",
    "Grace Potter",
    "Gregory Peck",
    "Guy Pearce",
    "Gwyneth Paltrow",
    "Gena Rowlands",
    "Gene Rayburn",
    "Gene Roddenberry",
    "George A. Romero",
    "George Reeves",
    "Gilda Radner",
    "Ginger Rogers",
    "Grigori Rasputin",
    "Guy Ritchie",
    "Gabriela Sabatini",
    "Gale Storm",
    "Garry Shandling",
    "Gary Sandy",
    "Gary Sinise",
    "Gene Simmons",
    "Gene Siskel",
    "George Beverly Shea",
    "George C. Scott",
    "George Segal",
    "George Shearing",
    "George Stephanopoulos",
    "George Strait",
    "Georges Seurat",
    "Gertrude Stein",
    "Gloria Steinem",
    "Gloria Stuart",
    "Gloria Swanson",
    "Grace Slick",
    "Guitar Shorty",
    "Gwen Stefani",
    "George Takei",
    "George Thorogood",
    "Grant Tinker",
    "Galina Ulanova",
    "Gianni Versace",
    "Giuseppe Verdi",
    "Gloria Vanderbilt",
    "Gore Vidal",
    "Gwen Verdon",
    "Gahan Wilson",
    "Gene Wilder",
    "George F. Will",
    "George Washington",
    "George Wendt",
    "George Westinghouse",
    "Gerard Way",
    "Grant Wood",
    "Glenn Yarborough",
    "Houdini",
    "Hutton",
    "Hank Aaron",
    "Hank Azaria",
    "Hans Christian Anderson",
    "Henry Hank Aaron",
    "Herb Alpert",
    "Horatio Alger",
    "Halle Berry",
    "Harry Belafonte",
    "Henri Cartier Bresson",
    "Hugh Beaumont",
    "Humphrey Bogart",
    "Hans Christian-Anderson",
    "Hans Conried",
    "Harry Caray",
    "Harry Carrey",
    "Harry Chapin",
    "Hayden Christensen",
    "Heloise Bowles Cruse",
    "Henri Cartier-Bresson",
    "Herb Caen",
    "Hillary Clinton",
    "Hoagy Carmichael",
    "Holly Marie Combs",
    "Howard Carter",
    "Howard Cosell",
    "Hume Cronyn",
    "Harley Davidson",
    "Heavy D",
    "Hilary Duff",
    "Howie Dorough",
    "Hugh Downs",
    "Hallie Eisenberg",
    "Herm Edwards",
    "Harrison Ford",
    "Harvey Fierstein",
    "Harvey Firestone",
    "Henry Fonda",
    "Henry Ford",
    "H.R. Giger",
    "Heather Graham",
    "Henry Gibson",
    "Hetty Green",
    "Hugh Grant",
    "Hal Holbrook",
    "Harry Hamlin",
    "Harry Houdini",
    "Hedda Hopper",
    "Helen Hayes",
    "Helen Hunt",
    "Henry John Heinz",
    "Herbert Hoover",
    "Herbie Hancock",
    "Herman Hollerith",
    "Hermann Hesse",
    "Holly Hunter",
    "Howard Hesseman",
    "Howard Hughes",
    "Hugh Hefner",
    "Hulk Hogan",
    "Huntz Hall",
    "Harry James",
    "Henry James",
    "Hu Jintao",
    "Hugh Jackman",
    "Hank Ketcham",
    "Harvey Keitel",
    "Harvey Korman",
    "Heidi Klum",
    "Helen Keller",
    "Henry A. Kissinger",
    "Henry Kissinger",
    "Howard Keel",
    "H.P. Lovecraft",
    "Hal Linden",
    "Harold Lloyd",
    "Harper Lee",
    "Heath Ledger",
    "Heather Locklear",
    "Henry Wadsworth Longfellow",
    "Huddie Lead Belly Ledbetter",
    "Harry Morgan",
    "Harvey Milk",
    "Hayley Mills",
    "Heidi Montag",
    "Helen Mirren",
    "Hendrik Meijer",
    "Henri Mancini",
    "Henri Matisse",
    "Henry Mancini",
    "Henry Miller",
    "Henry Morgan",
    "Herbie Mann",
    "Herman Melville",
    "Ho Chi Minh",
    "Hosni Mubarak",
    "Howie Mandel",
    "Harold Nicholas",
    "Harriet Nelson",
    "H.C. Oersted",
    "Hakeem Olajuwon",
    "Haley Joel Osment",
    "Helen OConnell",
    "Hugh OBrian",
    "H. Ross Perot",
    "Harold Pinter",
    "Harve Presnell",
    "Hayden Panettiere",
    "Hal Roach",
    "Harold Pee Wee Reese",
    "Harold Ramis",
    "Harold Robbins",
    "Harry Reasoner",
    "Helen Reddy",
    "Howard Rollins",
    "Han Solo",
    "Hannah Spearritt",
    "Harriet Beecher Stowe",
    "Harry Shearer",
    "Hilary Swank",
    "Hillary Swank",
    "Homer Simpson",
    "Horace Silver",
    "Howard Stern",
    "Harry S. Truman",
    "Harry Truman",
    "H.G. Wells",
    "Hank Williams",
    "Harriet Wheeler",
    "Henry Winkler",
    "Herschel Walker",
    "Henny Youngman",
    "Ian Anderson",
    "Isaac Asimov",
    "Ingmar Bergman",
    "Ingrid Bergman",
    "Irving Berlin",
    "Ice Cube",
    "Imogene Coca",
    "Irene Cara",
    "Irene Dunne",
    "Isadora Duncan",
    "Ian Fleming",
    "Indira Gandhi",
    "Ira Gershwin",
    "Ira Glass",
    "Isaac Hayes",
    "Ida Lupino",
    "Ian McDiarmid",
    "Ian McKellen",
    "Isaac Newton",
    "I.M. Pei",
    "Iggy Pop",
    "Irene Papas",
    "Itzhak Perlman",
    "Ivan Pavlov",
    "Igor Stravinsky",
    "Ione Skye",
    "Isaac Stern",
    "Isabel Sanford",
    "Ice T",
    "Ike Turner",
    "Isiah Thomas",
    "Ivana Trump",
    "Ian Ziering",
    "Jackson",
    "Juanes",
    "Jack Anderson",
    "James Agee",
    "James Arness",
    "Jane Austen",
    "Jean Arthur",
    "Jennifer Aniston",
    "Jessica Alba",
    "Joan Van Ark",
    "Joan of Arc",
    "John Adams",
    "John Amos",
    "John Astin",
    "John James Audubon",
    "John Quincy Adams",
    "Jon Anderson",
    "Julie Andrews",
    "June Allyson",
    "J Boog",
    "Jack Benny",
    "Jack Black",
    "Jack Bruce",
    "Jackson Browne",
    "Jacqueline Bisset",
    "James Baldwin",
    "James Bond",
    "James Brown",
    "James Buchanan",
    "James L. Brooks",
    "Javier Bardem",
    "Jean-Paul Belmondo",
    "Jeff Bezos",
    "Jeff Bridges",
    "Jennifer Beals",
    "Jenson Button",
    "Jessica Biel",
    "Jill Biden",
    "Jim Backus",
    "Jim Bakker",
    "Jim Belushi",
    "Jim Brown",
    "Jimmy Breslin",
    "Jimmy Buffett",
    "Joan Baez",
    "Joe Biden",
    "Joe E. Brown",
    "Joey Bishop",
    "Johann Sebastian Bach",
    "John Barry",
    "John Barrymore",
    "John Belushi",
    "John Bonham",
    "John Brown",
    "Johnny Bench",
    "Jon Bon-Jovi",
    "Jonathan Brandis",
    "Joseph Barbera",
    "Josephine Baker",
    "Judy Blume",
    "Juliette Binoche",
    "Justin Bieber",
    "J.C. Chasez",
    "J.J. Cale",
    "Jack Casady",
    "Jackie Chan",
    "Jackie Collins",
    "Jackie Coogan",
    "Jackie Cooper",
    "Jacques Cousteau",
    "James Caan",
    "James Cagney",
    "James Cameron",
    "James Caviezel",
    "James Coburn",
    "Jamie Lee Curtis",
    "Jane Curtin",
    "Jean Chr�tien",
    "Jean Cocteau",
    "Jeanne Crain",
    "Jeff Chandler",
    "Jennifer Capriati",
    "Jennifer Connelly",
    "Jeremy Castle",
    "Jesus Christ",
    "Jill Clayburgh",
    "Jim Carrey",
    "Jim Corr",
    "Jim Courier",
    "Jim Croce",
    "Jimmy Carter",
    "Jimmy Conners",
    "Jimmy Connors",
    "Joan Chen",
    "Joan Collins",
    "Joan Crawford",
    "Joan Cusack",
    "Joe Cocker",
    "John Cage",
    "John Candy",
    "John Carpenter",
    "John Cena",
    "John Chapman",
    "John Cleese",
    "John Coltrane",
    "John Cusack",
    "John Le Carre",
    "Johnny Carson",
    "Johnny Cash",
    "Jon Cryer",
    "Joseph Campanella",
    "Joseph Conrad",
    "Joseph Cotten",
    "Juan Carlos",
    "Judy Collins",
    "Julia Child",
    "Julian Casablancas",
    "Jack Dempsey",
    "Jakob Dylan",
    "James Daughton",
    "James Dean",
    "James Dickey",
    "James Doohan",
    "Jeff Daniels",
    "Jefferson Davis",
    "Jerry Van Dyke",
    "Jim Davis",
    "Jimmy Dean",
    "Jimmy Dorsey",
    "Jimmy Durante",
    "Joe Dante",
    "Joe DiMaggio",
    "Joe Dimaggio",
    "John Davidson",
    "John Deacon",
    "John Densmore",
    "John Denver",
    "John Derek",
    "John Dillinger",
    "Johnny Depp",
    "Joyce DeWitt",
    "Judy Dench",
    "Julia Louis Dreyfus",
    "Jason Earles",
    "Jenna Elfman",
    "Jill Eikenberry",
    "John Elway",
    "John Entwistle",
    "Julius Dr. J Erving",
    "Julius Erving",
    "James Farentino",
    "James Fox",
    "James Franciscus",
    "James Franco",
    "Jamie Farr",
    "Jamie Foxx",
    "Jane Fonda",
    "Jane Froman",
    "Jeff Fahey",
    "Jeff Foxworthy",
    "Jerry Falwell",
    "Jimmy Fallon",
    "Joan Fontaine",
    "Jodie Foster",
    "Joe Frazier",
    "Joey Fatone",
    "John Ford",
    "John Forsythe",
    "Jos� Feliciano",
    "Jos� Ferrer",
    "Jules Feiffer",
    "June Foray",
    "J. Paul Getty",
    "Jackie Gleason",
    "Jake Gyllenhaal",
    "James Galway",
    "James Gandolfini",
    "James Garfield",
    "James Garner",
    "Jane Goodall",
    "Janeane Garofalo",
    "Jasmine Guy",
    "Jean-Luc Godard",
    "Jean-Paul Gaultier",
    "Jeff Goldblum",
    "Jeff Gordon",
    "Jennie Garth",
    "Jennifer Garner",
    "Jerry Garcia",
    "Joe Garagiola",
    "Joel Grey",
    "Johann von Goethe",
    "Johannes Gutenberg",
    "John Gielgud",
    "John Glenn",
    "John Gosselin",
    "John Grisham",
    "Johnny Gruelle",
    "Jon Gosselin",
    "Jose Greco",
    "Josh Golden",
    "Josh Groban",
    "Judy Garland",
    "J. Edgar Hoover",
    "James Herriot",
    "James Hetfield",
    "James Hunt",
    "Jan Hooks",
    "Jean Harlow",
    "Jeff Hardy",
    "Jennifer Love Hewitt",
    "Jesse Helms",
    "Jill Hennessy",
    "Jim Henson",
    "Jimi Hendrix",
    "Jimmy Hoffa",
    "Joey Heatherton",
    "John Hancock",
    "John Hughes",
    "John Hurt",
    "John Huston",
    "John Lee Hooker",
    "Jon Hamm",
    "Jools Holland",
    "Joseph Haydn",
    "Josh Hartnett",
    "Judd Hirsch",
    "James Merritt Ives",
    "Janis Ian",
    "Jeremy Irons",
    "Jill Ireland",
    "Judge Lance Ito",
    "Julio Iglesias",
    "Jack Jones",
    "Jackie Joyner-Kersee",
    "James Earl Jones",
    "James Joyce",
    "Janet Jackson",
    "Janis Joplin",
    "Jasper Johns",
    "Jennifer Jones",
    "Jenny Jones",
    "Jermaine Jackson",
    "Jesse Jackson",
    "Jesse James",
    "Jill St. John",
    "Joan Jett",
    "Joe Jonas",
    "John H. Johnson",
    "John Paul Jones",
    "Jon Bon Jovi",
    "Judith Jamison",
    "Jack Kemp",
    "Jack Kerouac",
    "Jack Klugman",
    "Jackie Joyner Kersee",
    "Jane Kaczmarek",
    "Jean-Claude Killy",
    "Jerome Kern",
    "Jerzy Kosinski",
    "Joanna Kerns",
    "Johannes Kepler",
    "John F. Kennedy",
    "John Katz",
    "John Keats",
    "John Kerry",
    "John Krasinski",
    "Joseph P. Kennedy",
    "Joyce Kilmer",
    "Julie Kavner",
    "Jack LaLanne",
    "Jack Lemmon",
    "Jack London",
    "Jack Lord",
    "Jack Lousma",
    "Jake LaMotta",
    "James Longstreet",
    "Janet Leigh",
    "Jason Lee",
    "Jay Leno",
    "Jeff Licon",
    "Jennifer Jason Leigh",
    "Jennifer Lopez",
    "Jerry Lee Lewis",
    "Jerry Lewis",
    "Jessica Lange",
    "Jet Li",
    "Joan Lunden",
    "Joe E. Lewis",
    "Joe Louis",
    "Joey Lawrence",
    "John Landis",
    "John Larroquette",
    "John Leguizamo",
    "John Lennon",
    "John Lewis",
    "John Lithgow",
    "John Phillip Law",
    "Jon Lee",
    "Jon Lovitz",
    "Jude Law",
    "Julia Louis-Dreyfus",
    "Julian Lennon",
    "Julie London",
    "Juliette Lewis",
    "Juliette Low",
    "June Lockhart",
    "J.P. McCarthy",
    "Jackie Mason",
    "James Madison",
    "James Marsters",
    "James Mason",
    "James Michener",
    "James Monroe",
    "James Morrison",
    "Jan Merlin",
    "Jayne Mansfield",
    "Jayne Meadows",
    "Jean Marsh",
    "Jeanne Moreau",
    "Jillian Michaels",
    "Jim McKay",
    "Jim Messina",
    "Jim Morrison",
    "Joan Mir�",
    "Joe Montana",
    "Joel McCrea",
    "John Madden",
    "John Major",
    "John Malkovich",
    "John Mayall",
    "John Mayer",
    "John McCain",
    "John McEnroe",
    "John Mills",
    "John Milton",
    "John Muir",
    "John Singleton Mosby",
    "Johnny Mathis",
    "Johnny Mercer",
    "Johnny Miller",
    "Joni Mitchell",
    "Julian McMahon",
    "Julianne Moore",
    "Juliet Mills",
    "Jack Nicholson",
    "Jack Nicklaus",
    "Jack Niclaus",
    "James Naismith",
    "James Noble",
    "Jason Curtis Newsted",
    "Jason Newsted",
    "Jawaharlal Nehru",
    "Jay North",
    "Jim Nabors",
    "Joe Namath",
    "Johnette Napolitano",
    "Judd Nelson",
    "Julie Newmar",
    "Jacqueline Kennedy Onasis",
    "Jennifer ONeill",
    "Jerry Orbach",
    "Jesse Owens",
    "Jo OMeara",
    "Johnny Otis",
    "Joyce Carol Oates",
    "Jack Paar",
    "Jack Palance",
    "Jackson Pollock",
    "James Cash Penney",
    "James K. Polk",
    "James Patterson",
    "Jane Pauley",
    "Jason Priestley",
    "Jean Luc Ponty",
    "Jean Piaget",
    "Jeff Probst",
    "Jim Palmer",
    "Jimmy Page",
    "Joe Paterno",
    "Joe Perry",
    "Joe Pesci",
    "Joe Piscopo",
    "John J. Pershing",
    "Johnny Paycheck",
    "Joseph Papp",
    "Joseph Pulitzer",
    "Juan Peron",
    "Juliet Prowse",
    "J.K. Rowling",
    "J.P. Big Bopper Richardson",
    "Jackie Robinson",
    "James Earl Ray",
    "James Randi",
    "Jan van Riebeeck",
    "Jane Russell",
    "Jason Robards",
    "Jean Reno",
    "Jeanne Robertson",
    "Jeannie C. Riley",
    "Jeri Ryan",
    "Jerome Robbins",
    "Jerry Rice",
    "Joan Rivers",
    "Joe E. Ross",
    "Joey Ramone",
    "John Ratzenberger",
    "John Ritter",
    "Johnnie Ray",
    "Jon Benet Ramsey",
    "Joyce Randolph",
    "Julia Roberts",
    "J.D. Salinger",
    "Jaclyn Smith",
    "Jacqueline Susann",
    "Jaden Smith",
    "James Spader",
    "Jamie Lynn Spears",
    "Jane Seymore",
    "Jane Seymour",
    "Jay Silverheels",
    "Jean Seberg",
    "Jean Sibelius",
    "Jean Simmons",
    "Jean Smart",
    "Jean Stapleton",
    "Jean-Paul Sartre",
    "Jeremy Sumpter",
    "Jerry Seinfeld",
    "Jerry Springer",
    "Jerry Stiller",
    "Jessica Simpson",
    "Jessica Steen",
    "Jimmy Smits",
    "Jimmy Stewart",
    "Jo Stafford",
    "Joan Sutherland",
    "John Cameron Swayze",
    "John Paul Stevens",
    "John Philip Sousa",
    "John Sandford",
    "John Sebastian",
    "John Singer Sargent",
    "John Singer-Sargent",
    "John Stamos",
    "John Steinbeck",
    "Jon Stewart",
    "Jonas Salk",
    "Jonathan Swift",
    "Joseph Stalin",
    "Joss Stone",
    "Jozef Sabovcik",
    "Judge Judy Sheindlin",
    "Judy Sheindlin",
    "Julia Stiles",
    "Junior Seau",
    "J.R.R. Tolkien",
    "Jacques Tati",
    "James Taylor",
    "James Thurber",
    "Jeff Timmons",
    "Jennifer Tilly",
    "Jessica Tandy",
    "Jim Thorpe",
    "John Tesh",
    "John Travolta",
    "John Turturro",
    "John Tyler",
    "Justin Timberlake",
    "Jacob Underwood",
    "Jay Underwood",
    "John Updike",
    "Johnny Unitas",
    "James Van-Der-Beek",
    "Jan Vermeer",
    "Jesse Ventura",
    "Jon Voight",
    "Jules Verne",
    "Jack Warden",
    "Jack Webb",
    "Jack Weston",
    "Jack White",
    "James Whitmore",
    "James Woods",
    "Jamie Walters",
    "Jane Wyatt",
    "Jane Wyman",
    "Jesse White",
    "Jimmie Walker",
    "Jimmy Wakely",
    "Jimmy Webb",
    "Jo Anne Worley",
    "Joanne Woodward",
    "Joe Williams",
    "John Walsh",
    "John Waters",
    "John Wayne",
    "John Williams",
    "John Wooden",
    "Johnny Winter",
    "Jonathan Winters",
    "Joseph Wambaugh",
    "Joseph Wapner",
    "Judge Joseph Wapner",
    "Jay Z",
    "Jiang Zemin",
    "Kajol",
    "Kane",
    "Kathie",
    "Kenneth",
    "Kareem Abdul-Jabbar",
    "Karen Allen",
    "Kim Alexis",
    "Kirstie Alley",
    "Kofi Annan",
    "Konrad Adenauer",
    "Kurt Angle",
    "Karen Black",
    "Kate Bush",
    "Kathryn Bigelow",
    "Kathy Bates",
    "Kaye Ballard",
    "Keefe Brasselle",
    "Ken Berry",
    "Kevin Bacon",
    "Kim Basinger",
    "Kobe Bryant",
    "Karen Carpenter",
    "Kate Capshaw",
    "Kathleen Casey",
    "Katie Couric",
    "Keith Carradine",
    "Kelly Clarkson",
    "Ken Curtis",
    "Kenny Chesney",
    "Kevin Cadogan",
    "Kevin Costner",
    "Kim Campbell",
    "Kim Carnes",
    "Kim Cattrall",
    "Kirk Cameron",
    "Kit Carson",
    "Kurt Cobain",
    "Kat Von D",
    "Keir Dullea",
    "Kirk Douglas",
    "Kirsten Dunst",
    "Kristin Davis",
    "Kim Elizabeth",
    "King Edward",
    "Ken Follett",
    "Kirk Franklin",
    "Kahlil Gibran",
    "Kate Gosselin",
    "Kathryn Grayson",
    "Kathy Griffin",
    "Kelsey Grammer",
    "Kenny G",
    "Kate Hudson",
    "Katharine Hepburn",
    "Katie Holmes",
    "Ken Howard",
    "King Henry",
    "Kitty Carlisle Hart",
    "Kyle Howard",
    "Kathy Ireland",
    "Kim Jong Il",
    "Kareem Abdul Jabbar",
    "Kate Jackson",
    "Kim Jong-Il",
    "Kala Sosefina Mileniume Kauvaka",
    "Keira Knightley",
    "Ken Kesey",
    "Kim Kardashian",
    "Kiri Te Kanawa",
    "Kourtney Kardashian",
    "Kurt Krakowian",
    "Keith Lockhart",
    "Kelly Lynch",
    "Kenny Loggins",
    "Karl Malden",
    "Karl Marx",
    "Karl Menninger",
    "Kate Middleton",
    "Kate Mulgrew",
    "Keith Moon",
    "Kel Mitchell",
    "Kelly McGillis",
    "Kent McCord",
    "Kristy McNichol",
    "Kim Novak",
    "Keke Palmer",
    "Kelly Preston",
    "Kenneth Patchen",
    "Keshia Knight Pulliam",
    "Kherington Payne",
    "Kirby Puckett",
    "Katharine Ross",
    "Keanu Reeves",
    "Keith Richards",
    "Ken Russell",
    "Kenny Rogers",
    "Keri Russell",
    "Kevin Richardson",
    "Kid Rock",
    "Knute Rockne",
    "Kurt Russell",
    "Kate Smith",
    "Katee Sackhoff",
    "Kay Starr",
    "Keely Smith",
    "Kenneth Starr",
    "Kerri Strug",
    "Kevin Spacey",
    "Kirsten Storms",
    "Kyra Sedgwick",
    "Kathleen Turner",
    "Koko Taylor",
    "Karl Urban",
    "Kat Von-D",
    "Kurt Vonnegut",
    "Kanye West",
    "Liberace",
    "Lorie",
    "Lou",
    "Lance Armstrong",
    "Laverne Andrews",
    "Lew Ayres",
    "Lily Allen",
    "Loni Anderson",
    "Louie Anderson",
    "Louis Armstrong",
    "Louisa May Alcott",
    "L.L. Bean",
    "Lady Baden-Powell",
    "Lance Bass",
    "Larry Bird",
    "Larry Byrd",
    "Laura W. Bush",
    "Lauren Bacall",
    "LeVar Burton",
    "Lenny Bruce",
    "Leo Buscaglia",
    "Leonard Bernstein",
    "Les Brown",
    "Lil Bow-Wow",
    "Linda Blair",
    "Lindsey Buckingham",
    "Lizzie Borden",
    "Lloyd Bridges",
    "Lord Baden-Powell",
    "Louis Braille",
    "Louis Brandeis",
    "Lucille Ball",
    "Ludwig van Beethoven",
    "Luis Bu�uel",
    "Luis Miguel Basteri",
    "Luther Burbank",
    "LL Cool-J",
    "Larry Buster Crabbe",
    "Larry the Cable-Guy",
    "Lauren Collins",
    "Lauren Conrad",
    "Le Corbusier",
    "Lee J. Cobb",
    "Leo G. Carroll",
    "Leonard Cohen",
    "Leslie Caron",
    "Lewis Carrol",
    "Lewis Carroll",
    "Lon Chaney",
    "Lou Costello",
    "Lynda Carter",
    "Lynne Cheney",
    "Landon Donovan",
    "Larry David",
    "Leonardo Da-Vinci",
    "Leonardo DiCaprio",
    "Leonardo da-Vinci",
    "Les Dawson",
    "Linda Ellerbee",
    "Lisa Edelstein",
    "Larry Fine",
    "Larry Flynt",
    "Laurence Fishburne",
    "Lil Fizz",
    "Lola Falana",
    "Lou Ferrigno",
    "Louis Farrakhan",
    "Louise Fletcher",
    "Lynn Fontanne",
    "Lady Gaga",
    "Larry the Cable Guy",
    "Lee Gifford",
    "Leo Gorcey",
    "Liam Gallagher",
    "Lillian Gish",
    "Linda Gray",
    "Lorne Greene",
    "Lou Gehrig",
    "Louis Gossett",
    "Lowell George",
    "L. Ron Hubbard",
    "Langston Hughes",
    "Larry Hagman",
    "Lauren Hutton",
    "Lena Horne",
    "Linda Hamilton",
    "Linda Hunt",
    "Lionel Hampton",
    "Lance Ito",
    "Lee Iacocca",
    "LL Cool J",
    "LaToya Jackson",
    "Lady Bird Johnson",
    "Lebron James",
    "Louis Jourdan",
    "Lyndon B. Johnson",
    "Larry King",
    "Laszlo Kovacs",
    "Lenny Kravitz",
    "Lawrence Leritz",
    "Lennox Lewis",
    "Leona Lewis",
    "Leslie Twiggy Lawson",
    "Linda Lavin",
    "Lindsay Lohan",
    "Lisa Ling",
    "Lois Lowry",
    "Loretta Lynn",
    "Lotte Lenya",
    "Louis LAmour",
    "Louis Leakey",
    "Louise Lasser",
    "Lucky Luciano",
    "Lucy Lawless",
    "Lucy Liu",
    "Lyle Lovett",
    "Lea Michele",
    "Lee Majors",
    "Lee Marvin",
    "Leonard Maltin",
    "Liliana Mumy",
    "Linda McCartney",
    "Liz McClarnon",
    "Liza Minnelli",
    "Lorin Maazel",
    "Lorne Michaels",
    "Louis Malle",
    "Laraine Newman",
    "Laura Nyro",
    "Leonard Nimoy",
    "Leonard Spock Nimoy",
    "Leslie Nielsen",
    "Liam Neeson",
    "Larisa Oleynik",
    "Laurence Olivier",
    "Lee Harvey Oswald",
    "Lena Olin",
    "Leontyne Price",
    "Les Paul",
    "Linus Pauling",
    "Liz Phair",
    "Louis Pasteur",
    "Louis Prima",
    "Luciano Pavarotti",
    "Lamont ShowBoat Robinson",
    "LeAnn Rimes",
    "Lee Remick",
    "Leon Russell",
    "Lil Romeo",
    "Linda Ronstadt",
    "Lionel Richie",
    "Little Richard",
    "Lou Reed",
    "Louis Rukeyser",
    "Luise Rainer",
    "Lynn Redgrave",
    "Lane Smith",
    "Larry Storch",
    "Laura Schlessinger",
    "Layne Staley",
    "Lea Salonga",
    "Lee Strasberg",
    "Leon Schotter",
    "Leon Spinks",
    "Leopold Stokowski",
    "Lesley Stahl",
    "Levi Strauss",
    "Lizabeth Scott",
    "Lord Snowdon",
    "Loretta Swit",
    "Lana Turner",
    "Lauren Tewes",
    "Lawrence Taylor",
    "Lea Thompson",
    "Lee Trevino",
    "Leo Tolstoy",
    "Leon Trotsky",
    "Lily Tomlin",
    "Linus Torvalds",
    "Liv Tyler",
    "Louis Comfort Tiffany",
    "Lowell Thomas",
    "Lucas Till",
    "Lyle Talbot",
    "Leslie Uggams",
    "Liv Ullmann",
    "Leonardo da Vinci",
    "Ludwig van-Beethoven",
    "Luther Vandross",
    "Laura Wilkinson",
    "Lawrence Welk",
    "LeAnn Womack",
    "Lech Walesa",
    "Lesley Ann Warren",
    "Lil Bow Wow",
    "Lindsay Wagner",
    "Loudon Wainwright",
    "Lucinda Williams",
    "Lyle Waggoner",
    "Loretta Young",
    "Macaulay",
    "Madonna",
    "Meatloaf",
    "Michael",
    "Michelangelo",
    "MoNique",
    "Moby",
    "Morrissey",
    "Mozart",
    "Madeleine Albright",
    "Mahmoud Ahmadinejad",
    "Marc Anthony",
    "Marcus Allen",
    "Marian Anderson",
    "Marie Antoinette",
    "Mario Andretti",
    "Mary Kay Ash",
    "Matthew Arnold",
    "Maxene Andrews",
    "Maya Angelou",
    "Mel Allen",
    "Mitch Albom",
    "Mohammad Ali",
    "Morey Amsterdam",
    "Muhammad Ali",
    "M�dchen Amick",
    "Maria Bello",
    "Marion Barry",
    "Marlon Brando",
    "Martin Balsam",
    "Martin Brodeur",
    "Martin Van Buren",
    "Marty Balin",
    "Mary J. Blige",
    "Mason Betha",
    "Matthew Broderick",
    "Mel Blanc",
    "Mel Brooks",
    "Melvin Belli",
    "Menachem Begin",
    "Meredith Baxter",
    "Michael Biehn",
    "Michael Bloomberg",
    "Michael Bolton",
    "Michael Burger",
    "Michelangelo Buonarroti",
    "Michelle Branch",
    "Mikhail Baryshnikov",
    "Milton Berle",
    "Monica Bellucci",
    "M C",
    "M. C.-Hammer",
    "Macdonald Carey",
    "Madame Curie",
    "Madeleine Carroll",
    "Marc Chagall",
    "Maria Callas",
    "Mariah Carey",
    "Mario Cuomo",
    "Mark Cuban",
    "Mark Undertaker Callaway",
    "Marva Collins",
    "Mary Cassatt",
    "Maurice Chevalier",
    "Merce Cunningham",
    "Michael Caine",
    "Michael Chang",
    "Michael Connelly",
    "Michael Crawford",
    "Michael Crichton",
    "Mike Connors",
    "Miley Cyrus",
    "Montgomery Clift",
    "Mac Davis",
    "Mamie Van Doren",
    "Marion Davies",
    "Marlene Dietrich",
    "Matt Damon",
    "Matt Dillon",
    "Michael Damian",
    "Michael Dell",
    "Michael Douglas",
    "Michael Dukakis",
    "Michael J. Dady",
    "Micky Dolenz",
    "Mike Dirnt",
    "Mike Ditka",
    "Mike Douglas",
    "Miles Davis",
    "Minnie Driver",
    "M.C. Escher",
    "Mama Cass Elliot",
    "Mary Baker Eddy",
    "Melissa Etheridge",
    "Missy Elliott",
    "Malcolm Forbes",
    "Margot Fonteyn",
    "Marty Feldman",
    "Mary Frann",
    "Matt Frewer",
    "Mel Ferrer",
    "Mia Farrow",
    "Michael Flatley",
    "Michael J. Fox",
    "Mick Fleetwood",
    "Mike Farrell",
    "Millard Fillmore",
    "Milos Forman",
    "Milton Friedman",
    "Morgan Freeman",
    "Mahatma Gandhi",
    "Mark Paul Gosselaar",
    "Marla Gibbs",
    "Martha Graham",
    "Marvin Gaye",
    "Matt Groening",
    "Maxim Gorky",
    "Megan Gale",
    "Mel Gibson",
    "Melanie Griffith",
    "Melinda Gates",
    "Merv Griffin",
    "Michael Gross",
    "Mickey Gilley",
    "Mikhail Gorbachev",
    "Mitzi Gaynor",
    "Muammar Gadhafi",
    "M. C. Hammer",
    "M.C. Hammer",
    "MC Hammer",
    "Margaret Hamilton",
    "Margaux Hemingway",
    "Mariel Hemingway",
    "Mariette Hartley",
    "Marilu Henner",
    "Mariska Hargitay",
    "Mark Hamill",
    "Mark Harmon",
    "Martina Hingis",
    "Marvin Hagler",
    "Marvin Hamlisch",
    "Mary Hopkin",
    "Mata Hari",
    "Matthew Henson",
    "Melissa Joan Hart",
    "Merle Haggard",
    "Mia Hamm",
    "Michael C. Hall",
    "Mickey Hart",
    "Milton Hershey",
    "Miss Frances Horwich",
    "Moe Howard",
    "Monty Hall",
    "Moss Hart",
    "Magic Johnson",
    "Mahalia Jackson",
    "Melissa Joan-Hart",
    "Michael J. Jordan",
    "Michael Jackson",
    "Michael Johnson",
    "Michael Jordan",
    "Mick Jagger",
    "Milla Jovovich",
    "Madeline Kahn",
    "Margot Kidder",
    "Martin Luther King",
    "Michael Keaton",
    "Mila Kunis",
    "Madeline LEngle",
    "Margaret Leighton",
    "Mario Lanza",
    "Mario Lemieux",
    "Mark Lester",
    "Martin Landau",
    "Martin Lawrence",
    "Martin Luther",
    "Mary Leakey",
    "Matt Lauer",
    "Maya Ying Lin",
    "Meadowlark Lemon",
    "Meat Loaf",
    "Meriwether Lewis",
    "Michael Landon",
    "Michael Learned",
    "Michael Lovesmith",
    "Michel Legrand",
    "Michele Lee",
    "Myrna Loy",
    "Malcolm McDowell",
    "Mandy Moore",
    "Marcel Marceau",
    "Margaret Mead",
    "Margaret Mitchell",
    "Maria Montessori",
    "Maria Muldaur",
    "Marilyn McCoo",
    "Marilyn Monroe",
    "Mark Martin",
    "Mark McGwire",
    "Marlee Matlin",
    "Marsha Mason",
    "Marshall McLuhan",
    "Martin Milner",
    "Martin Mull",
    "Martina McBride",
    "Mary Martin",
    "Mary Tyler Moore",
    "Matthew McConaughey",
    "Maureen McCormick",
    "Melina Mercouri",
    "Michael McDonald",
    "Michael Michele",
    "Michael Moore",
    "Michael Moorer",
    "Mickey Mantle",
    "Mike Mills",
    "Mike Modano",
    "Miriam Makeba",
    "Mitch Miller",
    "Mitch Mitchell",
    "Modest Mussorgsky",
    "Michael Nesmith",
    "Mike Nichols",
    "Margaret OBrien",
    "Marie Osmond",
    "Mary-Kate Olsen",
    "Maureen OHara",
    "Merlin Olsen",
    "Michelle Obama",
    "Mandy Patinkin",
    "Manny Pacquiao",
    "Mario Puzo",
    "Markie Post",
    "Mary Kay Place",
    "Mary Pickford",
    "Master P",
    "Matthew Perry",
    "Maury Povich",
    "Max Planck",
    "Maxfield Parrish",
    "Melvin Van Peebles",
    "Michael Phelps",
    "Michele Pfeiffer",
    "Michelle Pfeiffer",
    "Michelle Phillips",
    "Mike Piazza",
    "Minnie Pearl",
    "Marilyn Quayle",
    "Mark Russell",
    "Martha Raye",
    "Mary Lou Retton",
    "Maurice Ravel",
    "Meg Ryan",
    "Michael Richards",
    "Mickey Rooney",
    "Mickey Rourke",
    "Mr. Rogers",
    "M. Night Shyamalan",
    "Mack Sennett",
    "Maggie Smith",
    "Marc Summers",
    "Maria Sharapova",
    "Marilyn Vos Savant",
    "Mark Spitz",
    "Martha Stewart",
    "Martie Seidel",
    "Martin Scorsese",
    "Martin Sheen",
    "Martin Short",
    "Mary Queen of Scots",
    "Mary Wollstonecraft Shelley",
    "Maureen Stapleton",
    "Maurice Sendak",
    "Max Steiner",
    "Max Von Sydow",
    "McLean Stevenson",
    "Meryl Streep",
    "Michael Sheen",
    "Mickey Spillane",
    "Mike Schmidt",
    "Mike Shinoda",
    "Morley Safer",
    "Mort Sahl",
    "Mao Tse-tung",
    "Margaret Thatcher",
    "Maria Tallchief",
    "Marisa Tomei",
    "Mark Twain",
    "Marlo Thomas",
    "Mary Travers",
    "Meg Tilly",
    "Mel Tillis",
    "Mel Torme",
    "Meshach Taylor",
    "Michael Tucker",
    "Mike Tyson",
    "Mother Teresa",
    "Mr. T",
    "Muzaffer Tema",
    "Meredith Vieira",
    "Madame C.J. Walker",
    "Mae West",
    "Malcolm-Jamal Warner",
    "Marlon Wayans",
    "Max Weinberg",
    "Michael Waltrip",
    "Michael Warren",
    "Michelle Wright",
    "Mike Wallace",
    "Montel Williams",
    "Muddy Waters",
    "Malcolm X",
    "Marvin Yagoda",
    "Michael York",
    "Michelle Yeoh",
    "Madeline Zima",
    "Mark Zuckerberg",
    "Moon Unit Zappa",
    "Napolenon",
    "Napoleon",
    "Nostradamus",
    "Neil Armstrong",
    "Napolean Bonepart",
    "Napoleon Bonaparte",
    "Napoleon Bonepart",
    "Natasha Bedingfield",
    "Ned Beatty",
    "Nicholas Brendon",
    "Nicole Bass",
    "Nicole Bobek",
    "Niels Bohr",
    "Notorious BIG",
    "Nadia Comaneci",
    "Nat King Cole",
    "Natalie Cole",
    "Nathaniel Currier",
    "Nell Carter",
    "Neve Campbell",
    "Nick Carter",
    "Nick Cave",
    "Nicolas Cage",
    "Napolean Dynomite",
    "Neil Diamond",
    "Nelson Eddy",
    "Nick Van Excel",
    "Nicole Eggert",
    "Nora Ephron",
    "Nanette Fabray",
    "Nathan Bedford Forrest",
    "Nina Foch",
    "Nancy Grace",
    "Nancy Lee Grahn",
    "Newt Gingrich",
    "Noel Gallagher",
    "Nomar Garciapara",
    "Naseem Hamed",
    "Nathaniel Hawthorne",
    "Neil Harris",
    "Nick Hexum",
    "Norm Hitzges",
    "Naomi Judd",
    "Nick Jonas",
    "Norah Jones",
    "Norman Jewison",
    "Nastassia Kinski",
    "Nat King-Cole",
    "Nicole Kidman",
    "Nik Kershaw",
    "Nikita Khrushchev",
    "Nikos Kazantzakis",
    "Nancy Lopez",
    "Nick Lachey",
    "Norman Lear",
    "Nana Mouskouri",
    "Nancy McKeon",
    "Nelson Mandela",
    "Niccolo Machiavelli",
    "Nick Mason",
    "Nikki Taylor Melton",
    "Norm MacDonald",
    "Norm Macdonald",
    "Norman Mailer",
    "Nate Newton",
    "Nichelle Nichols",
    "Nick Nolte",
    "Natalie Portman",
    "Neal Peart",
    "Nelson Piquet",
    "Nancy Reagan",
    "Nelson Riddle",
    "Nipsey Russell",
    "Nolan Ryan",
    "Norman Rockwell",
    "Nancy Sinatra",
    "Neil Sedaka",
    "Neil Simon",
    "Nicolas Sarkozy",
    "Nigel Short",
    "Nina Simone",
    "Noel Paul Stookey",
    "Norman Schwarzkopf",
    "Niki Taylor",
    "Nikki Taylor",
    "Nikola Tesla",
    "Nick Van-Excel",
    "N.C. Wyeth",
    "Nancy Walker",
    "Nancy Wilson",
    "Natalie Wood",
    "Nicol Williamson",
    "Noah Webster",
    "Neil Young",
    "Odetta",
    "Orphan Annie",
    "Omar Bradley",
    "Orlando Bloom",
    "Orson Bean",
    "Osama Bin-Laden",
    "Osama bin-Laden",
    "Otto von Bismarck",
    "Oleg Cassini",
    "Oliver Cromwell",
    "Ornette Coleman",
    "Olivia DeHavilland",
    "Oscar DeLaHoya",
    "Oscar Delahoya",
    "Ossie Davis",
    "Omar Epps",
    "Oscar the Grouch",
    "O. Henry",
    "Oliver Hardy",
    "Olivia Hussey",
    "Oscar De La Hoya",
    "Oscar Hammerstein",
    "Owen Hart",
    "Obi-Wan Kenobi",
    "Olga Korbut",
    "Otto Klemperer",
    "Osama Bin Laden",
    "Osama bin Laden",
    "Oscar Levant",
    "Ogden Nash",
    "Oliver North",
    "Ozzie Nelson",
    "Ozzie Ozbourne",
    "Ozzy Osbourne",
    "Otto Preminger",
    "Otis Redding",
    "O.J. Simpson",
    "OJ Simpson",
    "Oliver Stone",
    "Omar Sharif",
    "Oscar Schindler",
    "Obi Wan-Kenobi",
    "Oprah Winfrey",
    "Orson Welles",
    "Orville Wright",
    "Oscar Wilde",
    "Oskar Werner",
    "Pele",
    "Perlman",
    "Phoenix",
    "Pink",
    "Plato",
    "Prince",
    "Pam Ayres",
    "Pamela Anderson",
    "Patricia Arquette",
    "Patty Andrews",
    "Paul Anka",
    "Paula Abdul",
    "Philip Ahn",
    "Philip Austin",
    "P.T. Barnum",
    "Pat Buchanan",
    "Pat Buttram",
    "Paul Bear Bryant",
    "Pavel Bure",
    "Pearl Bailey",
    "Pearl S. Buck",
    "Peter Benchley",
    "Peter Bergman",
    "Peter Bogdanovich",
    "Peter Boyle",
    "Pierce Brosnan",
    "Polly Bergen",
    "Pope Benedict",
    "Pat Carroll",
    "Patrick Carney",
    "Patsy Cline",
    "Paul Cezanne",
    "Peggy Cass",
    "Penelope Cruz",
    "Perry Como",
    "Peter Criss",
    "Peter Cushing",
    "Petula Clark",
    "Phil Collins",
    "Pierre Cardin",
    "Princess Caroline",
    "Pam Dawber",
    "Patrick Dempsey",
    "Patrick Duffy",
    "Paul Desmond",
    "Paula Deen",
    "Phil Donahue",
    "Phyllis Diller",
    "Placido Domingo",
    "Princess Diana",
    "Patrick Ewing",
    "Paul Erlich",
    "Phil Everly",
    "Prince Edward",
    "Paul Ford",
    "Peggy Fleming",
    "Peter Falk",
    "Peter Fonda",
    "Peter Frampton",
    "Paul Gauguin",
    "Peter Gallagher",
    "Peter Graves",
    "Phyllis George",
    "Paris Hilton",
    "Pat Harrington",
    "Patricia Heaton",
    "Patrick Henry",
    "Patty Hearst",
    "Paul Bono Hewson",
    "Paul Harvey",
    "Paul Henreid",
    "Paul Hogan",
    "Pee-Wee Herman",
    "Philip Seymour Hoffman",
    "Phil Ivey",
    "Peter Jennings",
    "Patsy Kensit",
    "Paul Kantner",
    "Pauline Kael",
    "Patti LaBelle",
    "Paul Lynde",
    "Peggy Lee",
    "Peggy Lipton",
    "Percival Lowell",
    "Peter Lorre",
    "Phil Lesh",
    "Phill Lewis",
    "Piper Laurie",
    "Pamela Mason",
    "Pamela Sue Martin",
    "Pat Morita",
    "Patrick McGoohan",
    "Paul Mazursky",
    "Paul McCartney",
    "Paul McCrane",
    "Paul Miles",
    "Penny Marshall",
    "Peter Marshall",
    "Peter Max",
    "Peyton Manning",
    "Phil Mahre",
    "Piers Morgan",
    "Piet Mondriaan",
    "Pablo Neruda",
    "Pat Nixon",
    "Patricia Neal",
    "Paul Newman",
    "Peter Nero",
    "Peter Noone",
    "Phyllis Newman",
    "Pat OBrien",
    "Peter OToole",
    "Pablo Picasso",
    "Pablo Piccaso",
    "Paloma Picasso",
    "Pat Paulsen",
    "Patti Page",
    "Paul Petersen",
    "Paula Prentiss",
    "Pauley Perrette",
    "Paulina Porizkova",
    "Phil Proctor",
    "Philippe Petit",
    "Pope John Paul",
    "Priscilla Presley",
    "Pat Riley",
    "Patrick Roy",
    "Paul Pee-wee Herman Reubens",
    "Paul Reiser",
    "Paul Revere",
    "Paul Robeson",
    "Paul Rudd",
    "Pernell Roberts",
    "Pete Rose",
    "Pete Rozelle",
    "Phil Rizzuto",
    "Phylicia Rashad",
    "Pat Sajak",
    "Pat Summeral",
    "Pat Summerall",
    "Patrick Stewart",
    "Patrick Stump",
    "Patrick Swayze",
    "Patti Smith",
    "Paul Scofield",
    "Paul Shaffer",
    "Paul Simon",
    "Paul Stanley",
    "Pauly Shore",
    "Percy Bysshe Shelley",
    "Pete Sampras",
    "Pete Seeger",
    "Peter Scolari",
    "Peter Sellers",
    "Phil Silvers",
    "Phil Spector",
    "Phoebe Snow",
    "Phyllis Schlafly",
    "Picabo Street",
    "Pierre Salinger",
    "Preston Sturges",
    "Princess Stephanie",
    "Pamela Tiffin",
    "Paul Taylor",
    "Paul Tibbets",
    "Pete Townshend",
    "Peter Tork",
    "Piotr Ilyich Tchaikovsky",
    "Peter Ustinov",
    "Paul Verhoeven",
    "Paul Williams",
    "Paul Winchell",
    "Paul Winfield",
    "Peta Wilson",
    "Prince William",
    "Peter Yarrow",
    "Pia Zadora",
    "Quintanilla",
    "Queen Elizabeth",
    "Queen Juliana",
    "Quincy Jones",
    "Queen Latifah",
    "Quentin Tarantino",
    "Rawls",
    "Rhea",
    "Richard",
    "Rihanna",
    "River",
    "Rock",
    "Rod",
    "Ronaldinho",
    "Roseanne",
    "RuPaul",
    "Ralph Abernathy",
    "Rene Auberjonois",
    "Roald Amundsen",
    "Robert Altman",
    "Roone Arledge",
    "Rosanna Arquette",
    "Roscoe Fatty Arbuckle",
    "Rowan Atkinson",
    "Roy Acuff",
    "Ralph Bellamy",
    "Ralph Bunche",
    "Ray Bolger",
    "Ray Bradbury",
    "Raymond Burr",
    "Raz B",
    "Red Barber",
    "Red Buttons",
    "Richard Benjamin",
    "Richard Burton",
    "Robby Benson",
    "Robert Benchley",
    "Robert Blake",
    "Robert Burns",
    "Roger Bannister",
    "Rona Barrett",
    "Roscoe Lee Browne",
    "Russell Baker",
    "Ruth Buzzi",
    "Ray Charles",
    "Raymond Chandler",
    "Rich Cronin",
    "Richard Carpenter",
    "Richard Crenna",
    "Rita Coolidge",
    "Rivers Cuomo",
    "Robbie Coltrane",
    "Robert Carlyle",
    "Robert Caro",
    "Robert Chapin",
    "Robert Conrad",
    "Robert Cray",
    "Robert Culp",
    "Robert Cummings",
    "Robert N. Cronk",
    "Rocky Colavito",
    "Roger Clemens",
    "Roger Corman",
    "Ronald Colman",
    "Rory Calhoun",
    "Rosalynn Carter",
    "Rosanne Cash",
    "Rosemary Clooney",
    "Roy Clark",
    "Russell Crowe",
    "Ray Davies",
    "Rene Descartes",
    "Richard Dawson",
    "Richard Dreyfuss",
    "Roald Dahl",
    "Rob Van Dam",
    "Robert De-Niro",
    "Robert Deniro",
    "Robert Downey",
    "Robert Duvall",
    "Roger Daltrey",
    "Ronnie James Dio",
    "Rosemary DeCamp",
    "Ruby Dee",
    "Ralph Edwards",
    "Ralph Ellison",
    "Ralph W. Emerson",
    "Richard Engel",
    "Robert Englund",
    "Robert Evans",
    "Roger Ebert",
    "Redd Foxx",
    "Reverend Jerry Falwell",
    "Rhonda Fleming",
    "Ric Flair",
    "Richard Fleischer",
    "Robert Frost",
    "Robert Fulton",
    "Roberta Flack",
    "Roger Federer",
    "Rollie Fingers",
    "Ron Foos",
    "Ray Goulding",
    "Ray Guy",
    "Richard Gephardt",
    "Richard Gere",
    "Robert Goulet",
    "Robert Guillaume",
    "Robin Gibb",
    "Robin Givens",
    "Ron Glass",
    "Rube Goldberg",
    "Rudi Gernreich",
    "Rudolph Giuliani",
    "Rupert Grint",
    "Ruth Gordon",
    "Rex Harrison",
    "Richard Harris",
    "Rita Hayworth",
    "Robert Heinlein",
    "Rock Hudson",
    "Rolf Harris",
    "Ron Howard",
    "Roy Horn",
    "Rutger Hauer",
    "Randy Johnson",
    "Raul Julia",
    "Reggie Jackson",
    "Richard Jaeckel",
    "Rick James",
    "Robert Downey Jr",
    "Robert Johnson",
    "R. Kelly",
    "Ray Kroc",
    "Robby Krieger",
    "Robert F. Kennedy",
    "Robert Klein",
    "Rose Kennedy",
    "Ruby Keeler",
    "Rudyard Kipling",
    "Ryan Key",
    "R.D. Laing",
    "Ralph Lauren",
    "Ramsey Lewis",
    "Ray Liotta",
    "Richard Leakey",
    "Richard Lewis",
    "Ricki Lake",
    "Rob Lowe",
    "Robe Lowe",
    "Robert E. Lee",
    "Robert Ludlum",
    "Robin Leach",
    "Roy Lichtenstein",
    "Ralph Macchio",
    "Randolph Mantooth",
    "Ray Manzarek",
    "Ray Milland",
    "Reba McEntire",
    "Rene Magritte",
    "Rey Mysterio",
    "Ricardo Montalban",
    "Richard Moll",
    "Rik Mayall",
    "Rita Moreno",
    "Rob Morrow",
    "Robert Merrill",
    "Robert Mitchum",
    "Robert Morley",
    "Robert Morse",
    "Robert Mugabe",
    "Rocky Marciano",
    "Roddy McDowall",
    "Roger Maris",
    "Roger Miller",
    "Roger Moore",
    "Roger Mudd",
    "Roland Hussey Macy",
    "Ron Moody",
    "Ronnie Milsap",
    "Rose Marie",
    "Rue McClanahan",
    "Rupert Murdoch",
    "Russell Means",
    "Ryan Merriman",
    "Ralph Nader",
    "Randy Newman",
    "Richard Nixon",
    "Rick Nelson",
    "Robert De Niro",
    "Rudolf Nureyev",
    "Ruud Van Nistelrooy",
    "Randy Orton",
    "Ronn Owens",
    "Rosie ODonnell",
    "Roy Orbison",
    "Ryan ONeal",
    "Ray Parker",
    "Ray Price",
    "Regis Philbin",
    "Richard Petty",
    "Richard Pryor",
    "Robert E. Peary",
    "Robert Palmer",
    "Robert Parrish",
    "Robert Plant",
    "Robert Powell",
    "Robert Preston",
    "Roman Polanski",
    "Ron Horshack Palillo",
    "Rosa Parks",
    "Rosie Perez",
    "Ross Perot",
    "Randy Quaid",
    "Robin Quivers",
    "Rachael Ray",
    "Rachel Ray",
    "Ralph Richardson",
    "Ray Romano",
    "Rene Russo",
    "Rex Reed",
    "Richard Rodgers",
    "Richard Roundtree",
    "Rick Rockwell",
    "Rick Rubin",
    "Rob Reiner",
    "Robert Redford",
    "Robert Reed",
    "Robert Ripley",
    "Rosalind Russell",
    "Roy Rogers",
    "R.L. Stine",
    "Rachel Stevens",
    "Ravi Shankar",
    "Richard Red Skelton",
    "Richard Simmons",
    "Rick Schroder",
    "Rick Springfield",
    "Riley Smith",
    "Ringo Starr",
    "Robert Shaw",
    "Robert Smith",
    "Robert Stack",
    "Rod Serling",
    "Rod Steiger",
    "Rod Stewart",
    "Roger Staubach",
    "Roy Scheider",
    "Ryan Seacrest",
    "Randy Travis",
    "Redi Tlhabi",
    "Richard Thomas",
    "Rip Torn",
    "Robby Takac",
    "Robert Toth",
    "Robin Trower",
    "Rod Taylor",
    "Roger Taylor",
    "Rozonda Chilli Thomas",
    "Russ Tamblyn",
    "Robert Urich",
    "Ritchie Valens",
    "Robert Vaughn",
    "Rudolph Valentino",
    "Rudy Vallee",
    "Rachel Weisz",
    "Rainn Wilson",
    "Raoul Wallenberg",
    "Raquel Welch",
    "Ray Walston",
    "Reese Witherspoon",
    "Richard Wagner",
    "Richard Widmark",
    "Richard Wright",
    "Rick Warren",
    "Rick Wright",
    "Robert Wadlow",
    "Robert Wagner",
    "Robin Williams",
    "Roger Waters",
    "Ron Wood",
    "Rumer Willis",
    "Russell Wong",
    "Ruth Westheimer",
    "Robert Young",
    "Robin Yount",
    "Renee Zellweger",
    "Rob Zombie",
    "Robert Zemeckis",
    "Sade",
    "Santa",
    "Santana",
    "Seal",
    "Selena",
    "Shaggy",
    "Shakira",
    "Sinbad",
    "Sisqo",
    "Slash",
    "Spiderman",
    "Superman",
    "Swain",
    "Sam Adams",
    "Sholem Aleichem",
    "Sparky Anderson",
    "Spiro Agnew",
    "Sri Aurobindo",
    "Steve Allen",
    "Steve Austin",
    "Stone Cold Steve Austin",
    "Susan Anton",
    "Susan B. Anthony",
    "Sabrina Bryan",
    "Samuel Barber",
    "Samuel Beckett",
    "Sandra Bernhard",
    "Sandra Bullock",
    "Sarah Bernhardt",
    "Saul Bellow",
    "Scott Bairstow",
    "Scott Bakula",
    "Shelley Berman",
    "Shirley Bassey",
    "Shirley Booth",
    "Shirley Temple Black",
    "Simon Bolivar",
    "Sir Francis Bacon",
    "Sonny Bono",
    "Sophia Bush",
    "Soulja Boy",
    "Spring Byington",
    "Steve Burns",
    "Steven Bochco",
    "Susan Boyle",
    "Suzy Bogguss",
    "Syd Barrett",
    "Sam Cooke",
    "Samuel Colt",
    "Santa Claus",
    "Sarah Chalke",
    "Scatman Crothers",
    "Sean Connery",
    "Shaun Cassidy",
    "Shemekia Copeland",
    "Sheryl Crow",
    "Sid Caesar",
    "Sidney Crosby",
    "Simon Cowell",
    "Solanus Casey",
    "Stephen Crane",
    "Steve Carell",
    "Steve Carlton",
    "Stockard Channing",
    "Stone Cold",
    "Stu Cook",
    "Salvador Dali",
    "Sam Donaldson",
    "Sammy Davis",
    "Sandra Day-OConnor",
    "Sandra Dee",
    "Sandy Dennis",
    "Sandy Duncan",
    "Shannen Doherty",
    "Shelley Duvall",
    "Snoop Dogg",
    "Susan Dey",
    "Sam Elliot",
    "Sam Elliott",
    "Samantha Eggar",
    "Sheena Easton",
    "Sheila E.",
    "Sir Edward Elgar",
    "Sally Field",
    "Shelley Fabares",
    "Sherilyn Fenn",
    "Siegfried Fischbacher",
    "Sigmund Freud",
    "Stacy Ferguson",
    "Stan Freberg",
    "Sarah Michelle Gellar",
    "Scott Glenn",
    "Seth Green",
    "Sharon Gless",
    "Shecky Greene",
    "Spalding Gray",
    "Steve Garvey",
    "Steve Guttenberg",
    "Steve Guttenburg",
    "Stewart Granger",
    "Summer Glau",
    "Saddam Hussein",
    "Salma Hayek",
    "Sam Harris",
    "Sammy Hagar",
    "Samuel Lightnin Hopkins",
    "Scott Hamilton",
    "Screamin' Jay Hawkins",
    "Sean Hannity",
    "Shemp Howard",
    "Sherlock Holmes",
    "Sherman Hemsley",
    "Sir Edmund Hillary",
    "Skitch Henderson",
    "Sonja Henie",
    "Stephen Harper",
    "Stephen Hawking",
    "Stephen Hendry",
    "Sterling Holloway",
    "Steve Hackett",
    "Susan Hayward",
    "Susanna Hoffs",
    "Steve Crocodile Hunter Irwin",
    "Steve Irwin",
    "Samuel L. Jackson",
    "Scarlett Johansson",
    "Scott Joplin",
    "Shawn Johnson",
    "Shirley Jackson",
    "Shirley Jones",
    "Spike Jones",
    "Stephan Jenkins",
    "Steve Jobs",
    "Steven Jobs",
    "Stonewall Jackson",
    "Susan Saint James",
    "Sally Kellerman",
    "Sam Kinison",
    "Sandy Koufax",
    "Stacy Keach",
    "Stan Kenton",
    "Stanley Kramer",
    "Stanley Kubrick",
    "Stanley Kunitz",
    "Stephen King",
    "Suge Knight",
    "Swoosie Kurtz",
    "Sam Levenson",
    "Shari Lewis",
    "Sheldon Leonard",
    "Shelley Long",
    "Shia LaBeouf",
    "Sidney Lumet",
    "Sinclair Lewis",
    "Sophia Loren",
    "Spike Lee",
    "Stan Laurel",
    "Steve Lawrence",
    "Steven Anthony Lawrence",
    "Sugar Ray Leonard",
    "Susan Lucci",
    "Sal Mineo",
    "Samuel Morse",
    "Sarah McLachlan",
    "Sarah Miles",
    "Senator Joseph McCarthy",
    "Sergio Mendes",
    "Shane MacGowan",
    "Shawn Michaels",
    "Sheila MacRae",
    "Shigeru Miyamoto",
    "Shirley MacLaine",
    "Sofia Milos",
    "Spider Man",
    "Stan Mikita",
    "Stan Musial",
    "Steve Mahre",
    "Steve Marriott",
    "Steve Martin",
    "Steve McQueen",
    "Stuart Mathis",
    "Sun Myung Moon",
    "Super Man",
    "Sir Isaac Newton",
    "Sister Nivedita",
    "Steve Nash",
    "Stevie Nicks",
    "Sandra Day OConnor",
    "Sandra Oh",
    "Seiji Ozawa",
    "Shaquille Oneil",
    "Sharon Osbourne",
    "Shuggie Otis",
    "Sir Laurence Olivier",
    "Suleman octuplets",
    "S.J. Perelman",
    "Sam Peckinpah",
    "Sarah Jessica Parker",
    "Sarah Palin",
    "Scottie Pippen",
    "Sean Penn",
    "Sergei Prokofiev",
    "Sidney Poitier",
    "Slim Pickens",
    "Spencer Pratt",
    "Stefanie Powers",
    "Steve Perry",
    "Susan Perabo",
    "Suzanne Pleshette",
    "Sally Jessy Raphael",
    "Sally Rand",
    "Salman Rushdie",
    "Sam Rodia",
    "Sergei Rachmaninoff",
    "Seth Rogen",
    "Sheriff John Rovick",
    "Sir Cliff Richard",
    "Smokey Robinson",
    "Sugar Ray Robinson",
    "Sam Shepard",
    "Sammy Sosa",
    "Schim Schimmel",
    "Sharon Stone",
    "Shawn Stockman",
    "Sheryl Swoopes",
    "Sidney Sheldon",
    "Simone Signoret",
    "Sissy Spacek",
    "Sly Stone",
    "Sonia Sotomayor",
    "Soupy Sales",
    "Stella Stevens",
    "Stephen Sondheim",
    "Stephen Stills",
    "Steven Seagal",
    "Steven Segal",
    "Steven Spielberg",
    "Steven Spielburg",
    "Sully Sullenberger",
    "Susan Sarandon",
    "Susan Sontag",
    "Susan Strasberg",
    "Suzanne Somers",
    "Shania Twain",
    "Shirley Temple",
    "Sophie Tucker",
    "Spencer Tracy",
    "Steven Tyler",
    "Strom Thurmond",
    "Susan Tedeschi",
    "Stu Unger",
    "Sarah Vaughan",
    "Sid Vicious",
    "Swami Vivekananda",
    "Sam Walton",
    "Sam Waterston",
    "Sam Worthington",
    "Serena Williams",
    "Shane West",
    "Shaun White",
    "Shawn Wayans",
    "Shelley Winters",
    "Sigourney Weaver",
    "Simon Wiesenthal",
    "Steve Winwood",
    "Steve Wozniak",
    "Steven Wright",
    "Stevie Wonder",
    "Steve Young",
    "Steve Yzerman",
    "Susannah York",
    "Timbaland",
    "Timothy",
    "Taro Aso",
    "Taylor Abrahamse",
    "Tim Allen",
    "Tom Arnold",
    "Tori Amos",
    "Tracy Austin",
    "Troy Aikman",
    "Tammy Faye Bakker",
    "Tempestt Bledsoe",
    "Teresa Brewer",
    "Terry Bradshaw",
    "Theodore Bikel",
    "Tim Burton",
    "Timothy Bottoms",
    "Tina Barrett",
    "Todd Bridges",
    "Tom Bergeron",
    "Tom Bosley",
    "Tom Brady",
    "Tom Brokaw",
    "Tony Bennett",
    "Tony Blair",
    "Tyra Banks",
    "Tyson Beckford",
    "Ted Cassidy",
    "Tia Carrere",
    "Tim Conway",
    "Tim Curry",
    "Tom Clancy",
    "Tom Courtenay",
    "Tom Cruise",
    "Tommy Chong",
    "Tony Curtis",
    "Truman Capote",
    "Ty Cobb",
    "Ted Danson",
    "Timothy Dalton",
    "Tom Dreesen",
    "Tommy Dorsey",
    "Tony Danza",
    "Tony Dow",
    "Troy Donahue",
    "Tyne Daly",
    "T.S. Eliot",
    "Thomas Edison",
    "Tom Ewell",
    "Tom Fogerty",
    "Tammy Grimes",
    "Teri Garr",
    "Thomas Gainsborough",
    "Tipper Gore",
    "Tony Gwynn",
    "Tracey Gold",
    "Tab Hunter",
    "Taylor Hicks",
    "Teri Hatcher",
    "Tippi Hedren",
    "Tom Hanks",
    "Tom Hulce",
    "Tom T. Hall",
    "Tony Hawk",
    "Tony Iommi",
    "Thomas Jefferson",
    "Thomas Stonewall Jackson",
    "Tom Jones",
    "Tommy Lee Jones",
    "Ted Knight",
    "Ted Koppel",
    "Thomas Kinkade",
    "Toby Keith",
    "Timothy Leary",
    "Tina Louise",
    "Tom Lester",
    "Tom Leykis",
    "Tommy Lasorda",
    "Tommy Lee",
    "Trini Lopez",
    "Ted Mack",
    "Teena Marie",
    "Thelonious Monk",
    "Thomas Mann",
    "Thomas Merton",
    "Thurgood Marshall",
    "Tim Matheson",
    "Tim McGraw",
    "Tino Martinez",
    "Tom Mix",
    "Toni Morrison",
    "Toshiro Mifune",
    "Tracy Morgan",
    "Tug McGraw",
    "Tony Orlando",
    "Teddy Pendergrass",
    "Tom Petty",
    "Tom Poston",
    "Tyler Perry",
    "Tyrone Power",
    "Tanya Roberts",
    "Tara Reid",
    "Tex Ritter",
    "The Rock",
    "Theodore Roosevelt",
    "Tim Reid",
    "Tim Rice",
    "Tim Robbins",
    "Tim Russert",
    "Todd Rundgren",
    "Tony Randall",
    "Tony Richardson",
    "Tony Robbins",
    "Tony Roberts",
    "Tony Romo",
    "Talia Shire",
    "Tavis Smiley",
    "Taylor Swift",
    "Telly Savalas",
    "Terrence Stamp",
    "Terry Southern",
    "Thomas Sowell",
    "Tilda Swinton",
    "Tom Scholz",
    "Tom Seaver",
    "Tom Selleck",
    "Tom Smothers",
    "Tom Snyder",
    "Tom Stoppard",
    "Tommy Shaw",
    "Tony Shalhoub",
    "Tony Soprano",
    "Tanya Tucker",
    "Ted Turner",
    "Teresa Teng",
    "Tiffani Amber Thiessen",
    "Tina Turner",
    "Tiny Tim",
    "Tom Thumb",
    "Tommy Tune",
    "Toni Tennille",
    "Travis Tritt",
    "Twyla Tharp",
    "Tracey Ullman",
    "Tammy Wynette",
    "Ted Williams",
    "Tiger Woods",
    "Tionne T-Boz Watkins",
    "Tom Waits",
    "Tom Watson",
    "Tom Welling",
    "Tuesday Weld",
    "Tina Yothers",
    "Trisha Yearwood",
    "Tay Zonday",
    "Undertaker",
    "Usher",
    "Ursula Andress",
    "Usain Bolt",
    "Ulysses S. Grant",
    "Ub Iwerks",
    "Upton Sinclair",
    "Uma Thurman",
    "Vera-Ellen",
    "Vanessa Amorosi",
    "Valerie Bertinelli",
    "Victor Borge",
    "Victoria Beckham",
    "Van Cliburn",
    "Vanessa Carlton",
    "Vikki Carr",
    "Vic Damone",
    "Vera Ellen",
    "Victor Fleming",
    "Vincente Fox",
    "Vince Gill",
    "Vincent Gallo",
    "Vincent Van Gogh",
    "Virgil Gus Grissom",
    "Vittorio Gassman",
    "Valerie Harper",
    "Veronica Hamel",
    "Victor Hugo",
    "Vladimir Horowitz",
    "Van Johnson",
    "Victoria Jackson",
    "Val Kilmer",
    "Veronica Lake",
    "Vicki Lawrence",
    "Vince Lombardi",
    "Vivien Leigh",
    "Van Morrison",
    "Vanessa Minnillo",
    "Vaughn Monroe",
    "Vera Miles",
    "Vic Morrow",
    "Victor Mature",
    "Viggo Mortensen",
    "Vince McMahon",
    "Vince Neil",
    "Vladimir Nabokov",
    "Valerie Perrine",
    "Van Dyke Parks",
    "Vincent Price",
    "Vanessa Redgrave",
    "Ving Rhames",
    "Vidal Sassoon",
    "Vijay Singh",
    "Vin Scully",
    "Verne Mini-Me Troyer",
    "Vic Tayback",
    "Vince Vaughn",
    "Vincent Van-Gogh",
    "Vivian Vance",
    "Vanessa Williams",
    "Vanna White",
    "Venus Williams",
    "Virginia Woolf",
    "Vince Young",
    "Will I Am",
    "Woody Allen",
    "Wally Bronner",
    "Walter Brennan",
    "Ward Bond",
    "Warren Beatty",
    "Warren Buffett",
    "Wernher Von Braun",
    "Wild Bill",
    "Wilford Brimley",
    "William Beaumont",
    "William Bendix",
    "William Burroughs",
    "William F. Buckley",
    "Wally Cox",
    "Walter Cronkite",
    "Will Clark",
    "William Buffalo Bill Cody",
    "William Casey",
    "William Clark",
    "William Conrad",
    "Wilt Chamberlain",
    "Winston Churchill",
    "W.E.B. DuBois",
    "Wade Dominguez",
    "Walt Disney",
    "William Daniels",
    "Willy DeVille",
    "Wyatt Earp",
    "W.C. Fields",
    "Will Ferrell",
    "William Faulkner",
    "William Frawley",
    "William Friedkin",
    "Wayne Gretzky",
    "Whoopi Goldberg",
    "William Gilbert",
    "William Goldman",
    "Woody Guthrie",
    "Warren G. Harding",
    "Whitney Houston",
    "Wild Bill Hickok",
    "William Hanna",
    "William Harvey",
    "William Holden",
    "William Hurt",
    "William S. Hart",
    "Woody Harrelson",
    "Washington Irving",
    "Will I-Am",
    "Waylon Jennings",
    "William James",
    "Wolfman Jack",
    "Wassily Kandinsky",
    "Walter Matthau",
    "Walter Mondale",
    "Warren Moon",
    "Wendy Moniz",
    "Willey Mays",
    "William H. Macy",
    "William McKinley",
    "Willie Mays",
    "Wink Martindale",
    "Wolfgang Amadeus Mozart",
    "Wayne Newton",
    "Willie Nelson",
    "Warren Oates",
    "William Penn",
    "Wilson Pickett",
    "Wolfgang Puck",
    "Wayne Rogers",
    "Will Rogers",
    "Willie P. Richardson",
    "Winona Ryder",
    "Wallace Shawn",
    "Wallis Simpson",
    "Wes Studi",
    "Wesley Snipes",
    "Will Smith",
    "Willard Scott",
    "William Safire",
    "William Saroyan",
    "William Schallert",
    "William Seward",
    "William Shakespear",
    "William Shakespeare",
    "William Shatner",
    "Willie Shoemaker",
    "Willie Stargell",
    "William H. Taft",
    "Wernher Von-Braun",
    "Walt Whitman",
    "Walter Ray Williams",
    "Walter Winchell",
    "Wilbur Wright",
    "William Wellman",
    "Woodrow Wilson",
    "Weird Al Yankovic",
    "Warren Zevon",
    "Xuxa",
    "Xavier Cugat",
    "X.J. Kennedy",
    "Xena Warrior Princess",
    "Xena Warrior-Princess",
    "Yanni",
    "Yasser Arafat",
    "Yasmine Bleeth",
    "Yogi Berra",
    "Yul Brynner",
    "Yvonne DeCarlo",
    "Yuri Gagarin",
    "Yves Saint Laurent",
    "Yehudi Menuhin",
    "Yves Montand",
    "Yvette Mimieux",
    "Yoko Ono",
    "Yakov Smirnoff",
    "Yma Sumac",
    "Y.A. Tittle",
    "Zorro",
    "Zach Braff",
    "Zelda Fitzgerald",
    "Zane Grey",
    "Zsa Zsa Gabor",
    "Z.Z. Hill",
    "Zeppo Marx",
    "Zero Mostel",
    "Zubin Mehta",
    "ZaSu Pitts",
    "Zachary Taylor",
];

const COMPANIES: &[&str] = &[
    "Openlane",
    "Yearin",
    "Goodsilron",
    "Condax",
    "Opentech",
    "Golddex",
    "year-job",
    "Isdom",
    "Gogozoom",
    "Y-corporation",
    "Nam-zim",
    "Donquadtech",
    "Warephase",
    "Donware",
    "Faxquote",
    "Sunnamplex",
    "Lexiqvolax",
    "Sumace",
    "Treequote",
    "Iselectrics",
    "Zencorporation",
    "Plusstrip",
    "dambase",
    "Toughzap",
    "Codehow",
    "Zotware",
    "Statholdings",
    "Conecom",
    "Zathunicon",
    "Labdrill",
    "Ron-tech",
    "Green-Plus",
    "Groovestreet",
    "Zoomit",
    "Bioplex",
    "Zumgoity",
    "Scotfind",
    "Dalttechnology",
    "Kinnamplus",
    "Konex",
    "Stanredtax",
    "Cancity",
    "Finhigh",
    "Kan-code",
    "Blackzim",
    "Dontechi",
    "Xx-zobam",
    "Fasehatice",
    "Hatfan",
    "Streethex",
    "Inity",
    "Konmatfix",
    "Bioholding",
    "Hottechi",
    "Ganjaflex",
    "Betatech",
    "Domzoom",
    "Ontomedia",
    "Newex",
    "Betasoloin",
    "Mathtouch",
    "Rantouch",
    "Silis",
    "Plussunin",
    "Plexzap",
    "Finjob",
    "Xx-holding",
    "Scottech",
    "Funholding",
    "Sonron",
    "Singletechno",
    "Rangreen",
    "J-Texon",
    "Rundofase",
    "Doncon",
];
