#!/usr/bin/env bash

# Copyright Materialize, Inc. and contributors. All rights reserved.
#
# Use of this software is governed by the Business Source License
# included in the LICENSE file at the root of this repository.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0.

set -euo pipefail

# ShellCheck cannot follow this path, as it is only valid inside the Docker
# container.
# shellcheck disable=SC1091
. /usr/local/share/shlib/shlib.bash

ci_init

while read -r binary package cwd; do
    # Run tests, generating a JSON event stream. The jq in the pipeline below
    # prefixes each event's name field, if present, with the package name, so
    # that we can distinguish tests with the same names in different packages.
    (cd "$cwd" && ci_try "/tests/$binary" -Z unstable-options --format json --report-time) \
        | jq -c --arg package "$package" 'if .name then .name = "\($package)::\(.name)" else . end' \
        | tee -a results.json
done < /tests/manifest

ci_status_report
