//! Static registry of Materialize SQL functions for LSP completion and hover.
//!
//! Hardcoded to avoid a dependency on mz-sql

/// The kind of a SQL function.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FunctionKind {
    /// A scalar function that returns a single value per input row.
    Scalar,
    /// An aggregate function that combines multiple rows into one result.
    Aggregate,
    /// A window function that computes values across related rows.
    Window,
    /// A table function that returns a set of rows.
    Table,
}

/// Metadata about a single SQL function.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FunctionInfo {
    /// The function name (lowercase), extracted from the signature.
    pub name: &'static str,
    /// The full function signature.
    pub signature: &'static str,
    /// A plain-text description with markdown markup stripped.
    pub description: &'static str,
    /// Whether this is a scalar, aggregate, window, or table function.
    pub kind: FunctionKind,
}

/// All documented Materialize SQL functions, sorted alphabetically by name.
pub static FUNCTIONS: &[FunctionInfo] = &[
    FunctionInfo {
        name: "abs",
        signature: "abs(x: N) -> N",
        description: "The absolute value of x.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "acos",
        signature: "acos(x: double precision) -> double precision",
        description: "The inverse cosine of x, result in radians.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "acosh",
        signature: "acosh(x: double precision) -> double precision",
        description: "The inverse hyperbolic cosine of x.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "age",
        signature: "age(timestamp, timestamp) -> interval",
        description: "Subtracts one timestamp from another, producing a \"symbolic\" result that uses years and months, rather than just days.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "array_agg",
        signature: "array_agg(x: T) -> T[]",
        description: "Aggregate values (including nulls) as an array",
        kind: FunctionKind::Aggregate,
    },
    FunctionInfo {
        name: "array_cat",
        signature: "array_cat(a1: arrayany, a2: arrayany) -> arrayany",
        description: "Concatenates a1 and a2.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "array_fill",
        signature: "array_fill(anyelement, int[], [, int[]]) -> anyarray",
        description: "Returns an array initialized with supplied value and dimensions, optionally with lower bounds other than 1.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "array_length",
        signature: "array_length(a: arrayany, dim: bigint) -> int",
        description: "Returns the length of the specified dimension of the array.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "array_position",
        signature: "array_position(haystack: anycompatiblearray, needle: anycompatible) -> int",
        description: "Returns the subscript of needle in haystack. Returns null if not found.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "array_position",
        signature: "array_position(haystack: anycompatiblearray, needle: anycompatible, skip: int) -> int",
        description: "Returns the subscript of needle in haystack, skipping the first skip elements. Returns null if not found.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "array_remove",
        signature: "array_remove(a: anyarray, e: anyelement) -> anyarray",
        description: "Returns the array a without any elements equal to the given value e. The array must be one-dimensional. Comparisons are done using IS NOT DISTINCT FROM semantics, so it is possible to remove NULLs.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "array_to_string",
        signature: "array_to_string(a: anyarray, sep: text [, ifnull: text]) -> text",
        description: "This function has the potential to produce very large strings and may cause queries to run out of memory or crash. Use with caution. Concatenates the elements of array together separated by sep. Null elements are omitted unless ifnull is non-null, in which case null elements are replaced with the value of ifnull.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "ascii",
        signature: "ascii(s: str) -> int",
        description: "The ASCII value of s's left-most character.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "asin",
        signature: "asin(x: double precision) -> double precision",
        description: "The inverse sine of x, result in radians.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "asinh",
        signature: "asinh(x: double precision) -> double precision",
        description: "The inverse hyperbolic sine of x.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "atan",
        signature: "atan(x: double precision) -> double precision",
        description: "The inverse tangent of x, result in radians.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "atanh",
        signature: "atanh(x: double precision) -> double precision",
        description: "The inverse hyperbolic tangent of x.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "aws_secret",
        signature: "aws_secret(secret_name: text) -> text",
        description: "Resolves a secret value from AWS Secrets Manager. Requires aws_profile to be set in project.toml. Used in CREATE SECRET statements.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "avg",
        signature: "avg(x: T) -> U",
        description: "Average of T's values. Returns numeric if x is int, double if x is real, else returns same type as x.",
        kind: FunctionKind::Aggregate,
    },
    FunctionInfo {
        name: "bit_count",
        signature: "bit_count(b: bytea) -> bigint",
        description: "Returns the number of bits set in the bit string (aka _popcount_).",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "bit_length",
        signature: "bit_length(b: bytea) -> int",
        description: "Number of bits in b.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "bit_length",
        signature: "bit_length(s: str) -> int",
        description: "Number of bits in s.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "bool_and",
        signature: "bool_and(x: T) -> T",
        description: "NULL if all values of x are NULL, otherwise true if all values of x are true, otherwise false.",
        kind: FunctionKind::Aggregate,
    },
    FunctionInfo {
        name: "bool_or",
        signature: "bool_or(x: T) -> T",
        description: "NULL if all values of x are NULL, otherwise true if any values of x are true, otherwise false.",
        kind: FunctionKind::Aggregate,
    },
    FunctionInfo {
        name: "btrim",
        signature: "btrim(s: str) -> str",
        description: "Trim all spaces from both sides of s.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "btrim",
        signature: "btrim(s: str, c: str) -> str",
        description: "Trim any character in c from both sides of s.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "cast",
        signature: "CAST (cast_expr) -> T",
        description: "Value as type T",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "cbrt",
        signature: "cbrt(x: double precision) -> double precision",
        description: "The cube root of x.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "ceil",
        signature: "ceil(x: N) -> double precision",
        description: "The smallest integer >= x.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "ceiling",
        signature: "ceiling(x: N) -> double precision",
        description: "Alias of ceil.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "char_length",
        signature: "char_length(s: str) -> int",
        description: "Number of code points in s.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "chr",
        signature: "chr(i: int) -> str",
        description: "Character with the given Unicode codepoint. Only supports codepoints that can be encoded in UTF-8. The NULL (0) character is not allowed.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "coalesce",
        signature: "coalesce(x: T...) -> T?",
        description: "First non-NULL arg, or NULL if all are NULL.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "col_description",
        signature: "col_description(oid: oid, column: int) -> text",
        description: "Returns the comment for a table column, which is specified by the oid of its table and its column number.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "concat",
        signature: "concat(f: any, r: any...) -> text",
        description: "Concatenates the text representation of non-NULL arguments. The maximum length of the result string is 100 MiB.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "concat_ws",
        signature: "concat_ws(sep: str, f: any, r: any...) -> text",
        description: "Concatenates the text representation of non-NULL arguments from f and r separated by sep. The maximum length of the result string is 100 MiB.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "constant_time_eq",
        signature: "constant_time_eq(a: bytea, b: bytea) -> bool",
        description: "Returns true if the arrays are identical, otherwise returns false. The implementation mitigates timing attacks by making a best-effort attempt to execute in constant time if the arrays have the same length, regardless of their contents.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "constant_time_eq",
        signature: "constant_time_eq(a: text, b: text) -> bool",
        description: "Returns true if the strings are identical, otherwise returns false. The implementation mitigates timing attacks by making a best-effort attempt to execute in constant time if the strings have the same length, regardless of their contents.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "convert_from",
        signature: "convert_from(b: bytea, src_encoding: text) -> text",
        description: "Convert data b from original encoding specified by src_encoding into text.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "cos",
        signature: "cos(x: double precision) -> double precision",
        description: "The cosine of x, with x in radians.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "cosh",
        signature: "cosh(x: double precision) -> double precision",
        description: "The hyperbolic cosine of x, with x as a hyperbolic angle.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "cot",
        signature: "cot(x: double precision) -> double precision",
        description: "The cotangent of x, with x in radians.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "count",
        signature: "count(x: T) -> bigint",
        description: "Number of non-NULL inputs.",
        kind: FunctionKind::Aggregate,
    },
    FunctionInfo {
        name: "crc32",
        signature: "crc32(data: bytea) -> uint32",
        description: "Computes the 32-bit cyclic redundancy check of the given bytea data using the IEEE 802.3 polynomial.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "crc32",
        signature: "crc32(data: text) -> uint32",
        description: "Computes the 32-bit cyclic redundancy check of the given text data using the IEEE 802.3 polynomial.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "csv_extract",
        signature: "csv_extract(num_csv_col: int, col_name: string) -> col1: string, ... coln: string",
        description: "Extracts separated values from a column containing a CSV file formatted as a string",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "current_catalog",
        signature: "current_catalog() -> text",
        description: "Alias for current_database.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "current_database",
        signature: "current_database() -> text",
        description: "Returns the name of the current database.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "current_role",
        signature: "current_role() -> text",
        description: "Alias for current_user.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "current_schema",
        signature: "current_schema() -> text",
        description: "Returns the name of the first non-implicit schema on the search path, or NULL if the search path is empty.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "current_schemas",
        signature: "current_schemas(include_implicit: bool) -> text[]",
        description: "Returns the names of the schemas on the search path. The include_implicit parameter controls whether implicit schemas like mz_catalog and pg_catalog are included in the output.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "current_setting",
        signature: "current_setting(setting_name: text[, missing_ok: bool]) -> text",
        description: "Returns the value of the named setting or error if it does not exist. If missing_ok is true, return NULL if it does not exist.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "current_timestamp",
        signature: "current_timestamp() -> timestamptz",
        description: "The timestamp with time zone representing when the query was executed.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "current_user",
        signature: "current_user() -> text",
        description: "Returns the name of the user who executed the containing query.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "date_bin",
        signature: "date_bin(stride: interval, source: timestamp, origin: timestamp) -> timestamp",
        description: "Align source with origin along stride",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "date_part",
        signature: "date_part(time_component: str, val: timestamp) -> float",
        description: "Specified time component from value",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "date_trunc",
        signature: "date_trunc(time_component: str, val: interval) -> interval",
        description: "Largest time_component <= val",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "date_trunc",
        signature: "date_trunc(time_component: str, val: timestamp) -> timestamp",
        description: "Largest time_component <= val",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "decode",
        signature: "decode(s: text, format: text) -> bytea",
        description: "Decode s using the specified textual representation. The maximum size of the result is 100 MiB.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "degrees",
        signature: "degrees(x: double precision) -> double precision",
        description: "Converts radians to degrees.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "dense_rank",
        signature: "dense_rank() -> int",
        description: "Returns the rank of the current row within its partition without gaps, counting from 1. Rows that compare equal will have the same rank.",
        kind: FunctionKind::Window,
    },
    FunctionInfo {
        name: "digest",
        signature: "digest(data: bytea, type: text) -> bytea",
        description: "Computes a binary hash of the given bytea data using the specified type algorithm. The supported hash algorithms are the same as for the text variant of this function.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "digest",
        signature: "digest(data: text, type: text) -> bytea",
        description: "Computes a binary hash of the given text data using the specified type algorithm. Supported hash algorithms are: md5, sha1, sha224, sha256, sha384, and sha512.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "encode",
        signature: "encode(b: bytea, format: text) -> text",
        description: "Encode b using the specified textual representation",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "env_var",
        signature: "env_var(variable_name: text) -> text",
        description: "Resolves a secret value from a process environment variable. Used in CREATE SECRET statements.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "exists",
        signature: "EXISTS(s: Query) -> bool",
        description: "true if s returns at least one row.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "exp",
        signature: "exp(x: N) -> double precision",
        description: "Exponential of x (e raised to the given power)",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "extract",
        signature: "EXTRACT(extract_expr) -> numeric",
        description: "Specified time component from value",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "first_value",
        signature: "first_value(value anycompatible) -> anyelement",
        description: "Returns value evaluated at the first row of the window frame. The default window frame is RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW. See also Idiomatic Materialize SQL: First value.",
        kind: FunctionKind::Window,
    },
    FunctionInfo {
        name: "floor",
        signature: "floor(x: N) -> double precision",
        description: "The largest integer <= x.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "format_type",
        signature: "format_type(oid: int, typemod: int) -> text",
        description: "Returns the canonical SQL name for the type specified by oid with typemod applied.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "generate_series",
        signature: "generate_series(start: int, stop: int) -> Col<int>",
        description: "Generate all integer values between start and stop, inclusive.",
        kind: FunctionKind::Table,
    },
    FunctionInfo {
        name: "generate_series",
        signature: "generate_series(start: int, stop: int, step: int) -> Col<int>",
        description: "Generate all integer values between start and stop, inclusive, incrementing by step each time.",
        kind: FunctionKind::Table,
    },
    FunctionInfo {
        name: "generate_series",
        signature: "generate_series(start: timestamp, stop: timestamp, step: interval) -> Col<timestamp>",
        description: "Generate all timestamp values between start and stop, inclusive, incrementing by step each time.",
        kind: FunctionKind::Table,
    },
    FunctionInfo {
        name: "generate_subscripts",
        signature: "generate_subscripts(a: anyarray, dim: int) -> Col<int>",
        description: "Generates a series comprising the valid subscripts of the dim'th dimension of the given array a.",
        kind: FunctionKind::Table,
    },
    FunctionInfo {
        name: "get_bit",
        signature: "get_bit(b: bytea, n: int) -> int",
        description: "Return the nth bit from b, where the left-most bit in b is at the 0th position.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "get_byte",
        signature: "get_byte(b: bytea, n: int) -> int",
        description: "Return the nth byte from b, where the left-most byte in b is at the 0th position.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "greatest",
        signature: "greatest(x: T...) -> T?",
        description: "The maximum argument, or NULL if all are NULL.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "has_cluster_privilege",
        signature: "has_cluster_privilege([role: text or oid,] cluster: text, privilege: text) -> bool",
        description: "Reports whether the role with the specified role name or OID has the privilege on the cluster with the specified cluster name. If the role is omitted then the current_role is assumed.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "has_connection_privilege",
        signature: "has_connection_privilege([role: text or oid,] connection: text or oid, privilege: text) -> bool",
        description: "Reports whether the role with the specified role name or OID has the privilege on the connection with the specified connection name or OID. If the role is omitted then the current_role is assumed.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "has_database_privilege",
        signature: "has_database_privilege([role: text or oid,] database: text or oid, privilege: text) -> bool",
        description: "Reports whether the role with the specified role name or OID has the privilege on the database with the specified database name or OID. If the role is omitted then the current_role is assumed.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "has_role",
        signature: "has_role([user: name or oid,] role: text or oid, privilege: text) -> bool",
        description: "Reports whether the user has the privilege for role. privilege can either be MEMBER or USAGE, however currently this value is ignored. The PUBLIC pseudo-role cannot be used for the user nor the role. If the user is omitted then the current_role is assumed.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "has_schema_privilege",
        signature: "has_schema_privilege([role: text or oid,] schema: text or oid, privilege: text) -> bool",
        description: "Reports whether the role with the specified role name or OID has the privilege on the schema with the specified schema name or OID. If the role is omitted then the current_role is assumed.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "has_secret_privilege",
        signature: "has_secret_privilege([role: text or oid,] secret: text or oid, privilege: text) -> bool",
        description: "Reports whether the role with the specified role name or OID has the privilege on the secret with the specified secret name or OID. If the role is omitted then the current_role is assumed.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "has_system_privilege",
        signature: "has_system_privilege([role: text or oid,] privilege: text) -> bool",
        description: "Reports whether the role with the specified role name or OID has the system privilege. If the role is omitted then the current_role is assumed.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "has_table_privilege",
        signature: "has_table_privilege([role: text or oid,] relation: text or oid, privilege: text) -> bool",
        description: "Reports whether the role with the specified role name or OID has the privilege on the relation with the specified relation name or OID. If the role is omitted then the current_role is assumed.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "has_type_privilege",
        signature: "has_type_privilege([role: text or oid,] type: text or oid, privilege: text) -> bool",
        description: "Reports whether the role with the specified role name or OID has the privilege on the type with the specified type name or OID. If the role is omitted then the current_role is assumed.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "hmac",
        signature: "hmac(data: bytea, key: bytea, type: text) -> bytea",
        description: "Computes a hashed MAC of the given bytea data using the specified key and type algorithm. The supported hash algorithms are the same as for digest.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "hmac",
        signature: "hmac(data: text, key: text, type: text) -> bytea",
        description: "Computes a hashed MAC of the given text data using the specified key and type algorithm. Supported hash algorithms are the same as for digest.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "initcap",
        signature: "initcap(a: text) -> text",
        description: "Returns a with the first character of every word in upper case and all other characters in lower case. Words are separated by non-alphanumeric characters.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "jsonb_agg",
        signature: "jsonb_agg(expression) -> jsonb",
        description: "Aggregate values (including nulls) as a jsonb array",
        kind: FunctionKind::Aggregate,
    },
    FunctionInfo {
        name: "jsonb_array_elements",
        signature: "jsonb_array_elements(j: jsonb) -> Col<jsonb>",
        description: "j's elements if j is an array",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "jsonb_array_elements_text",
        signature: "jsonb_array_elements_text(j: jsonb) -> Col<string>",
        description: "j's elements if j is an array",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "jsonb_array_length",
        signature: "jsonb_array_length(j: jsonb) -> int",
        description: "Number of elements in j's outermost array",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "jsonb_build_array",
        signature: "jsonb_build_array(x: ...) -> jsonb",
        description: "Output each element of x as a jsonb array. Elements can be of heterogenous types",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "jsonb_build_object",
        signature: "jsonb_build_object(x: ...) -> jsonb",
        description: "The elements of x as a jsonb object. The argument list alternates between keys and values",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "jsonb_each",
        signature: "jsonb_each(j: jsonb) -> Col<(key: string, value: jsonb)>",
        description: "j's outermost elements if j is an object",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "jsonb_each_text",
        signature: "jsonb_each_text(j: jsonb) -> Col<(key: string, value: string)>",
        description: "j's outermost elements if j is an object",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "jsonb_object_agg",
        signature: "jsonb_object_agg(keys, values) -> jsonb",
        description: "Aggregate keys and values (including nulls) as a jsonb object",
        kind: FunctionKind::Aggregate,
    },
    FunctionInfo {
        name: "jsonb_object_keys",
        signature: "jsonb_object_keys(j: jsonb) -> Col<string>",
        description: "j's outermost keys if j is an object",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "jsonb_pretty",
        signature: "jsonb_pretty(j: jsonb) -> string",
        description: "Pretty printed (i.e. indented) j",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "jsonb_strip_nulls",
        signature: "jsonb_strip_nulls(j: jsonb) -> jsonb",
        description: "j with all object fields with a value of null removed. Other null values remain",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "jsonb_typeof",
        signature: "jsonb_typeof(j: jsonb) -> string",
        description: "Type of j's outermost value. One of object, array, string, number, boolean, and null",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "justify_days",
        signature: "justify_days(val: interval) -> interval",
        description: "Adjust interval so 30-day time periods are represented as months",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "justify_hours",
        signature: "justify_hours(val: interval) -> interval",
        description: "Adjust interval so 24-hour time periods are represented as days",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "justify_interval",
        signature: "justify_interval(val: interval) -> interval",
        description: "Adjust interval using justify_days and justify_hours, with additional sign adjustments",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "kafka_murmur2",
        signature: "kafka_murmur2(data: bytea) -> integer",
        description: "Computes the Murmur2 hash of the given bytea data using the seed used by Kafka's default partitioner and with the high bit cleared.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "kafka_murmur2",
        signature: "kafka_murmur2(data: text) -> integer",
        description: "Computes the Murmur2 hash of the given text data using the seed used by Kafka's default partitioner and with the high bit cleared.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "lag",
        signature: "lag(value anycompatible [, offset integer [, default anycompatible ]]) -> int",
        description: "Returns value evaluated at the row that is offset rows before the current row within the partition; if there is no such row, instead returns default (which must be of a type compatible with value). If offset is NULL, NULL is returned instead. Both offset and default are evaluated with respect to the current row. If omitted, offset defaults to 1 and default to NULL. See also Idiomatic Materialize SQL: Lag over.",
        kind: FunctionKind::Window,
    },
    FunctionInfo {
        name: "last_value",
        signature: "last_value(value anycompatible) -> anyelement",
        description: "Returns value evaluated at the last row of the window frame. The default window frame is RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW. See also Idiomatic Materialize SQL: Last value.",
        kind: FunctionKind::Window,
    },
    FunctionInfo {
        name: "lead",
        signature: "lead(value anycompatible [, offset integer [, default anycompatible ]]) -> int",
        description: "Returns value evaluated at the row that is offset rows after the current row within the partition; if there is no such row, instead returns default (which must be of a type compatible with value). If offset is NULL, NULL is returned instead. Both offset and default are evaluated with respect to the current row. If omitted, offset defaults to 1 and default to NULL. See also Idiomatic Materialize SQL: Lead over.",
        kind: FunctionKind::Window,
    },
    FunctionInfo {
        name: "least",
        signature: "least(x: T...) -> T?",
        description: "The minimum argument, or NULL if all are NULL.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "left",
        signature: "left(s: str, n: int) -> str",
        description: "The first n characters of s. If n is negative, all but the last |n| characters of s.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "length",
        signature: "length(b: bytea) -> int",
        description: "Number of bytes in s.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "length",
        signature: "length(s: bytea, encoding_name: str) -> int",
        description: "Number of code points in s after encoding",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "length",
        signature: "length(s: str) -> int",
        description: "Number of code points in s.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "list_agg",
        signature: "list_agg(x: any) -> L",
        description: "Aggregate values (including nulls) as a list",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "list_append",
        signature: "list_append(l: listany, e: listelementany) -> L",
        description: "Appends e to l.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "list_cat",
        signature: "list_cat(l1: listany, l2: listany) -> L",
        description: "Concatenates l1 and l2.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "list_length",
        signature: "list_length(l: listany) -> int",
        description: "Return the number of elements in l.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "list_prepend",
        signature: "list_prepend(e: listelementany, l: listany) -> listany",
        description: "Prepends e to l.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "ln",
        signature: "ln(x: double precision) -> double precision",
        description: "Natural logarithm of x.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "ln",
        signature: "ln(x: numeric) -> numeric",
        description: "Natural logarithm of x.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "log",
        signature: "log(b: numeric, x: numeric) -> numeric",
        description: "Base b logarithm of x.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "log",
        signature: "log(x: double precision) -> double precision",
        description: "Base 10 logarithm of x.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "log",
        signature: "log(x: numeric) -> numeric",
        description: "Base 10 logarithm of x.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "log10",
        signature: "log10(x: double precision) -> double precision",
        description: "Base 10 logarithm of x, same as log.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "log10",
        signature: "log10(x: numeric) -> numeric",
        description: "Base 10 logarithm of x, same as log.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "lower",
        signature: "lower(s: str) -> str",
        description: "Convert s to lowercase.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "lpad",
        signature: "lpad(s: str, len: int) -> str",
        description: "Prepend s with spaces up to length len, or right truncate if len is less than the length of s. The maximum length of the result string is 100 MiB.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "lpad",
        signature: "lpad(s: str, len: int, p: str) -> str",
        description: "Prepend s with characters pulled from p up to length len, or right truncate if len is less than the length of s. The maximum length of the result string is 100 MiB.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "ltrim",
        signature: "ltrim(s: str) -> str",
        description: "Trim all spaces from the left side of s.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "ltrim",
        signature: "ltrim(s: str, c: str) -> str",
        description: "Trim any character in c from the left side of s.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "map_agg",
        signature: "map_agg(keys: text, values: T) -> map[text=>T]",
        description: "Aggregate keys and values (including nulls) as a map",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "map_build",
        signature: "map_build(kvs: list record(text, T)) -> map[text=>T]",
        description: "Builds a map from a list of records whose fields are two elements, the first of which is text. In the face of duplicate keys, map_build retains value from the record in the latest positition. This function is purpose-built to process Kafka headers.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "map_length",
        signature: "map_length(m: mapany) -> int",
        description: "Return the number of elements in m.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "max",
        signature: "max(x: T) -> T",
        description: "Maximum value among T.",
        kind: FunctionKind::Aggregate,
    },
    FunctionInfo {
        name: "md5",
        signature: "md5(data: bytea) -> text",
        description: "Computes the MD5 hash of the given bytea data. For PostgreSQL compatibility, returns a hex-encoded value of type text rather than bytea.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "min",
        signature: "min(x: T) -> T",
        description: "Minimum value among T.",
        kind: FunctionKind::Aggregate,
    },
    FunctionInfo {
        name: "mod",
        signature: "mod(x: N, y: N) -> N",
        description: "x % y",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "mz_environment_id",
        signature: "mz_environment_id() -> text",
        description: "Returns a string containing a uuid uniquely identifying the Materialize environment.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "mz_is_superuser",
        signature: "mz_is_superuser() -> bool",
        description: "Reports whether the current_role is a superuser.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "mz_now",
        signature: "mz_now() -> mz_timestamp",
        description: "The logical time at which a query executes. Used for temporal filters and query timestamp introspection",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "mz_row_size",
        signature: "mz_row_size(expr: Record) -> int",
        description: "Returns the number of bytes used to store a row.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "mz_uptime",
        signature: "mz_uptime() -> interval",
        description: "Returns the length of time that the materialized process has been running.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "mz_version",
        signature: "mz_version() -> text",
        description: "Returns the server's version information as a human-readable string.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "mz_version_num",
        signature: "mz_version_num() -> int",
        description: "Returns the server's version as an integer having the format XXYYYZZ, where XX is the major version, YYY is the minor version and ZZ is the patch version.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "normalize",
        signature: "normalize(s: str) -> str",
        description: "Normalize s to Unicode Normalization Form NFC (default).",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "normalize",
        signature: "normalize(s: str, form: keyword) -> str",
        description: "Normalize s to the specified Unicode normalization form (NFC, NFD, NFKC, or NFKD).",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "now",
        signature: "now() -> timestamptz",
        description: "The timestamp with time zone representing when the query was executed",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "nullif",
        signature: "nullif(x: T, y: T) -> T?",
        description: "NULL if x == y, else x.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "obj_description",
        signature: "obj_description(oid: oid, catalog: text) -> text",
        description: "Returns the comment for a database object specified by its oid and the name of the containing system catalog.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "octet_length",
        signature: "octet_length(b: bytea) -> int",
        description: "Number of bytes in b.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "octet_length",
        signature: "octet_length(s: str) -> int",
        description: "Number of bytes in s.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "parse_ident",
        signature: "parse_ident(ident: str[, strict_mode: bool]) -> str[]",
        description: "Given a qualified identifier like a.\"b\".c, splits into an array of the constituent identifiers with quoting removed and escape sequences decoded. Extra characters after the last identifier are ignored unless the strict_mode parameter is true (defaults to false).",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "pg_backend_pid",
        signature: "pg_backend_pid() -> int",
        description: "Returns the internal connection ID.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "pg_cancel_backend",
        signature: "pg_cancel_backend(connection_id: int) -> bool",
        description: "Cancels an in-progress query on the specified connection ID. Returns whether the connection ID existed (not if it cancelled a query).",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "pg_column_size",
        signature: "pg_column_size(expr: any) -> int",
        description: "Returns the number of bytes used to store any individual data value.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "pg_encoding_to_char",
        signature: "pg_encoding_to_char(encoding_id: integer) -> text",
        description: "PostgreSQL compatibility shim. Not intended for direct use.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "pg_function_is_visible",
        signature: "pg_function_is_visible(relation: oid) -> boolean",
        description: "Reports whether the function with the specified OID is visible in the search path.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "pg_get_constraintdef",
        signature: "pg_get_constraintdef(oid: oid[, pretty: bool]) -> text",
        description: "Returns the constraint definition for the given oid. Currently always returns NULL since constraints aren't supported.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "pg_get_indexdef",
        signature: "pg_get_indexdef(index: oid[, column: integer, pretty: bool]) -> text",
        description: "Reconstructs the creating command for an index. (This is a decompiled reconstruction, not the original text of the command.) If column is supplied and is not zero, only the definition of that column is reconstructed.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "pg_get_ruledef",
        signature: "pg_get_ruledef(rule_oid: oid[, pretty bool]) -> text",
        description: "Reconstructs the creating command for a rule. This function always returns NULL because Materialize does not support rules.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "pg_get_userbyid",
        signature: "pg_get_userbyid(role: oid) -> text",
        description: "Returns the role (user) name for the given oid. If no role matches the specified OID, the string unknown (OID=oid) is returned.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "pg_get_viewdef",
        signature: "pg_get_viewdef(view_name: text[, pretty: bool]) -> text",
        description: "Returns the underlying SELECT command for the given view.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "pg_get_viewdef",
        signature: "pg_get_viewdef(view_oid: oid[, pretty: bool]) -> text",
        description: "Returns the underlying SELECT command for the given view.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "pg_get_viewdef",
        signature: "pg_get_viewdef(view_oid: oid[, wrap_column: integer]) -> text",
        description: "Returns the underlying SELECT command for the given view.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "pg_has_role",
        signature: "pg_has_role([user: name or oid,] role: text or oid, privilege: text) -> bool",
        description: "Alias for has_role for PostgreSQL compatibility.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "pg_is_in_recovery",
        signature: "pg_is_in_recovery() -> bool",
        description: "Returns if the a recovery is still in progress.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "pg_postmaster_start_time",
        signature: "pg_postmaster_start_time() -> timestamptz",
        description: "Returns the time when the server started.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "pg_relation_size",
        signature: "pg_relation_size(relation: regclass[, fork: text]) -> bigint",
        description: "Disk space used by the specified fork ('main', 'fsm', 'vm', or 'init') of the specified table or index. If no fork is specified, it defaults to 'main'. This function always returns -1 because Materialize does not store tables and indexes on local disk.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "pg_size_pretty",
        signature: "pg_size_pretty(expr: numeric) -> text",
        description: "Converts a size in bytes into a human-readable format.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "pg_stat_get_numscans",
        signature: "pg_stat_get_numscans(oid: oid) -> bigint",
        description: "Number of sequential scans done when argument is a table, or number of index scans done when argument is an index. This function always returns -1 because Materialize does not collect statistics.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "pg_table_is_visible",
        signature: "pg_table_is_visible(relation: oid) -> boolean",
        description: "Reports whether the relation with the specified OID is visible in the search path.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "pg_tablespace_location",
        signature: "pg_tablespace_location(tablespace: oid) -> text",
        description: "Returns the path in the file system that the provided tablespace is on.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "pg_type_is_visible",
        signature: "pg_type_is_visible(relation: oid) -> boolean",
        description: "Reports whether the type with the specified OID is visible in the search path.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "pg_typeof",
        signature: "pg_typeof(expr: any) -> text",
        description: "Returns the type of its input argument as a string.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "position",
        signature: "position(sub: str IN s: str) -> int",
        description: "The starting index of sub within s or 0 if sub is not a substring of s.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "pow",
        signature: "pow(x: double precision, y: double precision) -> double precision",
        description: "Alias of power.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "pow",
        signature: "pow(x: numeric, y: numeric) -> numeric",
        description: "Alias of power.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "power",
        signature: "power(x: double precision, y: double precision) -> double precision",
        description: "x raised to the power of y.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "power",
        signature: "power(x: numeric, y: numeric) -> numeric",
        description: "x raised to the power of y.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "radians",
        signature: "radians(x: double precision) -> double precision",
        description: "Converts degrees to radians.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "rank",
        signature: "rank() -> int",
        description: "Returns the rank of the current row within its partition with gaps (counting from 1): rows that compare equal will have the same rank, and then the rank is incremented by the number of rows that compared equal.",
        kind: FunctionKind::Window,
    },
    FunctionInfo {
        name: "regexp_extract",
        signature: "regexp_extract(regex: str, haystack: str) -> Col<string>",
        description: "Values of the capture groups of regex as matched in haystack. Outputs each capture group in a separate column. At least one capture group is needed. (The capture groups are the parts of the regular expression between parentheses.)",
        kind: FunctionKind::Table,
    },
    FunctionInfo {
        name: "regexp_match",
        signature: "regexp_match(haystack: str, needle: str [, flags: str]]) -> str[]",
        description: "Matches the regular expression needle against haystack, returning a string array that contains the value of each capture group specified in needle, in order. If flags is set to the string i matches case-insensitively.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "regexp_matches",
        signature: "regexp_matches(haystack: str, needle: str [, flags: str]]) -> str[]",
        description: "Matches the regular expression needle against haystack, returning a string array that contains the value of each capture group specified in needle, in order. If flags is set to the string i matches case-insensitively. If flags is set to the string g all matches are returned, otherwise only the first match is returned. Without the g flag, the behavior is the same as regexp_match.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "regexp_replace",
        signature: "regexp_replace(source: str, pattern: str, replacement: str [, flags: str]]) -> str",
        description: "This function has the potential to produce very large strings and may cause queries to run out of memory or crash. Use with caution. Replaces the first occurrence of pattern with replacement in source. No match will return source unchanged. If flags is set to g, all occurrences are replaced. If flags is set to i, matches case-insensitively. $N or $name in replacement can be used to match capture groups. ${N} must be used to disambiguate capture group indexes from names if other characters follow N. A $$ in replacement will write a literal $. See the rust regex docs for more details about replacement.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "regexp_split_to_array",
        signature: "regexp_split_to_array(text: str, pattern: str [, flags: str]]) -> str[]",
        description: "Splits text by the regular expression pattern into an array. If flags is set to i, matches case-insensitively.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "regexp_split_to_table",
        signature: "regexp_split_to_table(text: str, pattern: str [, flags: str]]) -> Col<string>",
        description: "Splits text by the regular expression pattern. If flags is set to i, matches case-insensitively.",
        kind: FunctionKind::Table,
    },
    FunctionInfo {
        name: "repeat",
        signature: "repeat(s: str, n: int) -> str",
        description: "Replicate the string n times. The maximum length of the result string is 100 MiB.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "replace",
        signature: "replace(s: str, f: str, r: str) -> str",
        description: "s with all instances of f replaced with r. The maximum length of the result string is 100 MiB.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "reverse",
        signature: "reverse(s: str) -> str",
        description: "Reverse the characters in s.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "right",
        signature: "right(s: str, n: int) -> str",
        description: "The last n characters of s. If n is negative, all but the first |n| characters of s.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "round",
        signature: "round(x: N) -> double precision",
        description: "x rounded to the nearest whole number. If N is real or double precision, rounds ties to the nearest even number. If N is numeric, rounds ties away from zero.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "round",
        signature: "round(x: numeric, y: int) -> numeric",
        description: "x rounded to y decimal places, while retaining the same numeric scale; rounds ties away from zero.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "row_number",
        signature: "row_number() -> int",
        description: "Returns the number of the current row within its partition, counting from 1. Rows that compare equal will be ordered in an unspecified way. See also Idiomatic Materialize SQL: Top-K.",
        kind: FunctionKind::Window,
    },
    FunctionInfo {
        name: "rtrim",
        signature: "rtrim(s: str) -> str",
        description: "Trim all spaces from the right side of s.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "rtrim",
        signature: "rtrim(s: str, c: str) -> str",
        description: "Trim any character in c from the right side of s.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "seahash",
        signature: "seahash(data: bytea) -> u64",
        description: "Computes the SeaHash hash of the given bytea data.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "seahash",
        signature: "seahash(data: text) -> u64",
        description: "Computes the SeaHash hash of the given text data.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "session_user",
        signature: "session_user() -> text",
        description: "Returns the name of the user who initiated the database connection.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "sha224",
        signature: "sha224(data: bytea) -> bytea",
        description: "Computes the SHA-224 hash of the given bytea data.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "sha256",
        signature: "sha256(data: bytea) -> bytea",
        description: "Computes the SHA-256 hash of the given bytea data.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "sha384",
        signature: "sha384(data: bytea) -> bytea",
        description: "Computes the SHA-384 hash of the given bytea data.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "sha512",
        signature: "sha512(data: bytea) -> bytea",
        description: "Computes the SHA-512 hash of the given bytea data.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "sin",
        signature: "sin(x: double precision) -> double precision",
        description: "The sine of x, with x in radians.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "sinh",
        signature: "sinh(x: double precision) -> double precision",
        description: "The hyperbolic sine of x, with x as a hyperbolic angle.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "split_part",
        signature: "split_part(s: str, d: s, i: int) -> str",
        description: "Split s on delimiter d. Return the str at index i, counting from 1.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "sqrt",
        signature: "sqrt(x: double precision) -> double precision",
        description: "The square root of x.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "sqrt",
        signature: "sqrt(x: numeric) -> numeric",
        description: "The square root of x.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "starts_with",
        signature: "starts_with(s: str, prefix: str) -> bool",
        description: "Report whether s starts with prefix.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "stddev",
        signature: "stddev(x: T) -> U",
        description: "Historical alias for stddev_samp. (imprecise) Returns numeric if x is int, double if x is real, else returns same type as x.",
        kind: FunctionKind::Aggregate,
    },
    FunctionInfo {
        name: "stddev_pop",
        signature: "stddev_pop(x: T) -> U",
        description: "Population standard deviation of T's values. (imprecise) Returns numeric if x is int, double if x is real, else returns same type as x.",
        kind: FunctionKind::Aggregate,
    },
    FunctionInfo {
        name: "stddev_samp",
        signature: "stddev_samp(x: T) -> U",
        description: "Sample standard deviation of T's values. (imprecise) Returns numeric if x is int, double if x is real, else returns same type as x.",
        kind: FunctionKind::Aggregate,
    },
    FunctionInfo {
        name: "string_agg",
        signature: "string_agg(value: text, delimiter: text) -> text",
        description: "Concatenates the non-null input values into text. Each value after the first is preceded by the corresponding delimiter",
        kind: FunctionKind::Aggregate,
    },
    FunctionInfo {
        name: "string_to_array",
        signature: "string_to_array(s: str, delimiter: str [, null_string: str]) -> str[]",
        description: "Splits the string at occurrences of delimiter and returns a text array of the split segments. If delimiter is NULL, each character in the string will become a separate element in the array. If delimiter is an empty string, then the string is treated as a single field. If null_string is supplied and is not NULL, fields matching that string are replaced by NULL. For example: string_to_array('xx~~yy~~zz', '~~', 'yy') → {xx,NULL,zz}",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "substring",
        signature: "substring('s' [FROM 'start_pos']? [FOR 'l']?) -> str",
        description: "Substring starting at start_pos of length l",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "substring",
        signature: "substring(s: str, start_pos: int) -> str",
        description: "Substring of s starting at start_pos",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "substring",
        signature: "substring(s: str, start_pos: int, l: int) -> str",
        description: "Substring starting at start_pos of length l",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "sum",
        signature: "sum(x: T) -> U",
        description: "Sum of T's values Returns bigint if x is int or smallint, numeric if x is bigint or uint8, uint8 if x is uint4 or uint2, else returns same type as x.",
        kind: FunctionKind::Aggregate,
    },
    FunctionInfo {
        name: "tan",
        signature: "tan(x: double precision) -> double precision",
        description: "The tangent of x, with x in radians.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "tanh",
        signature: "tanh(x: double precision) -> double precision",
        description: "The hyperbolic tangent of x, with x as a hyperbolic angle.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "timezone",
        signature: "timezone(zone, timestamp) -> timestamptz",
        description: "Converts timestamp to specified time zone, expressed as an offset from UTC",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "timezone",
        signature: "timezone(zone, timestamptz) -> timestamp",
        description: "Converts timestamp with time zone from UTC to specified time zone, expressed as the local time",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "timezone_offset",
        signature: "timezone_offset(zone: str, when: timestamptz) -> (abbrev: str, base_utc_offset: interval, dst_offset: interval)",
        description: "Describes a time zone's offset from UTC at a specified moment. zone must be a valid IANA Time Zone Database identifier. when is a timestamp with time zone that specifies the moment at which to determine zone's offset from UTC. abbrev is the abbreviation for zone that is in use at the specified moment (e.g., EST or EDT). base_utc_offset is the base offset from UTC at the specified moment (e.g., -5 hours). Positive offsets mean east of Greenwich; negative offsets mean west of Greenwich. dst_offset is the additional offset at the specified moment due to Daylight Saving Time rules (e.g., 1 hours). If non-zero, Daylight Saving Time is in effect.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "to_char",
        signature: "to_char(val: timestamp, format: str)",
        description: "Converts a timestamp into a string using the specified format",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "to_jsonb",
        signature: "to_jsonb(v: T) -> jsonb",
        description: "v as jsonb",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "to_timestamp",
        signature: "to_timestamp(val: double precision) -> timestamptz",
        description: "Converts Unix epoch (seconds since 00:00:00 UTC on January 1, 1970) to timestamp.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "translate",
        signature: "translate(s: str, from: str, to: str) -> str",
        description: "Any character in s that matches a character in from is replaced by the corresponding character in to. If from is longer than to, occurrences of the extra characters in from are removed.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "trim",
        signature: "trim([BOTH | LEADING | TRAILING]? ['c'? FROM]? 's') -> str",
        description: "Trims any character in c from s on the specified side. Defaults: - Side: BOTH - 'c': ' ' (space)",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "trunc",
        signature: "trunc(x: N) -> double precision",
        description: "x truncated toward zero to a whole number.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "try_parse_monotonic_iso8601_timestamp",
        signature: "try_parse_monotonic_iso8601_timestamp(s: str) -> timestamp",
        description: "Parses a specific subset of ISO8601 timestamps, returning NULL instead of error on failure: YYYY-MM-DDThh:mm:ss.sssZ",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "unnest",
        signature: "unnest(a: anyarray)",
        description: "Expands the array a into a set of rows.",
        kind: FunctionKind::Table,
    },
    FunctionInfo {
        name: "unnest",
        signature: "unnest(l: anylist)",
        description: "Expands the list l into a set of rows.",
        kind: FunctionKind::Table,
    },
    FunctionInfo {
        name: "unnest",
        signature: "unnest(m: anymap)",
        description: "Expands the map m in a set of rows with the columns key and value.",
        kind: FunctionKind::Table,
    },
    FunctionInfo {
        name: "upper",
        signature: "upper(s: str) -> str",
        description: "Convert s to uppercase.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "user",
        signature: "user() -> text",
        description: "Alias for current_user.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "uuid_generate_v5",
        signature: "uuid_generate_v5(namespace: uuid, name: text) -> uuid",
        description: "Generates a version 5 UUID (SHA-1) in the given namespace using the specified input name.",
        kind: FunctionKind::Scalar,
    },
    FunctionInfo {
        name: "var_pop",
        signature: "var_pop(x: T) -> U",
        description: "Population variance of T's values. (imprecise) Returns numeric if x is int, double if x is real, else returns same type as x.",
        kind: FunctionKind::Aggregate,
    },
    FunctionInfo {
        name: "var_samp",
        signature: "var_samp(x: T) -> U",
        description: "Sample variance of T's values. (imprecise) Returns numeric if x is int, double if x is real, else returns same type as x.",
        kind: FunctionKind::Aggregate,
    },
    FunctionInfo {
        name: "variance",
        signature: "variance(x: T) -> U",
        description: "Historical alias for var_samp. (imprecise) Returns numeric if x is int, double if x is real, else returns same type as x.",
        kind: FunctionKind::Aggregate,
    },
    FunctionInfo {
        name: "version",
        signature: "version() -> text",
        description: "Returns a PostgreSQL-compatible version string.",
        kind: FunctionKind::Scalar,
    },
];

/// Look up a function by exact name (case-insensitive).
///
/// Returns the first matching entry. When multiple overloads exist for the
/// same function name, only the first (alphabetically by signature) is returned.
pub fn lookup(name: &str) -> Option<&'static FunctionInfo> {
    let name_lower = name.to_lowercase();
    FUNCTIONS.iter().find(|f| f.name == name_lower)
}

/// Return all functions whose name starts with the given prefix (case-insensitive).
pub fn search_prefix(prefix: &str) -> impl Iterator<Item = &'static FunctionInfo> {
    let prefix_lower = prefix.to_lowercase();
    FUNCTIONS.iter().filter(move |f| f.name.starts_with(&prefix_lower))
}
