# Copyright Materialize, Inc. and contributors. All rights reserved.
#
# Use of this software is governed by the Business Source License
# included in the LICENSE file.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0.

# Datadriven tests for the equality-saturation pass (`apply pipeline=eqsat`).
# The expected outputs are generated by `REWRITE=1 cargo test -p mz-transform
# --test test_transforms`.

# Source definitions
# ------------------

define
DefSource name=t0
  - c0: bigint
  - c1: bigint
----
Source defined as t0

# Case (a): nested filters fuse to one filter.
#
# The merge_filters rule rewrites `filter(p, filter(q, r))` into a single
# `filter(p && q, r)`, reducing the operator count. Predicates must be
# boolean-typed: coalesce_mfp calls Filter::action which calls
# canonicalize_predicates, asserting boolean types. Use integer comparisons
# (#0 = 1), (#1 = 1) which are boolean and not reducible to constants since
# #0 and #1 are column references whose runtime values are unknown.
apply pipeline=eqsat
Filter (#0 = 1)
  Filter (#1 = 1)
    Get t0
----
Filter (#0 = 1) AND (#1 = 1)
  Get t0

# Case (a2): SP4d soundness regression — nested IDENTICAL filters.
#
# `Filter[#0=1](Filter[#0=1](Get))`: `merge_filters` fuses the two into the
# sibling `Filter[#0=1, #0=1](Get)`, which shares one e-class with the original
# `Filter[#0=1](Filter[#0=1](Get))`. The inner filter proves `#0=1`, so under
# the inner context the outer predicate folds to `true`. The colored scalar
# resolution must apply that fold ONLY to the node whose INPUT proves `#0=1`
# (the redundant outer filter), NEVER to the fused sibling whose input is the
# bare `Get` (which proves nothing). Before the SP4d input-context fix this
# produced `Filter[1=1, 1=1](Get)` — a tautology filter that returns ALL rows
# instead of the `#0=1` rows. The sound result still filters `#0 = 1`.
apply pipeline=eqsat
Filter (#0 = 1)
  Filter (#0 = 1)
    Get t0
----
Filter (#0 = 1)
  Get t0

# Case (a3): a single filter is unaffected (sound baseline).
apply pipeline=eqsat
Filter (#0 = 1)
  Get t0
----
Filter (#0 = 1)
  Get t0

# Case (b): filter distributes over a union, then inner filters fuse.
#
# `distribute_filter_union_nary` pushes the outer filter into each branch;
# `merge_filters` then fuses it with the per-branch filters. Boolean predicates
# required (see case (a) comment).
apply pipeline=eqsat
Filter (#0 = 1)
  Union
    Filter (#1 = 1)
      Get t0
    Filter (#1 = 1)
      Get t0
----
With
  cte l1 =
    Filter (#0 = 1) AND (#1 = 1)
      Get t0
Return
  Union
    Get l1
    Get l1

# Case (c): unsupported node (Reduce) under a Filter is preserved verbatim.
#
# The egraph pass bails out at unsupported variants, so the Reduce is returned
# intact and only the supported outer Filter envelope may be rewritten. Boolean
# predicate required (see case (a) comment).
apply pipeline=eqsat
Filter (#0 = 1)
  Reduce group_by=[#0] aggregates=[]
    Get t0
----
Filter (#0 = 1)
  Distinct project=[#0]
    Project (#0)
      Get t0

# Case (d): filter with a literal-false predicate rewrites to an empty constant.
#
# `empty_false_filter` fires (`Filter[false] r => Empty(r)`), and extraction
# picks the cheaper Constant. Raise must produce an empty collection of arity 2,
# not panic.
apply pipeline=eqsat
Filter (false)
  Get t0
----
Constant <empty>

# Case (e): a constant Map scalar is folded at lower time.
#
# `reduced_escalar` runs `MirScalarExpr::reduce` on the payload, so `1 + 1`
# is stored (and raised) as the literal `2`.
apply pipeline=eqsat
Map (1 + 1)
  Get t0
----
Map (2)
  Get t0

# Case (g): contradictory equivalences collapse to empty.
#
# The filter has two predicates #0 = 1 and #0 = 2. The equivalences analysis
# places them in one class [#0 = 1, #0 = 2, true], which after minimize
# yields class [#0, 1, 2]: two distinct literals forced equal, unsatisfiable.
# The colored empty-fold rewrites any such relation to Empty (colored_derive
# marks the class empty; color-aware extraction emits an empty Constant).
apply pipeline=eqsat
Filter ((#0 = 1) AND (#0 = 2))
  Get t0
----
Constant <empty>

# Case (h): equality predicate canonicalized by join equivalences, but retained.
#
# The inner join forces #0 = #2. The canonicalization step rewrites #2 to #0
# (canonical representative) in the FILTER predicate, turning #0 = #2 into
# #0 = #0. The join's own equivalence [#0, #2] is NOT rewritten: applying the
# join's output reducer back to the join's own conditions is circular and unsound
# (it would turn an equijoin into a weaker join, producing extra rows). The
# filter #0 = #0 is pushed into the first join input by push_filter_into_join_first.
# The filter is NOT dropped: dropping Filter[#a=#b] when the input's equivalences
# prove #a=#b is unsound for null-preserving sources (the equivalences analysis
# has no nullability facts), so that step is deferred to the typed/physical phase.
define
DefSource name=t1
  - c0: bigint
  - c1: bigint
----
Source defined as t1

apply pipeline=eqsat
Filter (#0 = #2)
  Join on=(#0 = #2)
    Get t0
    Get t1
----
Project (#0, #1, #0, #3)
  Filter (#0 = #0)
    Join on=(#0 = #2)
      Get t0
      Get t1

# Case (f): equivalence-canonical scalar rewriting.
#
# The Filter establishes #0 = #1. The Map computes #1 + 1 over that input.
# The equivalences analysis for the Map's e-class knows:
#   - #0 = #1 (from the filter below it),
#   - col2 = #0 + 1 (= #1 + 1, the Map's own new column).
#
# The Map scalar #1 + 1 is rewritten to #0 + 1. The outermost-first reducer first
# tries the composite whole-expression entry #1+1 → col2=#2, but the per-step
# max_col guard rejects it (#2 is the Map's own output column, a forward
# self-reference, out of range for max_col=2). It then applies the child rewrite
# #1 → #0 (in range), yielding #0 + 1. This rewrite is correct because the
# #0 = #1 fact comes from the Map's input chain, not from the Map's own scalars.
#
# The filter predicate #0 = #1 is NOT rewritten. The Filter's own equivalences
# include the fact `#0 = #1` derived from the predicate itself, which would map
# #1 → #0 and rewrite the predicate to #0 = #0 (trivially true, causing the filter
# to be dropped). Using only the input's (Get t0's) reducer avoids this circular
# rewrite. Get t0 has no non-trivial equivalences, so the predicate stays as #0 = #1.
apply pipeline=eqsat
Map (#1 + 1)
  Filter (#0 = #1)
    Get t0
----
Filter (#0 = #1)
  Map ((#0 + 1))
    Get t0

# Case (i): coalesce_mfp end-to-end witness.
#
# The outer Filter references the Map-added column (#2), so
# push_filter_through_map cannot sink it past the Map. The eqsat rules leave
# the plan as Filter / Map / Filter / Get (three MFP operators in non-canonical
# order). coalesce_mfp extracts the maximal MFP run, optimizes it, and
# re-emits it in canonical Map-then-Filter-then-Project form via
# CanonicalizeMfp::rebuild_mfp. The two separate Filter layers are merged into
# one, demonstrating that coalescing actually fires.
apply pipeline=eqsat
Filter (#2 = 0)
  Map (#0 + 1)
    Filter (#0 = #1)
      Get t0
----
Filter (#2 = 0) AND (#0 = #1)
  Map ((#0 + 1))
    Get t0

# Case (j): CSE witness: a shared filtered subterm is bound once via Let.
#
# The Union of two identical Filter(Get t0) branches has a shared subterm.
# CSE extracts it into a Let binding with two LocalGet references, so the
# filter is computed once rather than duplicated in the raised plan.
apply pipeline=eqsat
Union
  Filter (#0 = 1)
    Get t0
  Filter (#0 = 1)
    Get t0
----
With
  cte l1 =
    Filter (#0 = 1)
      Get t0
Return
  Union
    Get l1
    Get l1
