{
 "title": "pgwire protocol latencies",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "command",
    "query": "label_values(mz_command_durations_bucket, command)"
   },
   {
    "name": "command_right",
    "label": "command (right)",
    "query": "label_values(mz_command_durations_bucket, command)"
   }
  ]
 },
 "panels": [
  { "title": "For command $command", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$command heatmap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(mz_command_durations_bucket{command=\"$command\"}[30s])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "$command_right heatmap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(mz_command_durations_bucket{command=\"$command_right\"}[30s])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "$command quantiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(mz_command_durations_bucket{command=\"$command\"}[30s])) by (le))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(mz_command_durations_bucket{command=\"$command\"}[30s])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(mz_command_durations_bucket{command=\"$command\"}[30s])) by (le))",
     "legendFormat": "median"
    },
    {
     "expr": "histogram_quantile(0.001, sum(rate(mz_command_durations_bucket{command=\"$command\"}[30s])) by (le))",
     "legendFormat": "p001"
    }
   ]
  },
  {
   "title": "$command_right quantiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(mz_command_durations_bucket{command=\"$command_right\"}[30s])) by (le))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(mz_command_durations_bucket{command=\"$command_right\"}[30s])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(mz_command_durations_bucket{command=\"$command_right\"}[30s])) by (le))",
     "legendFormat": "median"
    },
    {
     "expr": "histogram_quantile(0.001, sum(rate(mz_command_durations_bucket{command=\"$command_right\"}[30s])) by (le))",
     "legendFormat": "p001"
    }
   ]
  },
  {
   "title": "$command s per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mz_command_durations_count{command=\"$command\"}[30s]))",
     "legendFormat": "qps"
    }
   ]
  },
  {
   "title": "$command_right s per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mz_command_durations_count{command=\"$command_right\"}[30s]))",
     "legendFormat": "qps"
    }
   ]
  }
 ]
}