// Copyright Materialize, Inc. and contributors. All rights reserved.
//
// Use of this software is governed by the Business Source License
// included in the LICENSE file.
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0.

//! Wasmtime engine lifecycle, module compilation, and instance creation.
//!
//! Wraps the `wasmtime` crate to compile WASM bytecode generated by [`crate::codegen`]
//! and execute it on columnar data.

use mz_expr::MirScalarExpr;
use mz_repr::SqlScalarType;

use crate::codegen::{self, WasmLayout};
use crate::columnar::{ColumnBatch, ResultColumn, TypedColumn};

/// Shared WASM compilation engine. Reuse across multiple compiled expressions
/// to amortize engine initialization cost.
pub struct ExprEngine {
    engine: wasmtime::Engine,
}

/// A compiled WASM module ready to evaluate an expression on columnar data.
pub struct CompiledExpr {
    module: wasmtime::Module,
    layout: WasmLayout,
    /// The scalar type of the output column.
    output_type: SqlScalarType,
    /// The input column indices this expression reads from,
    /// in the order expected by the WASM function parameters.
    input_columns: Vec<usize>,
}

impl ExprEngine {
    /// Creates a new WASM engine with default settings.
    pub fn new() -> Result<Self, wasmtime::Error> {
        let engine = wasmtime::Engine::default();
        Ok(ExprEngine { engine })
    }

    /// Attempts to compile the given expression into a WASM module.
    ///
    /// Returns `None` if the expression is not compilable (uses unsupported operations).
    /// Returns `Err` if WASM compilation fails (internal error).
    pub fn compile(
        &self,
        expr: &MirScalarExpr,
        input_types: &[(SqlScalarType, bool)],
    ) -> Result<Option<CompiledExpr>, wasmtime::Error> {
        let scalar_types: Vec<SqlScalarType> =
            input_types.iter().map(|(st, _)| st.clone()).collect();

        let (wasm_bytes, layout) = match codegen::generate_wasm(expr, &scalar_types) {
            Some(result) => result,
            None => return Ok(None),
        };

        let module = wasmtime::Module::new(&self.engine, &wasm_bytes)?;

        let input_columns = crate::analyze::referenced_columns(expr);

        let output_type =
            crate::analyze::infer_type(expr, &scalar_types).unwrap_or(SqlScalarType::Int64);

        Ok(Some(CompiledExpr {
            module,
            layout,
            output_type,
            input_columns,
        }))
    }
}

impl CompiledExpr {
    /// Returns a reference to the compiled WASM module.
    pub fn module(&self) -> &wasmtime::Module {
        &self.module
    }

    /// Returns the memory layout metadata.
    pub fn layout(&self) -> &WasmLayout {
        &self.layout
    }

    /// Returns the input column indices this expression reads, in parameter order.
    pub fn input_columns(&self) -> &[usize] {
        &self.input_columns
    }

    /// Returns the output scalar type of this compiled expression.
    pub fn output_type(&self) -> &SqlScalarType {
        &self.output_type
    }

    /// Evaluates the compiled expression on the given column batch.
    ///
    /// The batch must contain columns at the indices referenced by the expression.
    /// Returns a [`ResultColumn`] with the computed output values, validity, and error flags.
    pub fn evaluate(&self, batch: &ColumnBatch) -> Result<ResultColumn, wasmtime::Error> {
        let num_rows = batch.num_rows;
        if num_rows == 0 {
            return Ok(ResultColumn::new(TypedColumn::new_for_type(
                &self.output_type,
                0,
            )));
        }

        let mut store = wasmtime::Store::new(self.module.engine(), ());

        // Calculate memory needed:
        // Per input column: num_rows * 8 (values) + num_rows (validity)
        // Output: num_rows * 8 (values) + num_rows (validity) + num_rows (errors)
        let per_col_bytes = num_rows * 8 + num_rows;
        let output_bytes = num_rows * 8 + num_rows + num_rows;
        let total_bytes = self.layout.num_input_cols * per_col_bytes + output_bytes;
        let num_pages = (total_bytes + 65535) / 65536; // Round up to WASM pages (64KB each)

        let memory_type = wasmtime::MemoryType::new(u32::try_from(num_pages).unwrap_or(1), None);
        let memory = wasmtime::Memory::new(&mut store, memory_type)?;

        // Lay out data in linear memory.
        // Layout: [col0_values][col0_validity][col1_values][col1_validity]...[out_values][out_validity][errors]
        let mut offset: usize = 0;
        let mut param_values: Vec<wasmtime::Val> = Vec::new();

        // First param: num_rows.
        #[allow(clippy::as_conversions)]
        param_values.push(wasmtime::Val::I32(num_rows as i32));

        // Copy input columns into WASM memory.
        for &col_idx in &self.input_columns {
            let col = &batch.columns[col_idx];
            let values_ptr = offset;

            // Write values.
            match col {
                TypedColumn::Int64 { values, .. } => {
                    let mem_data = memory.data_mut(&mut store);
                    for (i, &v) in values.iter().enumerate() {
                        let bytes = v.to_le_bytes();
                        let dst = values_ptr + i * 8;
                        mem_data[dst..dst + 8].copy_from_slice(&bytes);
                    }
                }
                _ => {
                    // Milestone 1: only Int64 columns.
                    return Ok(ResultColumn::new(TypedColumn::new_for_type(
                        &self.output_type,
                        num_rows,
                    )));
                }
            }
            offset += num_rows * 8;

            let validity_ptr = offset;
            // Write validity.
            let validity = col.validity();
            let mem_data = memory.data_mut(&mut store);
            for (i, &v) in validity.iter().enumerate() {
                mem_data[validity_ptr + i] = u8::from(v);
            }
            offset += num_rows;

            #[allow(clippy::as_conversions)]
            {
                param_values.push(wasmtime::Val::I32(values_ptr as i32));
                param_values.push(wasmtime::Val::I32(validity_ptr as i32));
            }
        }

        // Output pointers.
        let out_values_ptr = offset;
        offset += num_rows * 8;
        let out_validity_ptr = offset;
        offset += num_rows;
        let out_errors_ptr = offset;

        #[allow(clippy::as_conversions)]
        {
            param_values.push(wasmtime::Val::I32(out_values_ptr as i32));
            param_values.push(wasmtime::Val::I32(out_validity_ptr as i32));
            param_values.push(wasmtime::Val::I32(out_errors_ptr as i32));
        }

        // Instantiate and call.
        let instance = wasmtime::Instance::new(&mut store, &self.module, &[memory.into()])?;
        let eval_func = instance
            .get_func(&mut store, "eval")
            .expect("eval function must exist in compiled module");

        let mut results = [];
        eval_func.call(&mut store, &param_values, &mut results)?;

        // Read results back from WASM memory.
        let mut out_values = vec![0i64; num_rows];
        let mut out_validity = vec![false; num_rows];
        let mut out_errors = vec![false; num_rows];
        let mut error_codes = vec![0u32; num_rows];

        let mem_data = memory.data(&store);
        for i in 0..num_rows {
            let bytes: [u8; 8] = mem_data[out_values_ptr + i * 8..out_values_ptr + i * 8 + 8]
                .try_into()
                .expect("8 bytes");
            out_values[i] = i64::from_le_bytes(bytes);
            out_validity[i] = mem_data[out_validity_ptr + i] != 0;
            let error_byte = mem_data[out_errors_ptr + i];
            out_errors[i] = error_byte != 0;
            error_codes[i] = u32::from(error_byte);
        }

        let column = match self.output_type {
            SqlScalarType::Bool => TypedColumn::Bool {
                values: out_values.iter().map(|&v| v != 0).collect(),
                validity: out_validity,
            },
            _ => TypedColumn::Int64 {
                values: out_values,
                validity: out_validity,
            },
        };

        Ok(ResultColumn {
            column,
            errors: out_errors,
            error_codes,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use mz_expr::{BinaryFunc, MirScalarExpr, UnaryFunc};
    use mz_repr::{Datum, ReprColumnType, ReprScalarType, Row, SqlScalarType};

    use crate::columnar::rows_to_columns;

    fn col(idx: usize) -> MirScalarExpr {
        MirScalarExpr::Column(idx, Default::default())
    }

    fn lit_i64(v: i64) -> MirScalarExpr {
        MirScalarExpr::Literal(
            Ok(Row::pack_slice(&[Datum::Int64(v)])),
            ReprColumnType {
                scalar_type: ReprScalarType::Int64,
                nullable: false,
            },
        )
    }

    fn add_i64(a: MirScalarExpr, b: MirScalarExpr) -> MirScalarExpr {
        MirScalarExpr::CallBinary {
            func: BinaryFunc::AddInt64(mz_expr::func::AddInt64),
            expr1: Box::new(a),
            expr2: Box::new(b),
        }
    }

    fn sub_i64(a: MirScalarExpr, b: MirScalarExpr) -> MirScalarExpr {
        MirScalarExpr::CallBinary {
            func: BinaryFunc::SubInt64(mz_expr::func::SubInt64),
            expr1: Box::new(a),
            expr2: Box::new(b),
        }
    }

    fn mul_i64(a: MirScalarExpr, b: MirScalarExpr) -> MirScalarExpr {
        MirScalarExpr::CallBinary {
            func: BinaryFunc::MulInt64(mz_expr::func::MulInt64),
            expr1: Box::new(a),
            expr2: Box::new(b),
        }
    }

    fn div_i64(a: MirScalarExpr, b: MirScalarExpr) -> MirScalarExpr {
        MirScalarExpr::CallBinary {
            func: BinaryFunc::DivInt64(mz_expr::func::DivInt64),
            expr1: Box::new(a),
            expr2: Box::new(b),
        }
    }

    fn mod_i64(a: MirScalarExpr, b: MirScalarExpr) -> MirScalarExpr {
        MirScalarExpr::CallBinary {
            func: BinaryFunc::ModInt64(mz_expr::func::ModInt64),
            expr1: Box::new(a),
            expr2: Box::new(b),
        }
    }

    fn bitand_i64(a: MirScalarExpr, b: MirScalarExpr) -> MirScalarExpr {
        MirScalarExpr::CallBinary {
            func: BinaryFunc::BitAndInt64(mz_expr::func::BitAndInt64),
            expr1: Box::new(a),
            expr2: Box::new(b),
        }
    }

    fn bitor_i64(a: MirScalarExpr, b: MirScalarExpr) -> MirScalarExpr {
        MirScalarExpr::CallBinary {
            func: BinaryFunc::BitOrInt64(mz_expr::func::BitOrInt64),
            expr1: Box::new(a),
            expr2: Box::new(b),
        }
    }

    fn bitxor_i64(a: MirScalarExpr, b: MirScalarExpr) -> MirScalarExpr {
        MirScalarExpr::CallBinary {
            func: BinaryFunc::BitXorInt64(mz_expr::func::BitXorInt64),
            expr1: Box::new(a),
            expr2: Box::new(b),
        }
    }

    fn neg_i64(a: MirScalarExpr) -> MirScalarExpr {
        MirScalarExpr::CallUnary {
            func: UnaryFunc::NegInt64(mz_expr::func::NegInt64),
            expr: Box::new(a),
        }
    }

    fn bitnot_i64(a: MirScalarExpr) -> MirScalarExpr {
        MirScalarExpr::CallUnary {
            func: UnaryFunc::BitNotInt64(mz_expr::func::BitNotInt64),
            expr: Box::new(a),
        }
    }

    fn abs_i64(a: MirScalarExpr) -> MirScalarExpr {
        MirScalarExpr::CallUnary {
            func: UnaryFunc::AbsInt64(mz_expr::func::AbsInt64),
            expr: Box::new(a),
        }
    }

    #[mz_ore::test]
    fn test_compile_and_evaluate_simple_add() {
        let engine = ExprEngine::new().unwrap();
        let expr = add_i64(col(0), col(1));
        let input_types = vec![(SqlScalarType::Int64, true), (SqlScalarType::Int64, true)];

        let compiled = engine.compile(&expr, &input_types).unwrap().unwrap();

        let rows = vec![
            Row::pack_slice(&[Datum::Int64(1), Datum::Int64(2)]),
            Row::pack_slice(&[Datum::Int64(3), Datum::Int64(4)]),
            Row::pack_slice(&[Datum::Int64(10), Datum::Int64(20)]),
        ];
        let batch = rows_to_columns(&rows, &input_types);
        let result = compiled.evaluate(&batch).unwrap();

        // Check results: 1+2=3, 3+4=7, 10+20=30
        match &result.column {
            TypedColumn::Int64 { values, validity } => {
                assert_eq!(values, &[3, 7, 30]);
                assert!(validity.iter().all(|&v| v));
            }
            _ => panic!("expected Int64 column"),
        }
        assert!(result.errors.iter().all(|&e| !e));
    }

    #[mz_ore::test]
    fn test_null_propagation() {
        let engine = ExprEngine::new().unwrap();
        let expr = add_i64(col(0), col(1));
        let input_types = vec![(SqlScalarType::Int64, true), (SqlScalarType::Int64, true)];

        let compiled = engine.compile(&expr, &input_types).unwrap().unwrap();

        let rows = vec![
            Row::pack_slice(&[Datum::Int64(1), Datum::Int64(2)]),
            Row::pack_slice(&[Datum::Null, Datum::Int64(4)]),
            Row::pack_slice(&[Datum::Int64(5), Datum::Null]),
        ];
        let batch = rows_to_columns(&rows, &input_types);
        let result = compiled.evaluate(&batch).unwrap();

        match &result.column {
            TypedColumn::Int64 { values, validity } => {
                assert_eq!(values[0], 3); // 1+2
                assert!(validity[0]);
                // Row 1: NULL + 4 => NULL
                assert!(!validity[1]);
                // Row 2: 5 + NULL => NULL
                assert!(!validity[2]);
            }
            _ => panic!("expected Int64 column"),
        }
    }

    #[mz_ore::test]
    fn test_add_with_literal() {
        let engine = ExprEngine::new().unwrap();
        let expr = add_i64(col(0), lit_i64(100));
        let input_types = vec![(SqlScalarType::Int64, true)];

        let compiled = engine.compile(&expr, &input_types).unwrap().unwrap();

        let rows = vec![
            Row::pack_slice(&[Datum::Int64(1)]),
            Row::pack_slice(&[Datum::Int64(42)]),
        ];
        let batch = rows_to_columns(&rows, &input_types);
        let result = compiled.evaluate(&batch).unwrap();

        match &result.column {
            TypedColumn::Int64 { values, validity } => {
                assert_eq!(values, &[101, 142]);
                assert!(validity.iter().all(|&v| v));
            }
            _ => panic!("expected Int64 column"),
        }
    }

    #[mz_ore::test]
    fn test_empty_batch() {
        let engine = ExprEngine::new().unwrap();
        let expr = add_i64(col(0), col(1));
        let input_types = vec![(SqlScalarType::Int64, true), (SqlScalarType::Int64, true)];

        let compiled = engine.compile(&expr, &input_types).unwrap().unwrap();

        let batch = rows_to_columns(&[], &input_types);
        let result = compiled.evaluate(&batch).unwrap();
        assert_eq!(result.column.len(), 0);
    }

    #[mz_ore::test]
    fn test_unsupported_returns_none() {
        let engine = ExprEngine::new().unwrap();
        let expr = MirScalarExpr::CallVariadic {
            func: mz_expr::VariadicFunc::Coalesce(mz_expr::func::variadic::Coalesce),
            exprs: vec![col(0)],
        };
        let input_types = vec![(SqlScalarType::Int64, true)];

        let compiled = engine.compile(&expr, &input_types).unwrap();
        assert!(compiled.is_none());
    }

    /// Evaluates an expression using the interpreter for a single row,
    /// returning the result datum.
    fn eval_interpreted(
        expr: &MirScalarExpr,
        datums: &[Datum<'_>],
    ) -> Result<Datum<'static>, mz_expr::EvalError> {
        let arena = mz_repr::RowArena::new();
        let result = expr.eval(datums, &arena)?;
        // Convert to owned datum.
        Ok(match result {
            Datum::Int64(v) => Datum::Int64(v),
            Datum::True => Datum::True,
            Datum::False => Datum::False,
            Datum::Null => Datum::Null,
            other => panic!("unexpected datum type: {other:?}"),
        })
    }

    /// Compares compiled and interpreted evaluation for a given expression and data.
    fn assert_compiled_matches_interpreted(
        expr: &MirScalarExpr,
        rows: &[Vec<Option<i64>>],
        num_cols: usize,
    ) {
        let engine = ExprEngine::new().unwrap();
        let input_types: Vec<_> = (0..num_cols)
            .map(|_| (SqlScalarType::Int64, true))
            .collect();

        let compiled = engine.compile(expr, &input_types).unwrap().unwrap();

        // Build Row values.
        let row_values: Vec<Row> = rows
            .iter()
            .map(|row| {
                let datums: Vec<Datum<'_>> = row
                    .iter()
                    .map(|v| match v {
                        Some(val) => Datum::Int64(*val),
                        None => Datum::Null,
                    })
                    .collect();
                Row::pack_slice(&datums)
            })
            .collect();

        let batch = rows_to_columns(&row_values, &input_types);
        let result = compiled.evaluate(&batch).unwrap();

        // Compare with interpreted results.
        for (i, row) in rows.iter().enumerate() {
            let datums: Vec<Datum<'_>> = row
                .iter()
                .map(|v| match v {
                    Some(val) => Datum::Int64(*val),
                    None => Datum::Null,
                })
                .collect();

            let interpreted = eval_interpreted(expr, &datums);

            if result.errors[i] {
                // Compiled path detected an error; interpreter should too.
                assert!(
                    interpreted.is_err(),
                    "row {i}: compiled errored but interpreter returned {:?}",
                    interpreted
                );
                continue;
            }

            match &result.column {
                TypedColumn::Int64 { values, validity } => {
                    if !validity[i] {
                        assert!(
                            matches!(&interpreted, Ok(Datum::Null)),
                            "row {i}: compiled null but interpreter returned {interpreted:?}"
                        );
                    } else {
                        match &interpreted {
                            Ok(Datum::Int64(v)) => {
                                assert_eq!(
                                    values[i], *v,
                                    "row {i}: compiled={}, interpreted={}",
                                    values[i], v
                                );
                            }
                            other => {
                                panic!("row {i}: compiled {} but interpreted {other:?}", values[i])
                            }
                        }
                    }
                }
                TypedColumn::Bool { values, validity } => {
                    if !validity[i] {
                        assert!(
                            matches!(&interpreted, Ok(Datum::Null)),
                            "row {i}: compiled null but interpreter returned {interpreted:?}"
                        );
                    } else {
                        let expected = if values[i] { Datum::True } else { Datum::False };
                        match &interpreted {
                            Ok(d) => {
                                assert_eq!(
                                    *d, expected,
                                    "row {i}: compiled={:?}, interpreted={:?}",
                                    expected, d
                                );
                            }
                            other => {
                                panic!("row {i}: compiled {:?} but interpreted {other:?}", expected)
                            }
                        }
                    }
                }
                other => panic!("unexpected column type: {other:?}"),
            }
        }
    }

    use proptest::prelude::*;

    /// Strategy for generating an optional i64 (Some = value, None = null).
    fn arb_nullable_i64() -> impl Strategy<Value = Option<i64>> {
        proptest::strategy::Union::new_weighted(vec![
            (9, any::<i64>().prop_map(Some).boxed()),
            (1, Just(None).boxed()),
        ])
    }

    /// Strategy for generating a row of `num_cols` nullable i64 values.
    fn arb_row(num_cols: usize) -> impl Strategy<Value = Vec<Option<i64>>> {
        proptest::collection::vec(arb_nullable_i64(), num_cols)
    }

    /// Strategy for generating a batch of rows.
    fn arb_batch(num_cols: usize, max_rows: usize) -> impl Strategy<Value = Vec<Vec<Option<i64>>>> {
        proptest::collection::vec(arb_row(num_cols), 0..=max_rows)
    }

    #[mz_ore::test]
    fn proptest_add_two_columns() {
        proptest!(|(rows in arb_batch(2, 100))| {
            // The proptest! macro interferes with rustfmt.
            let expr = add_i64(col(0), col(1));
            assert_compiled_matches_interpreted(&expr, &rows, 2);
        });
    }

    #[mz_ore::test]
    fn proptest_add_column_and_literal() {
        proptest!(|(rows in arb_batch(1, 100), lit_val in any::<i64>())| {
            // The proptest! macro interferes with rustfmt.
            let expr = add_i64(col(0), lit_i64(lit_val));
            assert_compiled_matches_interpreted(&expr, &rows, 1);
        });
    }

    #[mz_ore::test]
    fn proptest_nested_add() {
        // (col0 + col1) + col2
        proptest!(|(rows in arb_batch(3, 50))| {
            // The proptest! macro interferes with rustfmt.
            let expr = add_i64(add_i64(col(0), col(1)), col(2));
            assert_compiled_matches_interpreted(&expr, &rows, 3);
        });
    }

    #[mz_ore::test]
    fn proptest_sub_two_columns() {
        proptest!(|(rows in arb_batch(2, 100))| {
            let expr = sub_i64(col(0), col(1));
            assert_compiled_matches_interpreted(&expr, &rows, 2);
        });
    }

    #[mz_ore::test]
    fn proptest_mul_two_columns() {
        proptest!(|(rows in arb_batch(2, 100))| {
            let expr = mul_i64(col(0), col(1));
            assert_compiled_matches_interpreted(&expr, &rows, 2);
        });
    }

    #[mz_ore::test]
    fn proptest_div_two_columns() {
        proptest!(|(rows in arb_batch(2, 100))| {
            let expr = div_i64(col(0), col(1));
            assert_compiled_matches_interpreted(&expr, &rows, 2);
        });
    }

    #[mz_ore::test]
    fn proptest_mod_two_columns() {
        proptest!(|(rows in arb_batch(2, 100))| {
            let expr = mod_i64(col(0), col(1));
            assert_compiled_matches_interpreted(&expr, &rows, 2);
        });
    }

    #[mz_ore::test]
    fn proptest_bitand_two_columns() {
        proptest!(|(rows in arb_batch(2, 100))| {
            let expr = bitand_i64(col(0), col(1));
            assert_compiled_matches_interpreted(&expr, &rows, 2);
        });
    }

    #[mz_ore::test]
    fn proptest_bitor_two_columns() {
        proptest!(|(rows in arb_batch(2, 100))| {
            let expr = bitor_i64(col(0), col(1));
            assert_compiled_matches_interpreted(&expr, &rows, 2);
        });
    }

    #[mz_ore::test]
    fn proptest_bitxor_two_columns() {
        proptest!(|(rows in arb_batch(2, 100))| {
            let expr = bitxor_i64(col(0), col(1));
            assert_compiled_matches_interpreted(&expr, &rows, 2);
        });
    }

    #[mz_ore::test]
    fn proptest_neg_column() {
        proptest!(|(rows in arb_batch(1, 100))| {
            let expr = neg_i64(col(0));
            assert_compiled_matches_interpreted(&expr, &rows, 1);
        });
    }

    #[mz_ore::test]
    fn proptest_bitnot_column() {
        proptest!(|(rows in arb_batch(1, 100))| {
            let expr = bitnot_i64(col(0));
            assert_compiled_matches_interpreted(&expr, &rows, 1);
        });
    }

    #[mz_ore::test]
    fn proptest_abs_column() {
        proptest!(|(rows in arb_batch(1, 100))| {
            let expr = abs_i64(col(0));
            assert_compiled_matches_interpreted(&expr, &rows, 1);
        });
    }

    #[mz_ore::test]
    fn proptest_nested_mixed_ops() {
        // (col0 + col1) * (col2 - col0)
        proptest!(|(rows in arb_batch(3, 50))| {
            let expr = mul_i64(add_i64(col(0), col(1)), sub_i64(col(2), col(0)));
            assert_compiled_matches_interpreted(&expr, &rows, 3);
        });
    }

    #[mz_ore::test]
    fn proptest_nested_unary_binary() {
        // neg(col0 + col1)
        proptest!(|(rows in arb_batch(2, 50))| {
            let expr = neg_i64(add_i64(col(0), col(1)));
            assert_compiled_matches_interpreted(&expr, &rows, 2);
        });
    }

    #[mz_ore::test]
    fn proptest_abs_of_sub() {
        // abs(col0 - col1)
        proptest!(|(rows in arb_batch(2, 50))| {
            let expr = abs_i64(sub_i64(col(0), col(1)));
            assert_compiled_matches_interpreted(&expr, &rows, 2);
        });
    }

    // --- Comparison and Bool helpers ---

    fn eq_expr(a: MirScalarExpr, b: MirScalarExpr) -> MirScalarExpr {
        MirScalarExpr::CallBinary {
            func: BinaryFunc::Eq(mz_expr::func::Eq),
            expr1: Box::new(a),
            expr2: Box::new(b),
        }
    }

    fn not_eq_expr(a: MirScalarExpr, b: MirScalarExpr) -> MirScalarExpr {
        MirScalarExpr::CallBinary {
            func: BinaryFunc::NotEq(mz_expr::func::NotEq),
            expr1: Box::new(a),
            expr2: Box::new(b),
        }
    }

    fn lt_expr(a: MirScalarExpr, b: MirScalarExpr) -> MirScalarExpr {
        MirScalarExpr::CallBinary {
            func: BinaryFunc::Lt(mz_expr::func::Lt),
            expr1: Box::new(a),
            expr2: Box::new(b),
        }
    }

    fn lte_expr(a: MirScalarExpr, b: MirScalarExpr) -> MirScalarExpr {
        MirScalarExpr::CallBinary {
            func: BinaryFunc::Lte(mz_expr::func::Lte),
            expr1: Box::new(a),
            expr2: Box::new(b),
        }
    }

    fn gt_expr(a: MirScalarExpr, b: MirScalarExpr) -> MirScalarExpr {
        MirScalarExpr::CallBinary {
            func: BinaryFunc::Gt(mz_expr::func::Gt),
            expr1: Box::new(a),
            expr2: Box::new(b),
        }
    }

    fn gte_expr(a: MirScalarExpr, b: MirScalarExpr) -> MirScalarExpr {
        MirScalarExpr::CallBinary {
            func: BinaryFunc::Gte(mz_expr::func::Gte),
            expr1: Box::new(a),
            expr2: Box::new(b),
        }
    }

    fn not_expr(a: MirScalarExpr) -> MirScalarExpr {
        MirScalarExpr::CallUnary {
            func: UnaryFunc::Not(mz_expr::func::Not),
            expr: Box::new(a),
        }
    }

    // --- Comparison proptests ---

    #[mz_ore::test]
    fn proptest_eq_two_columns() {
        proptest!(|(rows in arb_batch(2, 100))| {
            let expr = eq_expr(col(0), col(1));
            assert_compiled_matches_interpreted(&expr, &rows, 2);
        });
    }

    #[mz_ore::test]
    fn proptest_not_eq_two_columns() {
        proptest!(|(rows in arb_batch(2, 100))| {
            let expr = not_eq_expr(col(0), col(1));
            assert_compiled_matches_interpreted(&expr, &rows, 2);
        });
    }

    #[mz_ore::test]
    fn proptest_lt_two_columns() {
        proptest!(|(rows in arb_batch(2, 100))| {
            let expr = lt_expr(col(0), col(1));
            assert_compiled_matches_interpreted(&expr, &rows, 2);
        });
    }

    #[mz_ore::test]
    fn proptest_lte_two_columns() {
        proptest!(|(rows in arb_batch(2, 100))| {
            let expr = lte_expr(col(0), col(1));
            assert_compiled_matches_interpreted(&expr, &rows, 2);
        });
    }

    #[mz_ore::test]
    fn proptest_gt_two_columns() {
        proptest!(|(rows in arb_batch(2, 100))| {
            let expr = gt_expr(col(0), col(1));
            assert_compiled_matches_interpreted(&expr, &rows, 2);
        });
    }

    #[mz_ore::test]
    fn proptest_gte_two_columns() {
        proptest!(|(rows in arb_batch(2, 100))| {
            let expr = gte_expr(col(0), col(1));
            assert_compiled_matches_interpreted(&expr, &rows, 2);
        });
    }

    #[mz_ore::test]
    fn proptest_not_of_lt() {
        // NOT (col0 < col1)
        proptest!(|(rows in arb_batch(2, 100))| {
            let expr = not_expr(lt_expr(col(0), col(1)));
            assert_compiled_matches_interpreted(&expr, &rows, 2);
        });
    }

    #[mz_ore::test]
    fn proptest_comparison_with_arithmetic() {
        // (col0 + col1) < col2
        proptest!(|(rows in arb_batch(3, 50))| {
            let expr = lt_expr(add_i64(col(0), col(1)), col(2));
            assert_compiled_matches_interpreted(&expr, &rows, 3);
        });
    }

    #[mz_ore::test]
    fn proptest_nested_comparison_not() {
        // NOT (col0 = (col1 + col2))
        proptest!(|(rows in arb_batch(3, 50))| {
            let expr = not_expr(eq_expr(col(0), add_i64(col(1), col(2))));
            assert_compiled_matches_interpreted(&expr, &rows, 3);
        });
    }

    #[mz_ore::test]
    fn proptest_comparison_with_literal() {
        // col0 < 42
        proptest!(|(rows in arb_batch(1, 100))| {
            let expr = lt_expr(col(0), lit_i64(42));
            assert_compiled_matches_interpreted(&expr, &rows, 1);
        });
    }
}
