// Copyright Materialize, Inc. and contributors. All rights reserved.
//
// Use of this software is governed by the Business Source License
// included in the LICENSE file.
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0.

//! Wasmtime engine lifecycle, module compilation, and instance creation.
//!
//! Wraps the `wasmtime` crate to compile WASM bytecode generated by [`crate::codegen`]
//! and execute it on columnar data.

use mz_expr::MirScalarExpr;
use mz_repr::SqlScalarType;

use crate::codegen::{self, WasmLayout};
use crate::columnar::{ColumnBatch, ResultColumn, TypedColumn};

/// Shared WASM compilation engine. Reuse across multiple compiled expressions
/// to amortize engine initialization cost.
pub struct ExprEngine {
    engine: wasmtime::Engine,
}

/// A compiled WASM module ready to evaluate an expression on columnar data.
pub struct CompiledExpr {
    module: wasmtime::Module,
    layout: WasmLayout,
    /// The scalar type of the output column.
    output_type: SqlScalarType,
    /// The input column indices this expression reads from,
    /// in the order expected by the WASM function parameters.
    input_columns: Vec<usize>,
}

impl ExprEngine {
    /// Creates a new WASM engine with default settings.
    pub fn new() -> Result<Self, wasmtime::Error> {
        let engine = wasmtime::Engine::default();
        Ok(ExprEngine { engine })
    }

    /// Attempts to compile the given expression into a WASM module.
    ///
    /// Returns `None` if the expression is not compilable (uses unsupported operations).
    /// Returns `Err` if WASM compilation fails (internal error).
    pub fn compile(
        &self,
        expr: &MirScalarExpr,
        _input_types: &[(SqlScalarType, bool)],
    ) -> Result<Option<CompiledExpr>, wasmtime::Error> {
        let (wasm_bytes, layout) = match codegen::generate_wasm(expr) {
            Some(result) => result,
            None => return Ok(None),
        };

        let module = wasmtime::Module::new(&self.engine, &wasm_bytes)?;

        let input_columns = crate::analyze::referenced_columns(expr);

        // For milestone 1, the output type is always Int64.
        let output_type = SqlScalarType::Int64;

        Ok(Some(CompiledExpr {
            module,
            layout,
            output_type,
            input_columns,
        }))
    }
}

impl CompiledExpr {
    /// Evaluates the compiled expression on the given column batch.
    ///
    /// The batch must contain columns at the indices referenced by the expression.
    /// Returns a [`ResultColumn`] with the computed output values, validity, and error flags.
    pub fn evaluate(&self, batch: &ColumnBatch) -> Result<ResultColumn, wasmtime::Error> {
        let num_rows = batch.num_rows;
        if num_rows == 0 {
            return Ok(ResultColumn::new(TypedColumn::new_for_type(
                &self.output_type,
                0,
            )));
        }

        let mut store = wasmtime::Store::new(self.module.engine(), ());

        // Calculate memory needed:
        // Per input column: num_rows * 8 (values) + num_rows (validity)
        // Output: num_rows * 8 (values) + num_rows (validity) + num_rows (errors)
        let per_col_bytes = num_rows * 8 + num_rows;
        let output_bytes = num_rows * 8 + num_rows + num_rows;
        let total_bytes = self.layout.num_input_cols * per_col_bytes + output_bytes;
        let num_pages = (total_bytes + 65535) / 65536; // Round up to WASM pages (64KB each)

        let memory_type = wasmtime::MemoryType::new(u32::try_from(num_pages).unwrap_or(1), None);
        let memory = wasmtime::Memory::new(&mut store, memory_type)?;

        // Lay out data in linear memory.
        // Layout: [col0_values][col0_validity][col1_values][col1_validity]...[out_values][out_validity][errors]
        let mut offset: usize = 0;
        let mut param_values: Vec<wasmtime::Val> = Vec::new();

        // First param: num_rows.
        #[allow(clippy::as_conversions)]
        param_values.push(wasmtime::Val::I32(num_rows as i32));

        // Copy input columns into WASM memory.
        for &col_idx in &self.input_columns {
            let col = &batch.columns[col_idx];
            let values_ptr = offset;

            // Write values.
            match col {
                TypedColumn::Int64 { values, .. } => {
                    let mem_data = memory.data_mut(&mut store);
                    for (i, &v) in values.iter().enumerate() {
                        let bytes = v.to_le_bytes();
                        let dst = values_ptr + i * 8;
                        mem_data[dst..dst + 8].copy_from_slice(&bytes);
                    }
                }
                _ => {
                    // Milestone 1: only Int64 columns.
                    return Ok(ResultColumn::new(TypedColumn::new_for_type(
                        &self.output_type,
                        num_rows,
                    )));
                }
            }
            offset += num_rows * 8;

            let validity_ptr = offset;
            // Write validity.
            let validity = col.validity();
            let mem_data = memory.data_mut(&mut store);
            for (i, &v) in validity.iter().enumerate() {
                mem_data[validity_ptr + i] = u8::from(v);
            }
            offset += num_rows;

            #[allow(clippy::as_conversions)]
            {
                param_values.push(wasmtime::Val::I32(values_ptr as i32));
                param_values.push(wasmtime::Val::I32(validity_ptr as i32));
            }
        }

        // Output pointers.
        let out_values_ptr = offset;
        offset += num_rows * 8;
        let out_validity_ptr = offset;
        offset += num_rows;
        let out_errors_ptr = offset;

        #[allow(clippy::as_conversions)]
        {
            param_values.push(wasmtime::Val::I32(out_values_ptr as i32));
            param_values.push(wasmtime::Val::I32(out_validity_ptr as i32));
            param_values.push(wasmtime::Val::I32(out_errors_ptr as i32));
        }

        // Instantiate and call.
        let instance = wasmtime::Instance::new(&mut store, &self.module, &[memory.into()])?;
        let eval_func = instance
            .get_func(&mut store, "eval")
            .expect("eval function must exist in compiled module");

        let mut results = [];
        eval_func.call(&mut store, &param_values, &mut results)?;

        // Read results back from WASM memory.
        let mut out_values = vec![0i64; num_rows];
        let mut out_validity = vec![false; num_rows];
        let mut out_errors = vec![false; num_rows];
        let mut error_codes = vec![0u32; num_rows];

        let mem_data = memory.data(&store);
        for i in 0..num_rows {
            let bytes: [u8; 8] = mem_data[out_values_ptr + i * 8..out_values_ptr + i * 8 + 8]
                .try_into()
                .expect("8 bytes");
            out_values[i] = i64::from_le_bytes(bytes);
            out_validity[i] = mem_data[out_validity_ptr + i] != 0;
            out_errors[i] = mem_data[out_errors_ptr + i] != 0;
            if out_errors[i] {
                // EvalError::NumericFieldOverflow discriminant.
                error_codes[i] = 1;
            }
        }

        Ok(ResultColumn {
            column: TypedColumn::Int64 {
                values: out_values,
                validity: out_validity,
            },
            errors: out_errors,
            error_codes,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use mz_expr::{BinaryFunc, MirScalarExpr};
    use mz_repr::{Datum, ReprColumnType, ReprScalarType, Row, SqlScalarType};

    use crate::columnar::rows_to_columns;

    fn col(idx: usize) -> MirScalarExpr {
        MirScalarExpr::Column(idx, Default::default())
    }

    fn lit_i64(v: i64) -> MirScalarExpr {
        MirScalarExpr::Literal(
            Ok(Row::pack_slice(&[Datum::Int64(v)])),
            ReprColumnType {
                scalar_type: ReprScalarType::Int64,
                nullable: false,
            },
        )
    }

    fn add_i64(a: MirScalarExpr, b: MirScalarExpr) -> MirScalarExpr {
        MirScalarExpr::CallBinary {
            func: BinaryFunc::AddInt64(mz_expr::func::AddInt64),
            expr1: Box::new(a),
            expr2: Box::new(b),
        }
    }

    #[mz_ore::test]
    fn test_compile_and_evaluate_simple_add() {
        let engine = ExprEngine::new().unwrap();
        let expr = add_i64(col(0), col(1));
        let input_types = vec![(SqlScalarType::Int64, true), (SqlScalarType::Int64, true)];

        let compiled = engine.compile(&expr, &input_types).unwrap().unwrap();

        let rows = vec![
            Row::pack_slice(&[Datum::Int64(1), Datum::Int64(2)]),
            Row::pack_slice(&[Datum::Int64(3), Datum::Int64(4)]),
            Row::pack_slice(&[Datum::Int64(10), Datum::Int64(20)]),
        ];
        let batch = rows_to_columns(&rows, &input_types);
        let result = compiled.evaluate(&batch).unwrap();

        // Check results: 1+2=3, 3+4=7, 10+20=30
        match &result.column {
            TypedColumn::Int64 { values, validity } => {
                assert_eq!(values, &[3, 7, 30]);
                assert!(validity.iter().all(|&v| v));
            }
            _ => panic!("expected Int64 column"),
        }
        assert!(result.errors.iter().all(|&e| !e));
    }

    #[mz_ore::test]
    fn test_null_propagation() {
        let engine = ExprEngine::new().unwrap();
        let expr = add_i64(col(0), col(1));
        let input_types = vec![(SqlScalarType::Int64, true), (SqlScalarType::Int64, true)];

        let compiled = engine.compile(&expr, &input_types).unwrap().unwrap();

        let rows = vec![
            Row::pack_slice(&[Datum::Int64(1), Datum::Int64(2)]),
            Row::pack_slice(&[Datum::Null, Datum::Int64(4)]),
            Row::pack_slice(&[Datum::Int64(5), Datum::Null]),
        ];
        let batch = rows_to_columns(&rows, &input_types);
        let result = compiled.evaluate(&batch).unwrap();

        match &result.column {
            TypedColumn::Int64 { values, validity } => {
                assert_eq!(values[0], 3); // 1+2
                assert!(validity[0]);
                // Row 1: NULL + 4 => NULL
                assert!(!validity[1]);
                // Row 2: 5 + NULL => NULL
                assert!(!validity[2]);
            }
            _ => panic!("expected Int64 column"),
        }
    }

    #[mz_ore::test]
    fn test_add_with_literal() {
        let engine = ExprEngine::new().unwrap();
        let expr = add_i64(col(0), lit_i64(100));
        let input_types = vec![(SqlScalarType::Int64, true)];

        let compiled = engine.compile(&expr, &input_types).unwrap().unwrap();

        let rows = vec![
            Row::pack_slice(&[Datum::Int64(1)]),
            Row::pack_slice(&[Datum::Int64(42)]),
        ];
        let batch = rows_to_columns(&rows, &input_types);
        let result = compiled.evaluate(&batch).unwrap();

        match &result.column {
            TypedColumn::Int64 { values, validity } => {
                assert_eq!(values, &[101, 142]);
                assert!(validity.iter().all(|&v| v));
            }
            _ => panic!("expected Int64 column"),
        }
    }

    #[mz_ore::test]
    fn test_empty_batch() {
        let engine = ExprEngine::new().unwrap();
        let expr = add_i64(col(0), col(1));
        let input_types = vec![(SqlScalarType::Int64, true), (SqlScalarType::Int64, true)];

        let compiled = engine.compile(&expr, &input_types).unwrap().unwrap();

        let batch = rows_to_columns(&[], &input_types);
        let result = compiled.evaluate(&batch).unwrap();
        assert_eq!(result.column.len(), 0);
    }

    #[mz_ore::test]
    fn test_unsupported_returns_none() {
        let engine = ExprEngine::new().unwrap();
        let expr = MirScalarExpr::CallVariadic {
            func: mz_expr::VariadicFunc::Coalesce(mz_expr::func::variadic::Coalesce),
            exprs: vec![col(0)],
        };
        let input_types = vec![(SqlScalarType::Int64, true)];

        let compiled = engine.compile(&expr, &input_types).unwrap();
        assert!(compiled.is_none());
    }

    /// Evaluates an expression using the interpreter for a single row,
    /// returning the result datum.
    fn eval_interpreted(
        expr: &MirScalarExpr,
        datums: &[Datum<'_>],
    ) -> Result<Datum<'static>, mz_expr::EvalError> {
        let arena = mz_repr::RowArena::new();
        let result = expr.eval(datums, &arena)?;
        // Convert to owned datum.
        Ok(match result {
            Datum::Int64(v) => Datum::Int64(v),
            Datum::Null => Datum::Null,
            other => panic!("unexpected datum type: {other:?}"),
        })
    }

    /// Compares compiled and interpreted evaluation for a given expression and data.
    fn assert_compiled_matches_interpreted(
        expr: &MirScalarExpr,
        rows: &[Vec<Option<i64>>],
        num_cols: usize,
    ) {
        let engine = ExprEngine::new().unwrap();
        let input_types: Vec<_> = (0..num_cols)
            .map(|_| (SqlScalarType::Int64, true))
            .collect();

        let compiled = engine.compile(expr, &input_types).unwrap().unwrap();

        // Build Row values.
        let row_values: Vec<Row> = rows
            .iter()
            .map(|row| {
                let datums: Vec<Datum<'_>> = row
                    .iter()
                    .map(|v| match v {
                        Some(val) => Datum::Int64(*val),
                        None => Datum::Null,
                    })
                    .collect();
                Row::pack_slice(&datums)
            })
            .collect();

        let batch = rows_to_columns(&row_values, &input_types);
        let result = compiled.evaluate(&batch).unwrap();

        // Compare with interpreted results.
        for (i, row) in rows.iter().enumerate() {
            let datums: Vec<Datum<'_>> = row
                .iter()
                .map(|v| match v {
                    Some(val) => Datum::Int64(*val),
                    None => Datum::Null,
                })
                .collect();

            let interpreted = eval_interpreted(expr, &datums);
            match &result.column {
                TypedColumn::Int64 { values, validity } => {
                    if result.errors[i] {
                        // Compiled path detected an error; interpreter should too.
                        assert!(
                            interpreted.is_err(),
                            "row {i}: compiled errored but interpreter returned {:?}",
                            interpreted
                        );
                    } else if !validity[i] {
                        // Compiled path says null.
                        match &interpreted {
                            Ok(Datum::Null) => {}
                            // Milestone 1: compiled path does wrapping add without overflow
                            // detection, so null propagation can mask overflows that the
                            // interpreter would catch.
                            Err(_) => {}
                            other => {
                                panic!("row {i}: compiled null but interpreter returned {other:?}")
                            }
                        }
                    } else {
                        // Compiled path returned a value.
                        match &interpreted {
                            Ok(Datum::Int64(v)) => {
                                // Note: compiled path does wrapping add (no overflow detection yet),
                                // so we only compare when the interpreted result doesn't overflow.
                                assert_eq!(
                                    values[i], *v,
                                    "row {i}: compiled={}, interpreted={}",
                                    values[i], v
                                );
                            }
                            Err(_) => {
                                // Interpreter overflowed but compiled path wrapped.
                                // This is expected for milestone 1 (no overflow detection in WASM).
                            }
                            other => {
                                panic!("row {i}: compiled {} but interpreted {other:?}", values[i])
                            }
                        }
                    }
                }
                _ => panic!("expected Int64 column"),
            }
        }
    }

    use proptest::prelude::*;

    /// Strategy for generating an optional i64 (Some = value, None = null).
    fn arb_nullable_i64() -> impl Strategy<Value = Option<i64>> {
        proptest::strategy::Union::new_weighted(vec![
            (9, any::<i64>().prop_map(Some).boxed()),
            (1, Just(None).boxed()),
        ])
    }

    /// Strategy for generating a row of `num_cols` nullable i64 values.
    fn arb_row(num_cols: usize) -> impl Strategy<Value = Vec<Option<i64>>> {
        proptest::collection::vec(arb_nullable_i64(), num_cols)
    }

    /// Strategy for generating a batch of rows.
    fn arb_batch(num_cols: usize, max_rows: usize) -> impl Strategy<Value = Vec<Vec<Option<i64>>>> {
        proptest::collection::vec(arb_row(num_cols), 0..=max_rows)
    }

    #[mz_ore::test]
    fn proptest_add_two_columns() {
        proptest!(|(rows in arb_batch(2, 100))| {
            // The proptest! macro interferes with rustfmt.
            let expr = add_i64(col(0), col(1));
            assert_compiled_matches_interpreted(&expr, &rows, 2);
        });
    }

    #[mz_ore::test]
    fn proptest_add_column_and_literal() {
        proptest!(|(rows in arb_batch(1, 100), lit_val in any::<i64>())| {
            // The proptest! macro interferes with rustfmt.
            let expr = add_i64(col(0), lit_i64(lit_val));
            assert_compiled_matches_interpreted(&expr, &rows, 1);
        });
    }

    #[mz_ore::test]
    fn proptest_nested_add() {
        // (col0 + col1) + col2
        proptest!(|(rows in arb_batch(3, 50))| {
            // The proptest! macro interferes with rustfmt.
            let expr = add_i64(add_i64(col(0), col(1)), col(2));
            assert_compiled_matches_interpreted(&expr, &rows, 3);
        });
    }
}
