# Copyright Materialize, Inc. and contributors. All rights reserved.
#
# Use of this software is governed by the Business Source License
# included in the LICENSE file at the root of this repository.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0.

# Note: This mzimage is a simple wrapper around the Fivetran Destination Tester to act as a mirror
#       and decouple ourselves from Fivetran's Dockerhub, incase Fivetran removes the image that we
#       depend on.

FROM fivetrandocker/sdk-destination-tester:024.0314.001
