# Copyright Materialize, Inc. and contributors. All rights reserved.
#
# Use of this software is governed by the Business Source License
# included in the LICENSE file at the root of this repository.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0.

"""
Configuration constants for workload replay.
"""

from materialize import MZ_ROOT

LOCATION = MZ_ROOT / "test" / "workload-replay" / "captured-workloads"
WORKLOAD_REPLAY_VERSION = "1.0.0"  # Used for uploading test analytics results
SEED_RANGE = 1_000_000

cluster_replica_sizes = {
    "bootstrap": {
        "cpu_exclusive": False,
        "cpu_limit": 0.5,
        "credits_per_hour": "0.25",
        "disk_limit": "7762MiB",
        "memory_limit": "3881MiB",
        "scale": 1,
        "workers": 1,
    },
    # M.1 cluster replica sizes
    "M.1-nano": {
        "cpu_exclusive": False,
        "cpu_limit": 0.5,
        "credits_per_hour": "0.75",
        "disk_limit": "26624MiB",
        "memory_limit": "3881MiB",
        "scale": 1,
        "workers": 1,
    },
    "M.1-micro": {
        "cpu_exclusive": True,
        "cpu_limit": 1,
        "credits_per_hour": "1.5",
        "disk_limit": "54272MiB",
        "memory_limit": "7762MiB",
        "scale": 1,
        "workers": 1,
    },
    "M.1-xsmall": {
        "cpu_exclusive": True,
        "cpu_limit": 2,
        "credits_per_hour": "3",
        "disk_limit": "108544MiB",
        "memory_limit": "15525MiB",
        "scale": 1,
        "workers": 2,
    },
    "M.1-small": {
        "cpu_exclusive": True,
        "cpu_limit": 4,
        "credits_per_hour": "6",
        "disk_limit": "217088MiB",
        "memory_limit": "31050MiB",
        "scale": 1,
        "workers": 4,
    },
    "M.1-medium": {
        "cpu_exclusive": True,
        "cpu_limit": 6,
        "credits_per_hour": "9",
        "disk_limit": "325632MiB",
        "memory_limit": "46575MiB",
        "scale": 1,
        "workers": 6,
    },
    "M.1-large": {
        "cpu_exclusive": True,
        "cpu_limit": 8,
        "credits_per_hour": "12",
        "disk_limit": "434176MiB",
        "memory_limit": "62100MiB",
        "scale": 1,
        "workers": 8,
    },
    "M.1-1.5xlarge": {
        "cpu_exclusive": True,
        "cpu_limit": 12,
        "credits_per_hour": "18",
        "disk_limit": "651264MiB",
        "memory_limit": "93150MiB",
        "scale": 1,
        "workers": 12,
    },
    "M.1-2xlarge": {
        "cpu_exclusive": True,
        "cpu_limit": 16,
        "credits_per_hour": "24",
        "disk_limit": "869376MiB",
        "memory_limit": "124201MiB",
        "scale": 1,
        "workers": 16,
    },
    "M.1-3xlarge": {
        "cpu_exclusive": True,
        "cpu_limit": 24,
        "credits_per_hour": "36",
        "disk_limit": "1303552MiB",
        "memory_limit": "186301MiB",
        "scale": 1,
        "workers": 24,
    },
    "M.1-4xlarge": {
        "cpu_exclusive": True,
        "cpu_limit": 31,
        "credits_per_hour": "48",
        "disk_limit": "1684480MiB",
        "memory_limit": "240640MiB",
        "scale": 1,
        "workers": 31,
    },
    "M.1-8xlarge": {
        "cpu_exclusive": True,
        "cpu_limit": 62,
        "credits_per_hour": "96",
        "disk_limit": "3368960MiB",
        "memory_limit": "481280MiB",
        "scale": 1,
        "workers": 62,
    },
    # Fake, just to be able to create clusters
    "M.1-16xlarge": {
        "cpu_exclusive": True,
        "cpu_limit": 62,
        "credits_per_hour": "192",
        "disk_limit": "6737920MiB",
        "memory_limit": "481280MiB",
        "scale": 1,
        "workers": 62,
    },
    "M.1-32xlarge": {
        "cpu_exclusive": True,
        "cpu_limit": 62,
        "credits_per_hour": "384",
        "disk_limit": "13475840MiB",
        "memory_limit": "481280MiB",
        "scale": 1,
        "workers": 62,
    },
    "M.1-64xlarge": {
        "cpu_exclusive": True,
        "cpu_limit": 62,
        "credits_per_hour": "768",
        "disk_limit": "26951680MiB",
        "memory_limit": "481280MiB",
        "scale": 1,
        "workers": 62,
    },
    "M.1-128xlarge": {
        "cpu_exclusive": True,
        "cpu_limit": 62,
        "credits_per_hour": "1536",
        "disk_limit": "53719040",
        "memory_limit": "481280MiB",
        "scale": 1,
        "workers": 62,
    },
    # cc cluster replica sizes
    "25cc": {
        "cpu_exclusive": False,
        "cpu_limit": 0.5,
        "credits_per_hour": "0.25",
        "disk_limit": "7762MiB",
        "memory_limit": "3881MiB",
        "scale": 1,
        "workers": 1,
    },
    "50cc": {
        "cpu_exclusive": True,
        "cpu_limit": 1,
        "credits_per_hour": "0.5",
        "disk_limit": "15525MiB",
        "memory_limit": "7762MiB",
        "scale": 1,
        "workers": 1,
    },
    "100cc": {
        "cpu_exclusive": True,
        "cpu_limit": 2,
        "credits_per_hour": "1",
        "disk_limit": "31050MiB",
        "memory_limit": "15525MiB",
        "scale": 1,
        "workers": 2,
    },
    "200cc": {
        "cpu_exclusive": True,
        "cpu_limit": 4,
        "credits_per_hour": "2",
        "disk_limit": "62100MiB",
        "memory_limit": "31050MiB",
        "scale": 1,
        "workers": 4,
    },
    "300cc": {
        "cpu_exclusive": True,
        "cpu_limit": 6,
        "credits_per_hour": "3",
        "disk_limit": "93150MiB",
        "memory_limit": "46575MiB",
        "scale": 1,
        "workers": 6,
    },
    "400cc": {
        "cpu_exclusive": True,
        "cpu_limit": 8,
        "credits_per_hour": "4",
        "disk_limit": "124201MiB",
        "memory_limit": "62100MiB",
        "scale": 1,
        "workers": 8,
    },
    "600cc": {
        "cpu_exclusive": True,
        "cpu_limit": 12,
        "credits_per_hour": "6",
        "disk_limit": "186301MiB",
        "memory_limit": "93150MiB",
        "scale": 1,
        "workers": 12,
    },
    "800cc": {
        "cpu_exclusive": True,
        "cpu_limit": 16,
        "credits_per_hour": "8",
        "disk_limit": "248402MiB",
        "memory_limit": "124201MiB",
        "scale": 1,
        "workers": 16,
    },
    "1200cc": {
        "cpu_exclusive": True,
        "cpu_limit": 24,
        "credits_per_hour": "12",
        "disk_limit": "372603MiB",
        "memory_limit": "186301MiB",
        "scale": 1,
        "workers": 24,
    },
    "1600cc": {
        "cpu_exclusive": True,
        "cpu_limit": 31,
        "credits_per_hour": "16",
        "disk_limit": "481280MiB",
        "memory_limit": "240640MiB",
        "scale": 1,
        "workers": 31,
    },
    "3200cc": {
        "cpu_exclusive": True,
        "cpu_limit": 62,
        "credits_per_hour": "32",
        "disk_limit": "962560MiB",
        "memory_limit": "481280MiB",
        "scale": 1,
        "workers": 62,
    },
    # Fake, just to be able to create clusters
    "6400cc": {
        "cpu_exclusive": True,
        "cpu_limit": 62,
        "credits_per_hour": "32",
        "disk_limit": "962560MiB",
        "memory_limit": "481280MiB",
        "scale": 1,
        "workers": 62,
    },
    "128C": {
        "cpu_exclusive": True,
        "cpu_limit": 62,
        "credits_per_hour": "32",
        "disk_limit": "962560MiB",
        "memory_limit": "481280MiB",
        "scale": 1,
        "workers": 62,
    },
    "256C": {
        "cpu_exclusive": True,
        "cpu_limit": 62,
        "credits_per_hour": "32",
        "disk_limit": "962560MiB",
        "memory_limit": "481280MiB",
        "scale": 1,
        "workers": 62,
    },
    "512C": {
        "cpu_exclusive": True,
        "cpu_limit": 62,
        "credits_per_hour": "32",
        "disk_limit": "962560MiB",
        "memory_limit": "481280MiB",
        "scale": 1,
        "workers": 62,
    },
    # Internal test sizes
    "scale=1,workers=1": {
        "cpu_exclusive": True,
        "cpu_limit": 1,
        "credits_per_hour": "0.5",
        "disk_limit": "15525MiB",
        "memory_limit": "7762MiB",
        "scale": 1,
        "workers": 1,
    },
    "scale=1,workers=2": {
        "cpu_exclusive": True,
        "cpu_limit": 2,
        "credits_per_hour": "1",
        "disk_limit": "31050MiB",
        "memory_limit": "15525MiB",
        "scale": 1,
        "workers": 2,
    },
    "scale=1,workers=4": {
        "cpu_exclusive": True,
        "cpu_limit": 4,
        "credits_per_hour": "2",
        "disk_limit": "62100MiB",
        "memory_limit": "31050MiB",
        "scale": 1,
        "workers": 4,
    },
    "scale=1,workers=6": {
        "cpu_exclusive": True,
        "cpu_limit": 6,
        "credits_per_hour": "3",
        "disk_limit": "93150MiB",
        "memory_limit": "46575MiB",
        "scale": 1,
        "workers": 6,
    },
    "scale=1,workers=8": {
        "cpu_exclusive": True,
        "cpu_limit": 8,
        "credits_per_hour": "4",
        "disk_limit": "124201MiB",
        "memory_limit": "62100MiB",
        "scale": 1,
        "workers": 8,
    },
    "scale=1,workers=12": {
        "cpu_exclusive": True,
        "cpu_limit": 12,
        "credits_per_hour": "6",
        "disk_limit": "186301MiB",
        "memory_limit": "93150MiB",
        "scale": 1,
        "workers": 12,
    },
    "scale=1,workers=16": {
        "cpu_exclusive": True,
        "cpu_limit": 16,
        "credits_per_hour": "8",
        "disk_limit": "248402MiB",
        "memory_limit": "124201MiB",
        "scale": 1,
        "workers": 16,
    },
    "scale=1,workers=24": {
        "cpu_exclusive": True,
        "cpu_limit": 24,
        "credits_per_hour": "12",
        "disk_limit": "372603MiB",
        "memory_limit": "186301MiB",
        "scale": 1,
        "workers": 24,
    },
    "scale=1,workers=31": {
        "cpu_exclusive": True,
        "cpu_limit": 31,
        "credits_per_hour": "16",
        "disk_limit": "481280MiB",
        "memory_limit": "240640MiB",
        "scale": 1,
        "workers": 31,
    },
    "scale=1,workers=62": {
        "cpu_exclusive": True,
        "cpu_limit": 62,
        "credits_per_hour": "32",
        "disk_limit": "962560MiB",
        "memory_limit": "481280MiB",
        "scale": 1,
        "workers": 62,
    },
    "scale=2,workers=1": {
        "cpu_exclusive": True,
        "cpu_limit": 1,
        "credits_per_hour": "0.5",
        "disk_limit": "15525MiB",
        "memory_limit": "7762MiB",
        "scale": 2,
        "workers": 1,
    },
    "scale=4,workers=1": {
        "cpu_exclusive": True,
        "cpu_limit": 1,
        "credits_per_hour": "0.5",
        "disk_limit": "15525MiB",
        "memory_limit": "7762MiB",
        "scale": 4,
        "workers": 1,
    },
}
