-- Copyright Materialize, Inc. and contributors. All rights reserved.
--
-- Use of this software is governed by the Business Source License
-- included in the LICENSE file at the root of this repository.
--
-- As of the Change Date specified in that file, in accordance with
-- the Business Source License, use of this software will be governed
-- by the Apache License, Version 2.0.

-- Materialize Catalog Ontology: Entity Types

INSERT INTO misc_mz_ontology.entity_types (name, relation, properties, description) VALUES

('database', 'mz_catalog.mz_databases', '{"primary_key": ["id"]}'::jsonb, 'A top-level namespace that contains schemas'),
('schema', 'mz_catalog.mz_schemas', '{"primary_key": ["id"]}'::jsonb, 'A namespace within a database that contains objects'),
('role', 'mz_catalog.mz_roles', '{"primary_key": ["id"]}'::jsonb, 'A user or role for authentication and access control'),
('cluster', 'mz_catalog.mz_clusters', '{"primary_key": ["id"]}'::jsonb, 'A compute cluster that runs dataflows for sources, sinks, MVs, and indexes'),
('replica', 'mz_catalog.mz_cluster_replicas', '{"primary_key": ["id"]}'::jsonb, 'A physical replica of a cluster providing fault tolerance'),
('table', 'mz_catalog.mz_tables', '{"primary_key": ["id"]}'::jsonb, 'A user-writable table that can be inserted into and updated'),
('source', 'mz_catalog.mz_sources', '{"primary_key": ["id"]}'::jsonb, 'An external data source ingested into Materialize (e.g., Kafka, Postgres)'),
('view', 'mz_catalog.mz_views', '{"primary_key": ["id"]}'::jsonb, 'A non-materialized view defined by a SQL query'),
('mv', 'mz_catalog.mz_materialized_views', '{"primary_key": ["id"]}'::jsonb, 'A materialized view maintained incrementally on a cluster'),
('index', 'mz_catalog.mz_indexes', '{"primary_key": ["id"]}'::jsonb, 'An in-memory index on a relation for fast lookups'),
('sink', 'mz_catalog.mz_sinks', '{"primary_key": ["id"]}'::jsonb, 'An export of data from Materialize to an external system'),
('connection', 'mz_catalog.mz_connections', '{"primary_key": ["id"]}'::jsonb, 'A reusable connection configuration to an external system'),
('secret', 'mz_catalog.mz_secrets', '{"primary_key": ["id"]}'::jsonb, 'An encrypted secret value used by connections'),
('type', 'mz_catalog.mz_types', '{"primary_key": ["id"]}'::jsonb, 'A named data type (base, array, list, map, or pseudo)'),
('array_type', 'mz_catalog.mz_array_types', '{"primary_key": ["id"]}'::jsonb, 'An array type with its element type'),
('list_type', 'mz_catalog.mz_list_types', '{"primary_key": ["id"]}'::jsonb, 'A list type with its element type'),
('map_type', 'mz_catalog.mz_map_types', '{"primary_key": ["id"]}'::jsonb, 'A map type with its key and value types'),
('base_type', 'mz_catalog.mz_base_types', '{"primary_key": ["id"]}'::jsonb, 'A primitive/base data type'),
('pseudo_type', 'mz_catalog.mz_pseudo_types', '{"primary_key": ["id"]}'::jsonb, 'A pseudo-type used in function signatures'),
('function', 'mz_catalog.mz_functions', '{"primary_key": ["id"]}'::jsonb, 'A built-in or user-defined function'),
('operator', 'mz_catalog.mz_operators', NULL, 'A built-in SQL operator'),
('relation', 'mz_catalog.mz_relations', '{"primary_key": ["id"]}'::jsonb, 'Union of all relation types: tables, sources, views, MVs (convenience view)'),
('object', 'mz_catalog.mz_objects', '{"primary_key": ["id"]}'::jsonb, 'Union of all object types: relations, indexes, connections, etc. (convenience view)'),
('column', 'mz_catalog.mz_columns', NULL, 'A column of a relation, with its name, position, type, and nullability'),
('index_column', 'mz_catalog.mz_index_columns', NULL, 'A column or expression in an index, with its position'),
('role_member', 'mz_catalog.mz_role_members', NULL, 'A membership grant: one role is a member of another role'),
('role_parameter', 'mz_catalog.mz_role_parameters', NULL, 'A session parameter default set for a role'),
('default_privilege', 'mz_catalog.mz_default_privileges', NULL, 'A default privilege rule applied to newly created objects'),
('system_privilege', 'mz_catalog.mz_system_privileges', NULL, 'A system-level privilege grant'),
('kafka_connection', 'mz_catalog.mz_kafka_connections', NULL, 'Kafka-specific connection configuration (brokers, progress topic)'),
('ssh_tunnel', 'mz_catalog.mz_ssh_tunnel_connections', NULL, 'SSH tunnel connection with public keys'),
('aws_privatelink', 'mz_catalog.mz_aws_privatelink_connections', NULL, 'AWS PrivateLink connection configuration'),
('kafka_source', 'mz_catalog.mz_kafka_sources', NULL, 'Kafka-specific source configuration (topic, group ID)'),
('kafka_sink', 'mz_catalog.mz_kafka_sinks', '{"primary_key": ["id"]}'::jsonb, 'Kafka-specific sink configuration (topic)'),
('iceberg_sink', 'mz_catalog.mz_iceberg_sinks', NULL, 'Iceberg-specific sink configuration (namespace, table)'),
('audit_event', 'mz_catalog.mz_audit_events', '{"primary_key": ["id"]}'::jsonb, 'An audit log entry recording a DDL operation'),
('storage_usage', 'mz_catalog.mz_storage_usage', '{"primary_key": ["object_id", "collection_timestamp"]}'::jsonb, 'Historical storage usage per object over time'),
('recent_storage', 'mz_catalog.mz_recent_storage_usage', '{"primary_key": ["object_id"]}'::jsonb, 'Most recent storage usage snapshot per object'),
('replica_size', 'mz_catalog.mz_cluster_replica_sizes', '{"primary_key": ["size"]}'::jsonb, 'Available cluster replica sizes with CPU, memory, and credit cost'),
('egress_ip', 'mz_catalog.mz_egress_ips', NULL, 'IP addresses used for outbound connections from Materialize'),
('object_dependency', 'mz_internal.mz_object_dependencies', NULL, 'A dependency edge: one object depends on another'),
('object_global_id', 'mz_internal.mz_object_global_ids', NULL, 'Mapping between CatalogItemId (SQL layer) and GlobalId (runtime layer)'),
('comment', 'mz_internal.mz_comments', NULL, 'A COMMENT ON annotation for a catalog object or column'),
('object_history', 'mz_internal.mz_object_history', NULL, 'Historical record of object creation and drops'),
('object_lifetime', 'mz_internal.mz_object_lifetimes', NULL, 'Computed lifetime span (created_at to dropped_at) for objects'),
('object_fqn', 'mz_internal.mz_object_fully_qualified_names', NULL, 'Fully qualified name (database.schema.name) for objects'),
('continual_task', 'mz_internal.mz_continual_tasks', NULL, 'A continual task definition'),
('replacement', 'mz_internal.mz_replacements', NULL, 'A record of an object replacement (ALTER ... SWAP)'),
('aggregate', 'mz_internal.mz_aggregates', NULL, 'Aggregate function metadata'),
('history_retention', 'mz_internal.mz_history_retention_strategies', NULL, 'History retention strategy for an object'),
('license_key', 'mz_internal.mz_license_keys', NULL, 'License key metadata'),
('replica_status_history', 'mz_internal.mz_cluster_replica_status_history', NULL, 'Historical replica status events (ready, not-ready, etc.)'),
('replica_status', 'mz_internal.mz_cluster_replica_statuses', NULL, 'Current status of each replica'),
('replica_metrics', 'mz_internal.mz_cluster_replica_metrics', NULL, 'CPU and memory metrics per replica'),
('replica_utilization', 'mz_internal.mz_cluster_replica_utilization', NULL, 'Computed utilization metrics per replica'),
('replica_history', 'mz_internal.mz_cluster_replica_history', NULL, 'Historical record of replica creation/drops'),
('replica_name_history', 'mz_internal.mz_cluster_replica_name_history', NULL, 'Historical replica names'),
('cluster_schedule', 'mz_internal.mz_cluster_schedules', NULL, 'Cluster scheduling configuration'),
('cluster_deployment', 'mz_internal.mz_cluster_deployment_lineage', NULL, 'Cluster deployment lineage information'),
('compute_dependency', 'mz_internal.mz_compute_dependencies', NULL, 'Dependency edges within compute dataflows'),
('compute_hydration_time', 'mz_internal.mz_compute_hydration_times', NULL, 'Time to hydrate compute objects'),
('compute_hydration_status', 'mz_internal.mz_compute_operator_hydration_statuses', NULL, 'Hydration status per compute operator'),
('hydration_status', 'mz_internal.mz_hydration_statuses', NULL, 'Overall hydration status per object'),
('compute_hydration_status_view', 'mz_internal.mz_compute_hydration_statuses', NULL, 'Computed hydration status per compute object'),
('frontier', 'mz_internal.mz_frontiers', NULL, 'Current read/write frontiers per object (source)'),
('global_frontier', 'mz_internal.mz_global_frontiers', NULL, 'Aggregated frontiers across all replicas'),
('wallclock_lag_history', 'mz_internal.mz_wallclock_lag_history', NULL, 'Historical wallclock lag per object (source)'),
('wallclock_global_lag', 'mz_internal.mz_wallclock_global_lag', NULL, 'Current wallclock lag aggregated across replicas'),
('wallclock_global_lag_history', 'mz_internal.mz_wallclock_global_lag_history', NULL, 'Historical global wallclock lag'),
('materialization_lag', 'mz_internal.mz_materialization_lag', NULL, 'Lag between a materialization and its inputs'),
('materialization_dep', 'mz_internal.mz_materialization_dependencies', NULL, 'Dependencies between materializations'),
('source_statistics', 'mz_internal.mz_source_statistics', NULL, 'Aggregated source ingestion statistics'),
('source_status', 'mz_internal.mz_source_statuses', NULL, 'Current source status (running, stalled, etc.)'),
('source_status_history', 'mz_internal.mz_source_status_history', NULL, 'Historical source status events'),
('sink_statistics', 'mz_internal.mz_sink_statistics', NULL, 'Aggregated sink export statistics'),
('sink_status', 'mz_internal.mz_sink_statuses', NULL, 'Current sink status'),
('sink_status_history', 'mz_internal.mz_sink_status_history', NULL, 'Historical sink status events'),
('storage_shard', 'mz_internal.mz_storage_shards', NULL, 'Persist shards used by storage objects'),
('storage_usage_by_shard', 'mz_internal.mz_storage_usage_by_shard', NULL, 'Storage usage broken down by shard'),
('kafka_source_table', 'mz_internal.mz_kafka_source_tables', NULL, 'Kafka source table-level details'),
('postgres_source_table', 'mz_internal.mz_postgres_source_tables', NULL, 'Postgres source table-level details'),
('postgres_source', 'mz_internal.mz_postgres_sources', NULL, 'Postgres source-level details'),
('mysql_source_table', 'mz_internal.mz_mysql_source_tables', NULL, 'MySQL source table-level details'),
('sql_server_source_table', 'mz_internal.mz_sql_server_source_tables', NULL, 'SQL Server source table-level details'),
('source_reference', 'mz_internal.mz_source_references', NULL, 'External references tracked by sources'),
('webhook_source', 'mz_internal.mz_webhook_sources', NULL, 'Webhook source configuration'),
('session_history', 'mz_internal.mz_session_history', NULL, 'Historical session connection events'),
('session', 'mz_internal.mz_sessions', NULL, 'Currently active sessions'),
('sql_text', 'mz_internal.mz_sql_text', NULL, 'Raw SQL text of executed statements'),
('recent_sql_text', 'mz_internal.mz_recent_sql_text', NULL, 'Recent SQL text (indexed, last 3 days)'),
('activity_log', 'mz_internal.mz_recent_activity_log', NULL, 'Recent query activity with execution stats'),
('subscription', 'mz_internal.mz_subscriptions', NULL, 'Active SUBSCRIBE operations'),
('statement_lifecycle', 'mz_internal.mz_statement_lifecycle_history', NULL, 'Statement lifecycle events (parse, bind, execute)'),
('network_policy', 'mz_internal.mz_network_policies', NULL, 'Network access policies'),
('network_policy_rule', 'mz_internal.mz_network_policy_rules', NULL, 'Individual rules within a network policy'),
('aws_connection', 'mz_internal.mz_aws_connections', NULL, 'AWS connection configuration details'),
('privatelink_status', 'mz_internal.mz_aws_privatelink_connection_statuses', NULL, 'PrivateLink connection health status'),
('arrangement_size', 'mz_introspection.mz_arrangement_sizes', NULL, 'Aggregated arrangement sizes (records, batches, bytes)'),
('arrangement_sharing', 'mz_introspection.mz_arrangement_sharing', NULL, 'Arrangement sharing between operators'),
('group_size_advice', 'mz_introspection.mz_expected_group_size_advice', NULL, 'Advice on expected group sizes for reduce operators'),
('dataflow', 'mz_introspection.mz_dataflows', NULL, 'Dataflow instances'),
('dataflow_operator', 'mz_introspection.mz_dataflow_operators', NULL, 'Operators within dataflows'),
('dataflow_address', 'mz_introspection.mz_dataflow_addresses', NULL, 'Address (scope path) of dataflow operators'),
('dataflow_channel', 'mz_introspection.mz_dataflow_channels', NULL, 'Communication channels between operators'),
('dataflow_operator_dataflow', 'mz_introspection.mz_dataflow_operator_dataflows', NULL, 'Mapping of operators to their parent dataflow'),
('compute_export', 'mz_introspection.mz_compute_exports', NULL, 'Compute exports (maintained collections)'),
('compute_frontier', 'mz_introspection.mz_compute_frontiers', NULL, 'Per-replica compute frontiers'),
('compute_import_frontier', 'mz_introspection.mz_compute_import_frontiers', NULL, 'Import frontiers for compute dependencies'),
('compute_error_count', 'mz_introspection.mz_compute_error_counts', NULL, 'Error counts per compute collection'),
('lir_mapping', 'mz_introspection.mz_lir_mapping', NULL, 'LIR (low-level IR) to dataflow operator mapping'),
('records_per_dataflow', 'mz_introspection.mz_records_per_dataflow', NULL, 'Record counts aggregated per dataflow'),
('mappable_object', 'mz_introspection.mz_mappable_objects', NULL, 'Objects that can be mapped to dataflow operators'),
('scheduling_elapsed', 'mz_introspection.mz_scheduling_elapsed', NULL, 'CPU time spent per operator'),
('scheduling_parks', 'mz_introspection.mz_scheduling_parks_histogram', NULL, 'Histogram of operator park durations'),
('peek_duration', 'mz_introspection.mz_peek_durations_histogram', NULL, 'Histogram of SELECT query durations'),
('active_peek', 'mz_introspection.mz_active_peeks', NULL, 'Currently executing SELECT queries'),
('message_count', 'mz_introspection.mz_message_counts', NULL, 'Inter-worker message counts'),
('transitive_dependency', 'mz_internal.mz_object_transitive_dependencies', '{"primary_key": ["object_id", "referenced_object_id"]}'::jsonb, 'Transitive closure of object dependencies — all direct and indirect dependencies');
