-- Copyright Materialize, Inc. and contributors. All rights reserved.
--
-- Use of this software is governed by the Business Source License
-- included in the LICENSE file at the root of this repository.
--
-- As of the Change Date specified in that file, in accordance with
-- the Business Source License, use of this software will be governed
-- by the Apache License, Version 2.0.

-- Materialize Catalog Ontology: Link Types

INSERT INTO misc_mz_ontology.link_types (name, source_entity, target_entity, properties, description) VALUES

('in_database', 'schema', 'database', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "database_id", "target_column": "id", "cardinality": "many_to_one", "nullable": true}'),
('in_schema', 'table', 'schema', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "schema_id", "target_column": "id", "cardinality": "many_to_one"}'),
('in_schema', 'source', 'schema', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "schema_id", "target_column": "id", "cardinality": "many_to_one"}'),
('in_schema', 'view', 'schema', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "schema_id", "target_column": "id", "cardinality": "many_to_one"}'),
('in_schema', 'mv', 'schema', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "schema_id", "target_column": "id", "cardinality": "many_to_one"}'),
('in_schema', 'connection', 'schema', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "schema_id", "target_column": "id", "cardinality": "many_to_one"}'),
('in_schema', 'secret', 'schema', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "schema_id", "target_column": "id", "cardinality": "many_to_one"}'),
('in_schema', 'type', 'schema', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "schema_id", "target_column": "id", "cardinality": "many_to_one"}'),
('in_schema', 'function', 'schema', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "schema_id", "target_column": "id", "cardinality": "many_to_one"}'),
('in_schema', 'sink', 'schema', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "schema_id", "target_column": "id", "cardinality": "many_to_one"}'),
('owned_by', 'database', 'role', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "owner_id", "target_column": "id", "cardinality": "many_to_one"}'),
('owned_by', 'schema', 'role', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "owner_id", "target_column": "id", "cardinality": "many_to_one"}'),
('owned_by', 'cluster', 'role', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "owner_id", "target_column": "id", "cardinality": "many_to_one"}'),
('owned_by', 'replica', 'role', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "owner_id", "target_column": "id", "cardinality": "many_to_one"}'),
('owned_by', 'table', 'role', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "owner_id", "target_column": "id", "cardinality": "many_to_one"}'),
('owned_by', 'source', 'role', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "owner_id", "target_column": "id", "cardinality": "many_to_one"}'),
('owned_by', 'view', 'role', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "owner_id", "target_column": "id", "cardinality": "many_to_one"}'),
('owned_by', 'mv', 'role', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "owner_id", "target_column": "id", "cardinality": "many_to_one"}'),
('owned_by', 'index', 'role', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "owner_id", "target_column": "id", "cardinality": "many_to_one"}'),
('owned_by', 'sink', 'role', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "owner_id", "target_column": "id", "cardinality": "many_to_one"}'),
('owned_by', 'connection', 'role', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "owner_id", "target_column": "id", "cardinality": "many_to_one"}'),
('owned_by', 'secret', 'role', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "owner_id", "target_column": "id", "cardinality": "many_to_one"}'),
('owned_by', 'type', 'role', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "owner_id", "target_column": "id", "cardinality": "many_to_one"}'),
('owned_by', 'function', 'role', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "owner_id", "target_column": "id", "cardinality": "many_to_one"}'),
('belongs_to_cluster', 'replica', 'cluster', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "cluster_id", "target_column": "id", "cardinality": "many_to_one"}'),
('runs_on_cluster', 'mv', 'cluster', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "cluster_id", "target_column": "id", "cardinality": "many_to_one"}'),
('runs_on_cluster', 'index', 'cluster', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "cluster_id", "target_column": "id", "cardinality": "many_to_one"}'),
('runs_on_cluster', 'source', 'cluster', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "cluster_id", "target_column": "id", "cardinality": "many_to_one", "nullable": true}'),
('runs_on_cluster', 'sink', 'cluster', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "cluster_id", "target_column": "id", "cardinality": "many_to_one"}'),
('indexes_relation', 'index', 'relation', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "on_id", "target_column": "id", "cardinality": "many_to_one"}'),
('belongs_to_index', 'index_column', 'index', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "index_id", "target_column": "id", "cardinality": "many_to_one"}'),
('belongs_to_relation', 'column', 'object', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "id", "target_column": "id", "cardinality": "many_to_one", "note": "id in mz_columns is the relation ID, not a unique column ID"}'),
('details_of', 'kafka_source', 'source', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "id", "target_column": "id", "cardinality": "one_to_one"}'),
('details_of', 'kafka_sink', 'sink', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "id", "target_column": "id", "cardinality": "one_to_one"}'),
('details_of', 'iceberg_sink', 'sink', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "id", "target_column": "id", "cardinality": "one_to_one"}'),
('details_of', 'kafka_connection', 'connection', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "id", "target_column": "id", "cardinality": "one_to_one"}'),
('details_of', 'ssh_tunnel', 'connection', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "id", "target_column": "id", "cardinality": "one_to_one"}'),
('details_of', 'aws_privatelink', 'connection', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "id", "target_column": "id", "cardinality": "one_to_one"}'),
('uses_connection', 'source', 'connection', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "connection_id", "target_column": "id", "cardinality": "many_to_one", "nullable": true}'),
('created_by_source', 'table', 'source', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "source_id", "target_column": "id", "cardinality": "many_to_one", "nullable": true}'),
('is_subtype_of', 'array_type', 'type', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "id", "target_column": "id", "cardinality": "one_to_one"}'),
('has_element_type', 'array_type', 'type', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "element_id", "target_column": "id", "cardinality": "many_to_one"}'),
('is_subtype_of', 'list_type', 'type', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "id", "target_column": "id", "cardinality": "one_to_one"}'),
('has_element_type', 'list_type', 'type', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "element_id", "target_column": "id", "cardinality": "many_to_one"}'),
('is_subtype_of', 'map_type', 'type', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "id", "target_column": "id", "cardinality": "one_to_one"}'),
('has_key_type', 'map_type', 'type', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "key_id", "target_column": "id", "cardinality": "many_to_one"}'),
('has_value_type', 'map_type', 'type', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "value_id", "target_column": "id", "cardinality": "many_to_one"}'),
('returns_type', 'function', 'type', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "return_type_id", "target_column": "id", "cardinality": "many_to_one", "nullable": true}'),
('member_of_role', 'role_member', 'role', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "role_id", "target_column": "id", "cardinality": "many_to_one"}'),
('has_member', 'role_member', 'role', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "member", "target_column": "id", "cardinality": "many_to_one"}'),
('granted_by', 'role_member', 'role', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "grantor", "target_column": "id", "cardinality": "many_to_one"}'),
('parameter_of', 'role_parameter', 'role', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "role_id", "target_column": "id", "cardinality": "many_to_one"}'),
('default_priv_for_role', 'default_privilege', 'role', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "role_id", "target_column": "id", "cardinality": "many_to_one"}'),
('default_priv_in_database', 'default_privilege', 'database', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "database_id", "target_column": "id", "cardinality": "many_to_one", "nullable": true}'),
('default_priv_in_schema', 'default_privilege', 'schema', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "schema_id", "target_column": "id", "cardinality": "many_to_one", "nullable": true}'),
('storage_usage_of', 'storage_usage', 'object', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "object_id", "target_column": "id", "cardinality": "many_to_one"}'),
('recent_storage_of', 'recent_storage', 'object', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "object_id", "target_column": "id", "cardinality": "one_to_one"}'),
('has_size', 'replica', 'replica_size', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "size", "target_column": "size", "cardinality": "many_to_one", "nullable": true}'),
('has_size', 'cluster', 'replica_size', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "size", "target_column": "size", "cardinality": "many_to_one", "nullable": true}'),
('union_includes', 'relation', 'table', '{}'::jsonb, '{"kind": "union", "discriminator_column": "type", "discriminator_value": "table"}'),
('union_includes', 'relation', 'source', '{}'::jsonb, '{"kind": "union", "discriminator_column": "type", "discriminator_value": "source"}'),
('union_includes', 'relation', 'view', '{}'::jsonb, '{"kind": "union", "discriminator_column": "type", "discriminator_value": "view"}'),
('union_includes', 'relation', 'mv', '{}'::jsonb, '{"kind": "union", "discriminator_column": "type", "discriminator_value": "materialized-view"}'),
('union_includes', 'object', 'relation', '{}'::jsonb, '{"kind": "union", "note": "mz_objects includes all relations plus indexes, connections, secrets, types, functions"}'),
('union_includes', 'object', 'index', '{}'::jsonb, '{"kind": "union", "discriminator_column": "type", "discriminator_value": "index"}'),
('union_includes', 'object', 'connection', '{}'::jsonb, '{"kind": "union", "discriminator_column": "type", "discriminator_value": "connection"}'),
('union_includes', 'object', 'secret', '{}'::jsonb, '{"kind": "union", "discriminator_column": "type", "discriminator_value": "secret"}'),
('maps_to_global_id', 'object', 'object', '{}'::jsonb, '{"kind": "maps_to", "via": "mz_internal.mz_object_global_ids", "from_type": "CatalogItemId", "to_type": "GlobalId", "note": "A CatalogItemId (SQL layer) maps to one or more GlobalIds (runtime layer)."}'),
('depends_on', 'object_dependency', 'object', '{}'::jsonb, '{"source_id_type": "CatalogItemId", "kind": "foreign_key", "source_column": "object_id", "target_column": "id", "cardinality": "many_to_one"}'),
('depended_on_by', 'object_dependency', 'object', '{}'::jsonb, '{"source_id_type": "CatalogItemId", "kind": "foreign_key", "source_column": "referenced_object_id", "target_column": "id", "cardinality": "many_to_one"}'),
('has_global_id', 'object_global_id', 'object', '{}'::jsonb, '{"kind": "maps_to", "source_column": "id", "target_column": "id", "from_type": "CatalogItemId", "to_type": "GlobalId"}'),
('comment_on', 'comment', 'object', '{}'::jsonb, '{"source_id_type": "CatalogItemId", "kind": "foreign_key", "source_column": "id", "target_column": "id", "cardinality": "many_to_one"}'),
('history_of', 'object_history', 'object', '{}'::jsonb, '{"source_id_type": "CatalogItemId", "kind": "foreign_key", "source_column": "id", "target_column": "id", "cardinality": "many_to_one"}'),
('lifetime_of', 'object_lifetime', 'object', '{}'::jsonb, '{"source_id_type": "CatalogItemId", "kind": "foreign_key", "source_column": "id", "target_column": "id", "cardinality": "one_to_one"}'),
('status_of_replica', 'replica_status', 'replica', '{}'::jsonb, '{"source_id_type": "CatalogItemId", "kind": "foreign_key", "source_column": "replica_id", "target_column": "id", "cardinality": "one_to_one"}'),
('status_history_of_replica', 'replica_status_history', 'replica', '{}'::jsonb, '{"source_id_type": "CatalogItemId", "kind": "foreign_key", "source_column": "replica_id", "target_column": "id", "cardinality": "many_to_one"}'),
('metrics_of_replica', 'replica_metrics', 'replica', '{}'::jsonb, '{"source_id_type": "CatalogItemId", "kind": "foreign_key", "source_column": "replica_id", "target_column": "id", "cardinality": "one_to_one"}'),
('utilization_of_replica', 'replica_utilization', 'replica', '{}'::jsonb, '{"source_id_type": "CatalogItemId", "kind": "foreign_key", "source_column": "replica_id", "target_column": "id", "cardinality": "one_to_one"}'),
('compute_depends_on', 'compute_dependency', 'object', '{}'::jsonb, '{"source_id_type": "GlobalId", "requires_mapping": "mz_internal.mz_object_global_ids", "kind": "foreign_key", "source_column": "object_id", "target_column": "id", "cardinality": "many_to_one"}'),
('compute_depended_by', 'compute_dependency', 'object', '{}'::jsonb, '{"source_id_type": "GlobalId", "requires_mapping": "mz_internal.mz_object_global_ids", "kind": "foreign_key", "source_column": "dependency_id", "target_column": "id", "cardinality": "many_to_one"}'),
('hydration_of', 'hydration_status', 'object', '{}'::jsonb, '{"source_id_type": "GlobalId", "requires_mapping": "mz_internal.mz_object_global_ids", "kind": "foreign_key", "source_column": "object_id", "target_column": "id", "cardinality": "one_to_one"}'),
('hydration_on_replica', 'hydration_status', 'replica', '{}'::jsonb, '{"source_id_type": "GlobalId", "kind": "foreign_key", "source_column": "replica_id", "target_column": "id", "cardinality": "many_to_one"}'),
('frontier_of', 'frontier', 'object', '{}'::jsonb, '{"source_id_type": "GlobalId", "requires_mapping": "mz_internal.mz_object_global_ids", "kind": "foreign_key", "source_column": "object_id", "target_column": "id", "cardinality": "many_to_one"}'),
('global_frontier_of', 'global_frontier', 'object', '{}'::jsonb, '{"source_id_type": "GlobalId", "requires_mapping": "mz_internal.mz_object_global_ids", "kind": "foreign_key", "source_column": "object_id", "target_column": "id", "cardinality": "one_to_one"}'),
('measures_lag_of', 'wallclock_lag_history', 'object', '{}'::jsonb, '{"source_id_type": "GlobalId", "requires_mapping": "mz_internal.mz_object_global_ids", "kind": "measures", "source_column": "object_id", "target_column": "id", "metric": "wallclock_lag"}'),
('measures_global_lag_of', 'wallclock_global_lag', 'object', '{}'::jsonb, '{"source_id_type": "GlobalId", "requires_mapping": "mz_internal.mz_object_global_ids", "kind": "measures", "source_column": "object_id", "target_column": "id", "metric": "wallclock_lag_global"}'),
('measures_materialization_lag', 'materialization_lag', 'object', '{}'::jsonb, '{"source_id_type": "CatalogItemId", "kind": "measures", "source_column": "object_id", "target_column": "id", "metric": "materialization_lag"}'),
('materialization_depends_on', 'materialization_dep', 'object', '{}'::jsonb, '{"source_id_type": "CatalogItemId", "kind": "depends_on", "source_column": "object_id", "target_column": "id"}'),
('statistics_of_source', 'source_statistics', 'source', '{}'::jsonb, '{"source_id_type": "CatalogItemId", "kind": "measures", "source_column": "id", "target_column": "id", "metric": "ingestion_statistics"}'),
('status_of_source', 'source_status', 'source', '{}'::jsonb, '{"source_id_type": "CatalogItemId", "kind": "foreign_key", "source_column": "id", "target_column": "id", "cardinality": "one_to_one"}'),
('status_history_of_source', 'source_status_history', 'source', '{}'::jsonb, '{"source_id_type": "CatalogItemId", "kind": "foreign_key", "source_column": "source_id", "target_column": "id", "cardinality": "many_to_one"}'),
('statistics_of_sink', 'sink_statistics', 'sink', '{}'::jsonb, '{"source_id_type": "CatalogItemId", "kind": "measures", "source_column": "id", "target_column": "id", "metric": "export_statistics"}'),
('status_of_sink', 'sink_status', 'sink', '{}'::jsonb, '{"source_id_type": "CatalogItemId", "kind": "foreign_key", "source_column": "id", "target_column": "id", "cardinality": "one_to_one"}'),
('status_history_of_sink', 'sink_status_history', 'sink', '{}'::jsonb, '{"source_id_type": "CatalogItemId", "kind": "foreign_key", "source_column": "sink_id", "target_column": "id", "cardinality": "many_to_one"}'),
('shard_of', 'storage_shard', 'object', '{}'::jsonb, '{"source_id_type": "GlobalId", "requires_mapping": "mz_internal.mz_object_global_ids", "kind": "foreign_key", "source_column": "object_id", "target_column": "id", "cardinality": "many_to_one"}'),
('session_on_cluster', 'activity_log', 'cluster', '{}'::jsonb, '{"source_id_type": "CatalogItemId", "kind": "foreign_key", "source_column": "cluster_id", "target_column": "id", "cardinality": "many_to_one"}'),
('operator_in_dataflow', 'dataflow_operator_dataflow', 'dataflow', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "dataflow_id", "target_column": "id", "cardinality": "many_to_one"}'),
('channel_in_dataflow', 'dataflow_channel', 'dataflow', '{}'::jsonb, '{"kind": "maps_to", "via": "mz_introspection.mz_dataflow_operator_dataflows", "note": "Channels do not have a direct dataflow_id. Use mz_dataflow_addresses to find the parent scope, then correlate with mz_dataflow_operator_dataflows."}'),
('address_of_operator', 'dataflow_address', 'dataflow_operator', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "id", "target_column": "id", "cardinality": "one_to_one"}'),
('export_of', 'compute_export', 'object', '{}'::jsonb, '{"source_id_type": "GlobalId", "requires_mapping": "mz_internal.mz_object_global_ids", "kind": "foreign_key", "source_column": "export_id", "target_column": "id", "cardinality": "many_to_one"}'),
('compute_frontier_of', 'compute_frontier', 'object', '{}'::jsonb, '{"source_id_type": "GlobalId", "requires_mapping": "mz_internal.mz_object_global_ids", "kind": "foreign_key", "source_column": "export_id", "target_column": "id", "cardinality": "many_to_one"}'),
('compute_import_frontier_of', 'compute_import_frontier', 'object', '{}'::jsonb, '{"source_id_type": "GlobalId", "requires_mapping": "mz_internal.mz_object_global_ids", "kind": "foreign_key", "source_column": "export_id", "target_column": "id", "cardinality": "many_to_one"}'),
('elapsed_for_operator', 'scheduling_elapsed', 'dataflow_operator', '{}'::jsonb, '{"kind": "measures", "source_column": "id", "target_column": "id", "metric": "cpu_time_ns", "note": "Both IDs are local uint64 operator IDs within a dataflow, not GlobalIds."}'),
('arrangement_of_operator', 'arrangement_size', 'dataflow_operator', '{}'::jsonb, '{"kind": "measures", "source_column": "operator_id", "target_column": "id", "metric": "arrangement_size", "note": "Both IDs are local uint64 operator IDs within a dataflow, not GlobalIds."}'),
('introspection_uses_global_id', 'compute_export', 'object_global_id', '{}'::jsonb, '{"kind": "maps_to", "note": "mz_introspection tables use GlobalId. To join with mz_catalog tables (which use CatalogItemId), go through mz_internal.mz_object_global_ids."}'),
('transitively_depends_on', 'transitive_dependency', 'object', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "object_id", "target_column": "id", "cardinality": "many_to_one", "source_id_type": "CatalogItemId"}'),
('transitively_depended_on_by', 'transitive_dependency', 'object', '{}'::jsonb, '{"kind": "foreign_key", "source_column": "referenced_object_id", "target_column": "id", "cardinality": "many_to_one", "source_id_type": "CatalogItemId"}');
