-- Copyright Materialize, Inc. and contributors. All rights reserved.
--
-- Use of this software is governed by the Business Source License
-- included in the LICENSE file at the root of this repository.
--
-- As of the Change Date specified in that file, in accordance with
-- the Business Source License, use of this software will be governed
-- by the Apache License, Version 2.0.

-- Materialize Catalog Ontology: Properties

INSERT INTO misc_mz_ontology.properties (entity_type, column_name, semantic_type, description) VALUES

('database', 'id', 'DatabaseId', 'Unique database identifier. PK.'),
('database', 'oid', 'OID', 'PostgreSQL-compatible OID.'),
('database', 'name', NULL, 'The name of the database.'),
('database', 'owner_id', 'RoleId', 'Owner of the database. FK -> mz_roles.id.'),
('database', 'privileges', NULL, 'ACL privileges on the database.'),
('schema', 'id', 'SchemaId', 'Unique schema identifier. PK.'),
('schema', 'oid', 'OID', 'PostgreSQL-compatible OID.'),
('schema', 'database_id', 'DatabaseId', 'Parent database. FK -> mz_databases.id. NULL for system schemas.'),
('schema', 'name', NULL, 'The name of the schema.'),
('schema', 'owner_id', 'RoleId', 'Owner of the schema. FK -> mz_roles.id.'),
('schema', 'privileges', NULL, 'ACL privileges on the schema.'),
('role', 'id', 'RoleId', 'Unique role identifier. PK.'),
('role', 'oid', 'OID', 'PostgreSQL-compatible OID.'),
('role', 'name', NULL, 'The name of the role.'),
('role', 'inherit', NULL, 'Whether the role inherits privileges.'),
('role', 'rolcanlogin', NULL, 'Whether the role can log in.'),
('role', 'rolsuper', NULL, 'Whether the role is a superuser.'),
('cluster', 'id', 'ClusterId', 'Unique cluster identifier. PK.'),
('cluster', 'name', NULL, 'The name of the cluster.'),
('cluster', 'owner_id', 'RoleId', 'Owner of the cluster. FK -> mz_roles.id.'),
('cluster', 'privileges', NULL, 'ACL privileges on the cluster.'),
('cluster', 'managed', NULL, 'Whether this is a managed cluster.'),
('cluster', 'size', NULL, 'Replica size for managed clusters. NULL for unmanaged.'),
('cluster', 'replication_factor', NULL, 'Number of replicas for managed clusters. NULL for unmanaged.'),
('cluster', 'disk', NULL, 'Whether replicas have disk. NULL for unmanaged.'),
('cluster', 'availability_zones', NULL, 'Availability zones for managed clusters.'),
('cluster', 'introspection_debugging', NULL, 'Whether introspection debugging is enabled.'),
('cluster', 'introspection_interval', NULL, 'Interval for introspection data collection.'),
('replica', 'id', 'ReplicaId', 'Unique replica identifier.'),
('replica', 'name', NULL, 'The name of the replica.'),
('replica', 'cluster_id', 'ClusterId', 'Parent cluster. FK -> mz_clusters.id.'),
('replica', 'size', NULL, 'Replica size (e.g., 25cc, 100cc).'),
('replica', 'availability_zone', NULL, 'The AZ where the replica runs.'),
('replica', 'owner_id', 'RoleId', 'Owner of the replica. FK -> mz_roles.id.'),
('replica', 'disk', NULL, 'Whether the replica has local disk.'),
('table', 'id', 'CatalogItemId', 'Unique table identifier. PK.'),
('table', 'oid', 'OID', 'PostgreSQL-compatible OID.'),
('table', 'schema_id', 'SchemaId', 'Parent schema. FK -> mz_schemas.id.'),
('table', 'name', NULL, 'The name of the table.'),
('table', 'owner_id', 'RoleId', 'Owner. FK -> mz_roles.id.'),
('table', 'privileges', NULL, 'ACL privileges.'),
('table', 'create_sql', 'SqlDefinition', 'CREATE TABLE statement.'),
('table', 'redacted_create_sql', 'RedactedSqlDefinition', 'Redacted CREATE TABLE statement.'),
('table', 'source_id', 'CatalogItemId', 'Source that created this table (e.g., Postgres replication). FK -> mz_sources.id. NULL for user-created tables.'),
('source', 'id', 'CatalogItemId', 'Unique source identifier. PK.'),
('source', 'oid', 'OID', 'PostgreSQL-compatible OID.'),
('source', 'schema_id', 'SchemaId', 'Parent schema. FK -> mz_schemas.id.'),
('source', 'name', NULL, 'The name of the source.'),
('source', 'type', 'SourceType', 'Source type: kafka, postgres, mysql, load-generator, progress, subsource.'),
('source', 'connection_id', 'CatalogItemId', 'Connection used by this source. FK -> mz_connections.id.'),
('source', 'size', NULL, 'Deprecated. Source size.'),
('source', 'envelope_type', NULL, 'Kafka envelope: none, upsert, debezium. NULL for non-Kafka.'),
('source', 'key_format', NULL, 'Kafka key format: avro, json, bytes, text. NULL for non-Kafka.'),
('source', 'value_format', NULL, 'Kafka value format: avro, json, bytes, text. NULL for non-Kafka.'),
('source', 'cluster_id', 'ClusterId', 'Cluster running this source. FK -> mz_clusters.id. NULL for subsources.'),
('source', 'owner_id', 'RoleId', 'Owner. FK -> mz_roles.id.'),
('source', 'privileges', NULL, 'ACL privileges.'),
('source', 'create_sql', 'SqlDefinition', 'CREATE SOURCE statement.'),
('source', 'redacted_create_sql', 'RedactedSqlDefinition', 'Redacted CREATE SOURCE statement.'),
('view', 'id', 'CatalogItemId', 'Unique view identifier. PK.'),
('view', 'oid', 'OID', 'PostgreSQL-compatible OID.'),
('view', 'schema_id', 'SchemaId', 'Parent schema. FK -> mz_schemas.id.'),
('view', 'name', NULL, 'The name of the view.'),
('view', 'definition', 'SqlDefinition', 'The SELECT query defining the view.'),
('view', 'owner_id', 'RoleId', 'Owner. FK -> mz_roles.id.'),
('view', 'privileges', NULL, 'ACL privileges.'),
('view', 'create_sql', 'SqlDefinition', 'CREATE VIEW statement.'),
('view', 'redacted_create_sql', 'RedactedSqlDefinition', 'Redacted CREATE VIEW statement.'),
('mv', 'id', 'CatalogItemId', 'Unique MV identifier. PK.'),
('mv', 'oid', 'OID', 'PostgreSQL-compatible OID.'),
('mv', 'schema_id', 'SchemaId', 'Parent schema. FK -> mz_schemas.id.'),
('mv', 'name', NULL, 'The name of the materialized view.'),
('mv', 'cluster_id', 'ClusterId', 'Cluster maintaining this MV. FK -> mz_clusters.id.'),
('mv', 'definition', 'SqlDefinition', 'The SELECT query defining the MV.'),
('mv', 'owner_id', 'RoleId', 'Owner. FK -> mz_roles.id.'),
('mv', 'privileges', NULL, 'ACL privileges.'),
('mv', 'create_sql', 'SqlDefinition', 'CREATE MATERIALIZED VIEW statement.'),
('mv', 'redacted_create_sql', 'RedactedSqlDefinition', 'Redacted CREATE MATERIALIZED VIEW statement.'),
('index', 'id', 'CatalogItemId', 'Unique index identifier. PK.'),
('index', 'oid', 'OID', 'PostgreSQL-compatible OID.'),
('index', 'name', NULL, 'The name of the index.'),
('index', 'on_id', 'CatalogItemId', 'The relation this index is built on. FK -> any relation.'),
('index', 'cluster_id', 'ClusterId', 'Cluster maintaining this index. FK -> mz_clusters.id.'),
('index', 'owner_id', 'RoleId', 'Owner. FK -> mz_roles.id.'),
('index', 'create_sql', 'SqlDefinition', 'CREATE INDEX statement.'),
('index', 'redacted_create_sql', 'RedactedSqlDefinition', 'Redacted CREATE INDEX statement.'),
('sink', 'id', 'CatalogItemId', 'Unique sink identifier. PK.'),
('sink', 'oid', 'OID', 'PostgreSQL-compatible OID.'),
('sink', 'schema_id', 'SchemaId', 'Parent schema. FK -> mz_schemas.id.'),
('sink', 'name', NULL, 'The name of the sink.'),
('sink', 'type', NULL, 'Sink type: kafka.'),
('sink', 'connection_id', 'CatalogItemId', 'Connection used by this sink. FK -> mz_connections.id.'),
('sink', 'size', NULL, 'Sink size.'),
('sink', 'envelope_type', NULL, 'Sink envelope: upsert, debezium.'),
('sink', 'format', NULL, 'Deprecated. Kafka message format.'),
('sink', 'key_format', NULL, 'Kafka key format.'),
('sink', 'value_format', NULL, 'Kafka value format.'),
('sink', 'cluster_id', 'ClusterId', 'Cluster running this sink. FK -> mz_clusters.id.'),
('sink', 'owner_id', 'RoleId', 'Owner. FK -> mz_roles.id.'),
('sink', 'create_sql', 'SqlDefinition', 'CREATE SINK statement.'),
('sink', 'redacted_create_sql', 'RedactedSqlDefinition', 'Redacted CREATE SINK statement.'),
('connection', 'id', 'CatalogItemId', 'Unique connection identifier. PK.'),
('connection', 'oid', 'OID', 'PostgreSQL-compatible OID.'),
('connection', 'schema_id', 'SchemaId', 'Parent schema. FK -> mz_schemas.id.'),
('connection', 'name', NULL, 'The name of the connection.'),
('connection', 'type', 'ConnectionType', 'Connection type: kafka, postgres, ssh-tunnel, etc.'),
('connection', 'owner_id', 'RoleId', 'Owner. FK -> mz_roles.id.'),
('connection', 'privileges', NULL, 'ACL privileges.'),
('connection', 'create_sql', 'SqlDefinition', 'CREATE CONNECTION statement.'),
('connection', 'redacted_create_sql', 'RedactedSqlDefinition', 'Redacted CREATE CONNECTION statement.'),
('secret', 'id', 'CatalogItemId', 'Unique secret identifier.'),
('secret', 'oid', 'OID', 'PostgreSQL-compatible OID.'),
('secret', 'schema_id', 'SchemaId', 'Parent schema. FK -> mz_schemas.id.'),
('secret', 'name', NULL, 'The name of the secret.'),
('secret', 'owner_id', 'RoleId', 'Owner. FK -> mz_roles.id.'),
('secret', 'privileges', NULL, 'ACL privileges.'),
('type', 'id', 'CatalogItemId', 'Unique type identifier. PK.'),
('type', 'oid', 'OID', 'PostgreSQL-compatible OID.'),
('type', 'schema_id', 'SchemaId', 'Parent schema. FK -> mz_schemas.id.'),
('type', 'name', NULL, 'The name of the type.'),
('type', 'category', NULL, 'Type category.'),
('type', 'owner_id', 'RoleId', 'Owner. FK -> mz_roles.id.'),
('type', 'privileges', NULL, 'ACL privileges.'),
('type', 'create_sql', 'SqlDefinition', 'CREATE TYPE statement.'),
('type', 'redacted_create_sql', 'RedactedSqlDefinition', 'Redacted CREATE TYPE statement.'),
('array_type', 'id', 'CatalogItemId', 'The type ID. FK -> mz_types.id.'),
('array_type', 'element_id', 'CatalogItemId', 'Element type. FK -> mz_types.id.'),
('list_type', 'id', 'CatalogItemId', 'The type ID. FK -> mz_types.id.'),
('list_type', 'element_id', 'CatalogItemId', 'Element type. FK -> mz_types.id.'),
('list_type', 'element_modifiers', NULL, 'Element type modifiers.'),
('map_type', 'id', 'CatalogItemId', 'The type ID. FK -> mz_types.id.'),
('map_type', 'key_id', 'CatalogItemId', 'Key type. FK -> mz_types.id.'),
('map_type', 'value_id', 'CatalogItemId', 'Value type. FK -> mz_types.id.'),
('map_type', 'key_modifiers', NULL, 'Key type modifiers.'),
('map_type', 'value_modifiers', NULL, 'Value type modifiers.'),
('base_type', 'id', 'CatalogItemId', 'The type ID. FK -> mz_types.id.'),
('pseudo_type', 'id', 'CatalogItemId', 'The type ID. FK -> mz_types.id.'),
('function', 'id', 'CatalogItemId', 'Unique function identifier.'),
('function', 'oid', 'OID', 'PostgreSQL-compatible OID.'),
('function', 'schema_id', 'SchemaId', 'Parent schema. FK -> mz_schemas.id.'),
('function', 'name', NULL, 'The name of the function.'),
('function', 'argument_type_ids', NULL, 'Array of argument type IDs. Each refers to mz_types.id.'),
('function', 'variadic_argument_type_id', 'CatalogItemId', 'Variadic argument type. FK -> mz_types.id.'),
('function', 'return_type_id', 'CatalogItemId', 'Return type. FK -> mz_types.id. NULL for void.'),
('function', 'returns_set', NULL, 'Whether this is a table function.'),
('function', 'owner_id', 'RoleId', 'Owner. FK -> mz_roles.id.'),
('operator', 'oid', 'OID', 'PostgreSQL-compatible OID.'),
('operator', 'name', NULL, 'Operator name.'),
('operator', 'argument_type_ids', NULL, 'Array of argument type IDs.'),
('operator', 'return_type_id', 'CatalogItemId', 'Return type. FK -> mz_types.id.'),
('column', 'id', 'CatalogItemId', 'The relation this column belongs to. FK -> any relation.'),
('column', 'name', NULL, 'Column name.'),
('column', 'position', NULL, '1-indexed position in the relation.'),
('column', 'nullable', NULL, 'Whether the column can be NULL.'),
('column', 'type', NULL, 'SQL data type name.'),
('column', 'default', NULL, 'Default expression.'),
('column', 'type_oid', 'OID', 'OID of the column type. FK -> mz_types.oid.'),
('column', 'type_mod', NULL, 'Packed type modifier.'),
('index_column', 'index_id', 'CatalogItemId', 'Parent index. FK -> mz_indexes.id.'),
('index_column', 'index_position', NULL, '1-indexed position within the index.'),
('index_column', 'on_position', NULL, 'Position in the indexed relation. NULL for expression columns.'),
('index_column', 'on_expression', NULL, 'SQL expression for computed index columns.'),
('index_column', 'nullable', NULL, 'Whether this index column can be NULL.'),
('role_member', 'role_id', 'RoleId', 'The role being granted membership in. FK -> mz_roles.id.'),
('role_member', 'member', 'RoleId', 'The role that is a member. FK -> mz_roles.id.'),
('role_member', 'grantor', 'RoleId', 'The role that granted membership. FK -> mz_roles.id.'),
('role_parameter', 'role_id', 'RoleId', 'The role. FK -> mz_roles.id.'),
('role_parameter', 'parameter_name', NULL, 'Configuration parameter name.'),
('role_parameter', 'parameter_value', NULL, 'Default value for this role.'),
('default_privilege', 'role_id', 'RoleId', 'Creator role. FK -> mz_roles.id. ''p'' = PUBLIC.'),
('default_privilege', 'database_id', 'DatabaseId', 'Scope database. FK -> mz_databases.id. NULL = global.'),
('default_privilege', 'schema_id', 'SchemaId', 'Scope schema. FK -> mz_schemas.id. NULL = database-wide.'),
('default_privilege', 'object_type', 'ObjectType', 'Type of object this rule applies to.'),
('default_privilege', 'grantee', 'RoleId', 'Role receiving privileges. ''p'' = PUBLIC.'),
('default_privilege', 'privileges', NULL, 'Set of privileges to grant.'),
('system_privilege', 'privileges', NULL, 'System-level privilege grant.'),
('kafka_connection', 'id', 'CatalogItemId', 'Connection ID. FK -> mz_connections.id.'),
('kafka_connection', 'brokers', NULL, 'Kafka broker addresses.'),
('kafka_connection', 'sink_progress_topic', NULL, 'Kafka topic for sink progress tracking.'),
('ssh_tunnel', 'id', 'CatalogItemId', 'Connection ID. FK -> mz_connections.id.'),
('ssh_tunnel', 'public_key_1', NULL, 'First SSH public key.'),
('ssh_tunnel', 'public_key_2', NULL, 'Second SSH public key.'),
('aws_privatelink', 'id', 'CatalogItemId', 'Connection ID. FK -> mz_connections.id.'),
('aws_privatelink', 'principal', NULL, 'AWS Principal for VPC endpoint.'),
('kafka_source', 'id', 'CatalogItemId', 'Source ID. FK -> mz_sources.id.'),
('kafka_source', 'group_id_prefix', NULL, 'Kafka consumer group ID prefix.'),
('kafka_source', 'topic', NULL, 'Kafka topic name.'),
('kafka_sink', 'id', 'CatalogItemId', 'Sink ID. FK -> mz_sinks.id.'),
('kafka_sink', 'topic', NULL, 'Kafka topic name.'),
('iceberg_sink', 'id', 'CatalogItemId', 'Sink ID. FK -> mz_sinks.id.'),
('iceberg_sink', 'namespace', NULL, 'Iceberg table namespace.'),
('iceberg_sink', 'table', NULL, 'Iceberg table name.'),
('audit_event', 'id', NULL, 'Monotonically increasing event ID. PK.'),
('audit_event', 'event_type', NULL, 'Event type: create, drop, alter.'),
('audit_event', 'object_type', 'ObjectType', 'Type of affected object.'),
('audit_event', 'details', NULL, 'JSON details varying by event/object type.'),
('audit_event', 'user', NULL, 'User who triggered the event. NULL if system.'),
('audit_event', 'occurred_at', 'WallclockTimestamp', 'When the event occurred.'),
('replica_size', 'size', NULL, 'Human-readable size name (e.g., 25cc).'),
('replica_size', 'processes', NULL, 'Number of processes.'),
('replica_size', 'workers', NULL, 'Timely Dataflow workers per process.'),
('replica_size', 'cpu_nano_cores', NULL, 'CPU allocation per process in nano-cores.'),
('replica_size', 'memory_bytes', 'ByteCount', 'RAM allocation per process.'),
('replica_size', 'disk_bytes', 'ByteCount', 'Disk allocation per process.'),
('replica_size', 'credits_per_hour', 'CreditRate', 'Compute credits consumed per hour.'),
('egress_ip', 'egress_ip', NULL, 'Start of the IP range.'),
('egress_ip', 'prefix_length', NULL, 'CIDR prefix length.'),
('egress_ip', 'cidr', NULL, 'CIDR notation.'),
('relation', 'id', 'CatalogItemId', 'Relation ID.'),
('relation', 'oid', 'OID', 'PostgreSQL-compatible OID.'),
('relation', 'schema_id', 'SchemaId', 'Parent schema. FK -> mz_schemas.id.'),
('relation', 'name', NULL, 'Relation name.'),
('relation', 'type', 'ObjectType', 'Relation type: table, source, view, materialized-view.'),
('relation', 'owner_id', 'RoleId', 'Owner. FK -> mz_roles.id.'),
('relation', 'cluster_id', 'ClusterId', 'Cluster. FK -> mz_clusters.id. NULL for views/tables.'),
('relation', 'privileges', NULL, 'ACL privileges.'),
('object', 'id', 'CatalogItemId', 'Object ID.'),
('object', 'oid', 'OID', 'PostgreSQL-compatible OID.'),
('object', 'schema_id', 'SchemaId', 'Parent schema. FK -> mz_schemas.id.'),
('object', 'name', NULL, 'Object name.'),
('object', 'type', 'ObjectType', 'Object type: table, source, view, materialized-view, sink, index, connection, secret, type, function.'),
('object', 'owner_id', 'RoleId', 'Owner. FK -> mz_roles.id.'),
('object', 'cluster_id', 'ClusterId', 'Cluster. FK -> mz_clusters.id. NULL for non-cluster objects.'),
('object', 'privileges', NULL, 'ACL privileges.'),
('storage_usage', 'object_id', 'CatalogItemId', 'Object being measured. FK -> mz_objects.id.'),
('storage_usage', 'size_bytes', 'ByteCount', 'Storage bytes used.'),
('storage_usage', 'collection_timestamp', 'WallclockTimestamp', 'When usage was assessed.'),
('recent_storage', 'object_id', 'CatalogItemId', 'Object being measured. FK -> mz_objects.id.'),
('recent_storage', 'size_bytes', 'ByteCount', 'Most recent storage bytes used.'),
('object_dependency', 'object_id', 'CatalogItemId', 'The dependent object.'),
('object_dependency', 'referenced_object_id', 'CatalogItemId', 'The object being depended on.'),
('object_global_id', 'id', 'CatalogItemId', 'SQL-layer catalog item ID.'),
('object_global_id', 'global_id', 'GlobalId', 'Runtime global ID.'),
('comment', 'id', 'CatalogItemId', 'The object being commented on.'),
('object_history', 'id', 'CatalogItemId', 'The object.'),
('object_lifetime', 'id', 'CatalogItemId', 'The object.'),
('replica_status', 'replica_id', 'ReplicaId', 'The replica.'),
('replica_status_history', 'replica_id', 'ReplicaId', 'The replica.'),
('replica_metrics', 'replica_id', 'ReplicaId', 'The replica.'),
('replica_utilization', 'replica_id', 'ReplicaId', 'The replica.'),
('frontier', 'object_id', 'GlobalId', 'The object. Uses GlobalId, not CatalogItemId.'),
('frontier', 'read_frontier', 'MzTimestamp', 'The earliest timestamp at which the output is still readable.'),
('frontier', 'write_frontier', 'MzTimestamp', 'The next timestamp at which the output may change.'),
('global_frontier', 'object_id', 'GlobalId', 'The object. Uses GlobalId.'),
('wallclock_lag_history', 'object_id', 'GlobalId', 'The object. Uses GlobalId, not CatalogItemId.'),
('wallclock_lag_history', 'replica_id', 'ReplicaId', 'The replica.'),
('wallclock_lag_history', 'lag', NULL, 'The amount of time the objects write frontier lags behind wallclock time.'),
('wallclock_lag_history', 'occurred_at', 'WallclockTimestamp', 'Wall-clock timestamp of the observation.'),
('wallclock_global_lag', 'object_id', 'GlobalId', 'The object. Uses GlobalId.'),
('wallclock_global_lag', 'lag', NULL, 'The amount of time the objects write frontier lags behind wallclock time.'),
('wallclock_global_lag_history', 'object_id', 'GlobalId', 'The object. Uses GlobalId.'),
('wallclock_global_lag_history', 'lag', NULL, 'The minimum wallclock lag observed during the minute.'),
('wallclock_global_lag_history', 'occurred_at', 'WallclockTimestamp', 'The minute-aligned timestamp of the observation.'),
('materialization_lag', 'object_id', 'CatalogItemId', 'The materialization. Uses CatalogItemId.'),
('materialization_lag', 'slowest_local_input_id', 'CatalogItemId', 'Slowest direct input.'),
('materialization_lag', 'slowest_global_input_id', 'CatalogItemId', 'Slowest root input.'),
('materialization_lag', 'local_lag', NULL, 'The amount of time the materialization lags behind its direct inputs.'),
('materialization_lag', 'global_lag', NULL, 'The amount of time the materialization lags behind its root inputs (sources and tables).'),
('materialization_dep', 'object_id', 'CatalogItemId', 'The materialization.'),
('materialization_dep', 'dependency_id', 'CatalogItemId', 'The dependency.'),
('hydration_status', 'object_id', 'GlobalId', 'The object. Uses GlobalId.'),
('hydration_status', 'replica_id', 'ReplicaId', 'The replica.'),
('hydration_status', 'hydrated', NULL, 'Whether the object is hydrated on the replica.'),
('compute_hydration_status_view', 'object_id', 'GlobalId', 'The compute object.'),
('compute_hydration_status_view', 'replica_id', 'ReplicaId', 'The replica.'),
('compute_hydration_status_view', 'hydrated', NULL, 'Whether the compute object is hydrated.'),
('compute_hydration_status_view', 'hydration_time', NULL, 'Time it took to hydrate.'),
('compute_dependency', 'object_id', 'GlobalId', 'The compute object. Uses GlobalId.'),
('compute_dependency', 'dependency_id', 'GlobalId', 'The dependency. Uses GlobalId.'),
('source_statistics', 'id', 'CatalogItemId', 'The source.'),
('source_statistics', 'replica_id', 'ReplicaId', 'The replica running the source.'),
('source_statistics', 'messages_received', 'RecordCount', 'Messages received from external system.'),
('source_statistics', 'bytes_received', 'ByteCount', 'Bytes read from external system.'),
('source_statistics', 'updates_staged', 'RecordCount', 'Updates written but not yet committed.'),
('source_statistics', 'updates_committed', 'RecordCount', 'Updates committed to storage layer.'),
('source_statistics', 'records_indexed', 'RecordCount', 'Records in the source envelope state index.'),
('source_statistics', 'bytes_indexed', 'ByteCount', 'Bytes in the source internal index.'),
('source_statistics', 'rehydration_latency', NULL, 'Time to rehydrate internal index after restart.'),
('source_statistics', 'snapshot_records_known', 'RecordCount', 'Total records in the source snapshot.'),
('source_statistics', 'snapshot_records_staged', 'RecordCount', 'Snapshot records read so far.'),
('source_statistics', 'snapshot_committed', NULL, 'Whether initial snapshot is committed.'),
('source_statistics', 'offset_known', NULL, 'Offset of most recent upstream data known.'),
('source_statistics', 'offset_committed', NULL, 'Offset of data durably ingested.'),
('source_status', 'id', 'CatalogItemId', 'The source.'),
('source_status', 'name', NULL, 'The name of the source.'),
('source_status', 'type', 'SourceType', 'The type of the source.'),
('source_status', 'last_status_change_at', 'WallclockTimestamp', 'When the status last changed.'),
('source_status', 'status', NULL, 'The status: created, starting, running, paused, stalled, failed, or dropped.'),
('source_status', 'error', NULL, 'Error message if in error state.'),
('source_status', 'details', NULL, 'Additional metadata. May contain a hint field.'),
('source_status_history', 'source_id', 'CatalogItemId', 'The source.'),
('source_status_history', 'occurred_at', 'WallclockTimestamp', 'When the status change occurred.'),
('source_status_history', 'status', NULL, 'The status: created, starting, running, paused, stalled, failed, or dropped.'),
('source_status_history', 'error', NULL, 'Error message if in error state.'),
('source_status_history', 'details', NULL, 'Additional metadata.'),
('source_status_history', 'replica_id', 'ReplicaId', 'The replica running this source instance.'),
('sink_statistics', 'id', 'CatalogItemId', 'The sink.'),
('sink_statistics', 'replica_id', 'ReplicaId', 'The replica running the sink.'),
('sink_statistics', 'messages_staged', 'RecordCount', 'Messages staged but possibly not committed.'),
('sink_statistics', 'messages_committed', 'RecordCount', 'Messages committed to the sink.'),
('sink_statistics', 'bytes_staged', 'ByteCount', 'Bytes staged but possibly not committed.'),
('sink_statistics', 'bytes_committed', 'ByteCount', 'Bytes committed to the sink.'),
('sink_status', 'id', 'CatalogItemId', 'The sink.'),
('sink_status', 'name', NULL, 'The name of the sink.'),
('sink_status', 'type', NULL, 'The type of the sink.'),
('sink_status', 'last_status_change_at', 'WallclockTimestamp', 'When the status last changed.'),
('sink_status', 'status', NULL, 'The status: created, starting, running, stalled, failed, or dropped.'),
('sink_status', 'error', NULL, 'Error message if in error state.'),
('sink_status', 'details', NULL, 'Additional metadata.'),
('sink_status_history', 'sink_id', 'CatalogItemId', 'The sink.'),
('sink_status_history', 'occurred_at', 'WallclockTimestamp', 'When the status change occurred.'),
('sink_status_history', 'status', NULL, 'The status: created, starting, running, stalled, failed, or dropped.'),
('sink_status_history', 'error', NULL, 'Error message if in error state.'),
('sink_status_history', 'details', NULL, 'Additional metadata.'),
('sink_status_history', 'replica_id', 'ReplicaId', 'The replica running this sink instance.'),
('storage_shard', 'object_id', 'GlobalId', 'The object. Uses GlobalId.'),
('storage_shard', 'shard_id', 'ShardId', 'The persist shard ID.'),
('storage_usage_by_shard', 'id', NULL, 'Row ID.'),
('storage_usage_by_shard', 'shard_id', 'ShardId', 'The persist shard ID.'),
('storage_usage_by_shard', 'size_bytes', 'ByteCount', 'Storage bytes used by this shard.'),
('storage_usage_by_shard', 'collection_timestamp', 'WallclockTimestamp', 'When usage was assessed.'),
('comment', 'object_type', 'ObjectType', 'The type of object the comment is on.'),
('comment', 'object_sub_id', NULL, 'For column comments, the column number. NULL otherwise.'),
('comment', 'comment', NULL, 'The comment text.'),
('session_history', 'session_id', NULL, 'Globally unique session ID.'),
('session_history', 'connected_at', 'WallclockTimestamp', 'When the session was established.'),
('session_history', 'initial_application_name', NULL, 'The application_name at connection time.'),
('session_history', 'authenticated_user', NULL, 'The user the session was established for.'),
('activity_log', 'execution_id', NULL, 'Unique ID per executed statement.'),
('activity_log', 'sample_rate', NULL, 'The rate at which the statement was sampled.'),
('activity_log', 'cluster_id', 'ClusterId', 'The cluster the query ran on.'),
('activity_log', 'application_name', NULL, 'The application_name at execution time.'),
('activity_log', 'cluster_name', NULL, 'The cluster name at execution time.'),
('activity_log', 'database_name', NULL, 'The database at execution time.'),
('activity_log', 'search_path', NULL, 'The search_path at execution time.'),
('activity_log', 'transaction_isolation', NULL, 'The transaction isolation level.'),
('activity_log', 'execution_timestamp', 'MzTimestamp', 'The logical timestamp chosen for execution.'),
('activity_log', 'transient_index_id', 'GlobalId', 'Transient index used for fast-path peeks.'),
('activity_log', 'params', NULL, 'Bound parameter values for prepared statements.'),
('activity_log', 'mz_version', NULL, 'The Materialize version that executed this statement.'),
('activity_log', 'began_at', 'WallclockTimestamp', 'When the statement began executing.'),
('activity_log', 'finished_at', 'WallclockTimestamp', 'When the statement finished executing.'),
('activity_log', 'finished_status', NULL, 'Final status: success, canceled, error, or aborted.'),
('activity_log', 'error_message', NULL, 'Error message if the statement failed.'),
('activity_log', 'result_size', 'ByteCount', 'Size in bytes of the result.'),
('activity_log', 'rows_returned', 'RecordCount', 'Number of rows returned.'),
('activity_log', 'execution_strategy', NULL, 'For SELECTs: constant, fast-path, or standard.'),
('activity_log', 'transaction_id', NULL, 'Transaction ID for the statement.'),
('activity_log', 'prepared_statement_id', NULL, 'UUID of the prepared statement.'),
('activity_log', 'sql_hash', NULL, 'Hash of the SQL text.'),
('activity_log', 'prepared_statement_name', NULL, 'Name of the prepared statement (empty string if unnamed).'),
('activity_log', 'session_id', NULL, 'The session ID. Corresponds to mz_sessions.id.'),
('activity_log', 'prepared_at', 'WallclockTimestamp', 'When the statement was prepared.'),
('activity_log', 'statement_type', NULL, 'Type of statement: select, insert, etc.'),
('activity_log', 'throttled_count', NULL, 'Number of times this statement was throttled before being logged.'),
('activity_log', 'connected_at', 'WallclockTimestamp', 'When the session was established.'),
('activity_log', 'initial_application_name', NULL, 'The application_name at session connection time.'),
('activity_log', 'authenticated_user', NULL, 'The user for the session.'),
('activity_log', 'sql', 'SqlDefinition', 'The SQL text of the statement.'),
('arrangement_size', 'operator_id', NULL, 'The operator (local uint64 ID within a dataflow, not a GlobalId).'),
('arrangement_size', 'records', 'RecordCount', 'Number of records in the arrangement.'),
('arrangement_size', 'batches', NULL, 'Number of batches in the arrangement.'),
('arrangement_size', 'size', 'ByteCount', 'Utilized size in bytes.'),
('arrangement_size', 'capacity', 'ByteCount', 'Capacity in bytes (can be larger than size).'),
('arrangement_size', 'allocations', NULL, 'Number of separate memory allocations.'),
('scheduling_elapsed', 'id', NULL, 'The operator (local uint64 ID within a dataflow, not a GlobalId).'),
('scheduling_elapsed', 'elapsed_ns', NULL, 'Total elapsed time in the operator in nanoseconds.'),
('dataflow', 'id', NULL, 'The dataflow ID (local uint64, not a GlobalId).'),
('dataflow', 'name', NULL, 'The internal name of the dataflow.'),
('dataflow_operator', 'id', NULL, 'The operator ID (local uint64, not a GlobalId).'),
('dataflow_operator', 'name', NULL, 'The internal name of the operator.'),
('compute_export', 'export_id', 'GlobalId', 'The exported collection. Uses GlobalId.'),
('compute_export', 'dataflow_id', NULL, 'The parent dataflow (local uint64 ID, not a GlobalId). Corresponds to mz_dataflows.id.'),
('compute_frontier', 'export_id', 'GlobalId', 'The exported collection. Uses GlobalId.'),
('compute_frontier', 'time', 'MzTimestamp', 'The next timestamp at which the output may change.'),
('compute_import_frontier', 'export_id', 'GlobalId', 'The exported collection. Uses GlobalId.'),
('transitive_dependency', 'object_id', 'CatalogItemId', 'The dependent object.'),
('transitive_dependency', 'referenced_object_id', 'CatalogItemId', 'The object being depended on (directly or indirectly).'),
('replica_status', 'process_id', NULL, 'The ID of the process within the replica.'),
('replica_status', 'status', NULL, 'The status of the replica: online or offline.'),
('replica_status', 'reason', NULL, 'If offline, the reason (e.g., oom-killed).'),
('replica_status', 'updated_at', 'WallclockTimestamp', 'When the status was last updated.'),
('replica_metrics', 'process_id', NULL, 'The ID of a process within the replica.'),
('replica_metrics', 'cpu_nano_cores', NULL, 'Approximate CPU usage in billionths of a vCPU core.'),
('replica_metrics', 'memory_bytes', 'ByteCount', 'Approximate RAM usage in bytes.'),
('replica_metrics', 'disk_bytes', 'ByteCount', 'Approximate disk usage in bytes.'),
('replica_metrics', 'heap_bytes', 'ByteCount', 'Approximate heap (RAM + swap) usage in bytes.'),
('replica_metrics', 'heap_limit', 'ByteCount', 'Available heap (RAM + swap) space in bytes.'),
('replica_utilization', 'process_id', NULL, 'The ID of a process within the replica.'),
('replica_utilization', 'cpu_percent', NULL, 'Approximate CPU usage as percent of allocation.'),
('replica_utilization', 'memory_percent', NULL, 'Approximate RAM usage as percent of allocation.'),
('replica_utilization', 'disk_percent', NULL, 'Approximate disk usage as percent of allocation.'),
('replica_utilization', 'heap_percent', NULL, 'Approximate heap usage as percent of allocation.');
