\c benchmark
ALTER TABLE cpu REPLICA IDENTITY NOTHING;
ALTER TABLE tags REPLICA IDENTITY NOTHING;
TRUNCATE TABLE cpu;
TRUNCATE TABLE tags;
ALTER TABLE cpu REPLICA IDENTITY FULL;
ALTER TABLE tags REPLICA IDENTITY FULL;
CREATE PUBLICATION mz_source FOR TABLE cpu, tags;
