// Copyright Materialize, Inc. and contributors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License in the LICENSE file at the
// root of this repository, or online at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Utilities to efficiently store data indexed by an advancing frontier.
//!
//! [`BucketChain`] partitions a timestamp domain into a chain of geometrically
//! sized tiles relative to a monotonically advancing lower-bound frontier:
//! small tiles near the frontier (so peeling is cheap) and exponentially
//! larger tiles further out (so storing future data is cheap). Operations are
//! amortized logarithmic in the number of outstanding timestamps under
//! wall-clock-like frontier advance.
//!
//! # 1D specialization
//!
//! The current implementation is specialized to timestamp domains whose
//! down-set lattice is itself totally ordered and admits a power-of-two
//! scalar measure — i.e., totally-ordered timestamps with the natural length
//! measure on intervals. Wall-clock millisecond timestamps satisfy this; the
//! amortization argument relies on (a) a metric in which tile sizes are
//! denominated and (b) a bounded rate at which the frontier advances through
//! that metric.
//!
//! The [`Frontier`] trait names the lattice primitives the chain consumes:
//! [`Frontier::covers`] tests whether a point lies in the down-set generated
//! by a frontier, and [`Frontier::step_by`] advances a frontier by a
//! power-of-two amount of measure (used to size and bisect tiles). For
//! totally-ordered point types, a frontier is a singleton antichain and the
//! trait is implemented directly on the point: `covers(f, p) ≡ p < f` and
//! `step_by(f, k) ≡ f + 2^k`.
//!
//! # Generalization
//!
//! Conceptually, a frontier is an element of the down-set lattice `L(P)` of an
//! underlying partial order `P` (equivalently, by Birkhoff, an antichain in
//! `P`), and the amortized analysis extends to any `L(P)` carrying an
//! efficiently-computable measure on which the frontier advances at bounded
//! rate. Realizing that generalization requires replacing the `BTreeMap`
//! storage with a measure-balanced tree and computing the measure of
//! tile-minus-down-set as the frontier crosses tiles — straightforward for
//! products of total orders, hard for arbitrary posets. The trait surface
//! here is named for the general framing but only the 1D specialization is
//! wired up.

use std::collections::BTreeMap;

use mz_ore::cast::CastFrom;
use timely::progress::Timestamp;
use timely::progress::frontier::AntichainRef;

/// A frontier in the down-set lattice of a timestamp domain.
///
/// In the current 1D specialization, a value `f: Self` represents the singleton
/// antichain `{f}`, whose down-set is `{p : p < f}`. Implementations live on
/// the point type itself.
pub trait Frontier: Timestamp + Ord {
    /// The bit-width of the lattice's total measure: the chain's root tile
    /// spans `2^INITIAL_BITS` units. For fixed-width integer timestamps this
    /// is the type's bit width.
    const INITIAL_BITS: u32 = const { (size_of::<Self>() * 8) as u32 };

    /// Returns `true` iff `point` lies in the down-set generated by `self` —
    /// equivalently, the frontier has advanced past `point`.
    ///
    /// Defaults to strict-less-than, which is correct for totally-ordered
    /// frontiers represented as singleton antichains on their own point type.
    #[inline]
    fn covers(&self, point: &Self) -> bool {
        point < self
    }

    /// Step `self` forward by `2^bits` units of measure on the lattice.
    /// Returns `None` if stepping would exceed the domain.
    ///
    /// The chain uses this to size and bisect tiles: a tile rooted at frontier
    /// `lo` with bit-width `b` spans `[lo, lo.step_by(b))`, and its midpoint
    /// frontier is `lo.step_by(b - 1)`.
    fn step_by(&self, bits: u32) -> Option<Self>;
}

/// A type that can be split into two parts at a frontier.
pub trait Bucket: Sized {
    /// The frontier type associated with this storage.
    type Frontier: Frontier;
    /// Split self in two at `at`. The first element contains all data with
    /// timestamps in the down-set of `at` (`Frontier::covers` returns true),
    /// the second all other data.
    fn split(self, at: &Self::Frontier, fuel: &mut i64) -> (Self, Self);
}

/// A `[start, end)` region of the lattice, where `end = None` means the region
/// extends to the top of the domain.
pub struct BucketRange<F> {
    /// The lower bound (inclusive).
    pub start: F,
    end: Option<F>,
}

impl<F: Frontier> BucketRange<F> {
    /// Returns `true` if the range contains the given point.
    pub fn contains(&self, point: &F) -> bool {
        !self.start.covers(point) && self.end.as_ref().is_none_or(|e| e.covers(point))
    }
}

/// A sorted chain of tiles, representing data partitioned by frontier position.
///
/// Bucket chains support three main APIs: finding tiles for a given point, peeling
/// off tiles up to a frontier, and restoring the chain property. All operations aim
/// to be amortized logarithmic in the number of outstanding timestamps.
///
/// Tile bit-widths grow geometrically with distance from the chain's lower bound,
/// so points near the frontier live in small tiles and far-future points live in
/// large ones. The *chain property* requires adjacent tiles to be within two bits
/// (a factor of four in measure), with an imaginary tile of `-2` bits just before
/// the smallest tile. The chain may temporarily violate this property; `peel` and
/// `find` still work, though `peel` may need to split more tiles than usual.
///
/// [`BucketChain::restore`] re-establishes the chain property. It takes a fuel
/// budget so that the caller can interleave maintenance with other work.
#[derive(Debug)]
pub struct BucketChain<B: Bucket> {
    /// Tiles keyed by lower frontier. Each value is `(bit-width, payload)`,
    /// where bit-width is the log2 of the tile's measure.
    content: BTreeMap<B::Frontier, (u32, B)>,
}

impl<B: Bucket> BucketChain<B> {
    /// Construct a new bucket chain. Spans the whole domain.
    #[inline]
    pub fn new(storage: B) -> Self {
        Self {
            // The initial tile starts at the minimum frontier and spans the whole domain.
            content: BTreeMap::from([(
                <B::Frontier as Timestamp>::minimum(),
                (B::Frontier::INITIAL_BITS, storage),
            )]),
        }
    }

    /// Find the range of the tile that contains data for `point`. Returns
    /// `None` if no tile covers `point` (only points that haven't been peeled
    /// are still found).
    ///
    /// The bounds are only valid until the next call to `peel` or `restore`.
    #[inline]
    pub fn range_of(&self, point: &B::Frontier) -> Option<BucketRange<B::Frontier>> {
        let (start, (bits, _)) = self.content.range(..=point).next_back()?;
        Some(BucketRange {
            start: start.clone(),
            end: start.step_by(*bits),
        })
    }

    /// Find the tile that contains data for `point`. Returns a reference to
    /// the payload, or `None` if no tile covers `point`.
    ///
    /// Only points that haven't been peeled can still be found.
    #[inline]
    pub fn find(&self, point: &B::Frontier) -> Option<&B> {
        self.content
            .range(..=point)
            .next_back()
            .map(|(_, (_, storage))| storage)
    }

    /// Find the tile that contains data for `point`. Returns a mutable reference
    /// to the payload, or `None` if no tile covers `point`.
    ///
    /// Only points that haven't been peeled can still be found.
    #[inline]
    pub fn find_mut(&mut self, point: &B::Frontier) -> Option<&mut B> {
        self.content
            .range_mut(..=point)
            .next_back()
            .map(|(_, (_, storage))| storage)
    }

    /// Peel off all data up to `frontier`. The returned tiles contain all data
    /// strictly less than the frontier.
    #[inline]
    pub fn peel(&mut self, frontier: AntichainRef<B::Frontier>) -> Vec<B> {
        let mut peeled = vec![];
        // While there are tiles, and the frontier is past the lowest start, peel them off.
        while let Some(min_entry) = self.content.first_entry()
            && !frontier.less_equal(min_entry.key())
        {
            let (start, (bits, storage)) = self.content.pop_first().expect("must exist");
            let upper = start.step_by(bits);

            // Split the tile if it straddles the frontier.
            if upper.is_none() && !frontier.is_empty()
                || upper.is_some() && frontier.less_than(&upper.unwrap())
            {
                // We need to split, no matter how much fuel we have.
                self.split_and_insert(&mut 0, bits, start, storage);
            } else {
                // Tile is fully past the frontier; release it.
                peeled.push(storage);
            }
        }
        peeled
    }

    /// Restore the chain property by splitting tiles as necessary.
    ///
    /// The chain is well-formed if adjacent tiles are within two bits of each
    /// other, with an imaginary tile of `-2` bits just before the smallest tile.
    ///
    /// The caller must invoke `restore` repeatedly with a positive fuel budget
    /// until the remaining fuel after the call is non-positive. This allows
    /// the caller to control the amount of work done in a single call and
    /// interleave it with other work.
    #[inline]
    pub fn restore(&mut self, fuel: &mut i64) {
        // We could write this in terms of a cursor API, but it's not stable yet. Instead, we
        // allocate a new map and move elements over.
        let mut new = BTreeMap::default();
        let mut last_bits = -2;
        while *fuel > 0
            && let Some((start, (bits, storage))) = self.content.pop_first()
        {
            // Accept the tile if its size satisfies the chain property.
            if isize::cast_from(bits) <= last_bits + 2 {
                new.insert(start, (bits, storage));
                last_bits = isize::cast_from(bits);
            } else {
                // Otherwise, split it.
                self.split_and_insert(fuel, bits, start, storage);
            }
        }
        // Move remaining elements if we ran out of fuel.
        new.append(&mut self.content);
        self.content = new;
    }

    /// Returns `true` if the chain is empty. This means there are no outstanding times left.
    #[inline(always)]
    pub fn is_empty(&self) -> bool {
        self.content.is_empty()
    }

    /// The number of tiles in the chain.
    #[inline(always)]
    pub fn len(&self) -> usize {
        self.content.len()
    }

    /// Bisect the tile specified by `(bits, start, storage)` and insert the
    /// two halves. Updates `fuel`.
    ///
    /// Panics if the tile cannot be split, i.e., it covers 0 bits.
    #[inline(always)]
    fn split_and_insert(&mut self, fuel: &mut i64, bits: u32, start: B::Frontier, storage: B) {
        let bits = bits - 1;
        let midpoint = start.step_by(bits).expect("must exist");
        let (bot, top) = storage.split(&midpoint, fuel);
        self.content.insert(start, (bits, bot));
        self.content.insert(midpoint, (bits, top));
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    impl Frontier for u8 {
        fn step_by(&self, bits: u32) -> Option<Self> {
            self.checked_add(1_u8.checked_shl(bits)?)
        }
    }

    impl Frontier for u64 {
        fn step_by(&self, bits: u32) -> Option<Self> {
            self.checked_add(1_u64.checked_shl(bits)?)
        }
    }

    struct TestStorage<T> {
        inner: Vec<T>,
    }

    impl<T: std::fmt::Debug> std::fmt::Debug for TestStorage<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            self.inner.fmt(f)
        }
    }

    impl<T: Frontier> Bucket for TestStorage<T> {
        type Frontier = T;
        fn split(self, at: &T, fuel: &mut i64) -> (Self, Self) {
            *fuel = fuel.saturating_sub(self.inner.len().try_into().expect("must fit"));
            let (left, right) = self.inner.into_iter().partition(|d| at.covers(d));
            (Self { inner: left }, Self { inner: right })
        }
    }

    fn collect_and_sort<T: Frontier>(peeled: Vec<TestStorage<T>>) -> Vec<T> {
        let mut collected: Vec<_> = peeled
            .iter()
            .flat_map(|b| b.inner.iter().cloned())
            .collect();
        collected.sort();
        collected
    }

    #[mz_ore::test]
    fn test_bucket_chain_empty_peel_all() {
        let mut chain = BucketChain::new(TestStorage::<u8> { inner: vec![] });
        let mut fuel = 1000;
        chain.restore(&mut fuel);
        assert!(fuel > 0);
        let peeled = chain.peel(AntichainRef::new(&[]));
        assert!(collect_and_sort(peeled).is_empty());
        assert!(chain.is_empty());
    }

    #[mz_ore::test]
    fn test_bucket_chain_u8() {
        let mut chain = BucketChain::new(TestStorage::<u8> {
            inner: (0..=255).collect(),
        });
        let mut fuel = -1;
        while fuel <= 0 {
            fuel = 100;
            chain.restore(&mut fuel);
        }
        let peeled = chain.peel(AntichainRef::new(&[1]));
        assert_eq!(peeled.len(), 1);
        assert_eq!(peeled[0].inner[0], 0);
        assert!(collect_and_sort(peeled).into_iter().eq(0..1));
        let mut fuel = 1000;
        chain.restore(&mut fuel);
        assert!(fuel > 0);
        let peeled = chain.peel(AntichainRef::new(&[63]));
        let mut fuel = 1000;
        chain.restore(&mut fuel);
        assert!(fuel > 0);
        assert!(collect_and_sort(peeled).into_iter().eq(1..63));
        let peeled = chain.peel(AntichainRef::new(&[65]));
        let mut fuel = 1000;
        chain.restore(&mut fuel);
        assert!(fuel > 0);
        assert!(collect_and_sort(peeled).into_iter().eq(63..65));
        let peeled = chain.peel(AntichainRef::new(&[]));
        let mut fuel = 1000;
        chain.restore(&mut fuel);
        assert!(fuel > 0);
        assert!(collect_and_sort(peeled).into_iter().eq(65..=255));
    }

    /// Test a chain with 10M disjoint elements.
    #[mz_ore::test]
    #[cfg_attr(miri, ignore)] // slow
    fn test_bucket_10m() {
        let limit = 10_000_000;

        let mut chain = BucketChain::new(TestStorage::<u64> { inner: Vec::new() });
        let mut fuel = 1000;
        chain.restore(&mut fuel);
        assert!(fuel > 0);

        let now = 1739276664_u64;

        let peeled = chain.peel(AntichainRef::new(&[now]));
        let mut fuel = 1000;
        chain.restore(&mut fuel);
        assert!(fuel > 0);
        let peeled = collect_and_sort(peeled);
        assert!(peeled.is_empty());

        for i in now..now + limit {
            chain.find_mut(&i).expect("must exist").inner.push(i);
        }

        let mut offset = now;
        let step = 1000;
        while offset < now + limit {
            let peeled = chain.peel(AntichainRef::new(&[offset + step]));
            assert!(
                collect_and_sort(peeled)
                    .into_iter()
                    .eq(offset..offset + step)
            );
            offset += step;
            let mut fuel = 1000;
            chain.restore(&mut fuel);
        }
    }

    #[mz_ore::test]
    fn test_range_of() {
        let chain = BucketChain::new(TestStorage::<u8> { inner: vec![] });
        let range = chain.range_of(&0).unwrap();
        assert!(range.contains(&0));
        assert!(range.contains(&255));
    }
}
