[package]
name = "mz-wasm-udf"
description = "Deterministic WebAssembly runtime for arrow-udf scalar functions."
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
arrow.workspace = true
arrow-ipc.workspace = true
chrono.workspace = true
itertools.workspace = true
mz-expr = { path = "../expr" }
mz-ore = { path = "../ore" }
mz-repr = { path = "../repr" }
mz-wasm-udf-abi = { path = "../wasm-udf-abi" }
thiserror.workspace = true
tracing.workspace = true
wasmtime = { workspace = true, features = ["anyhow", "backtrace", "cranelift", "runtime", "std"] }

[dev-dependencies]
flate2.workspace = true
mz-ore = { path = "../ore", features = ["test"] }

[features]
default = []
