{
 "title": "Materialize Overview",
 "time": { "from": "now-24h/d", "to": "now/d" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(up{instance=~\".*:6875\"}, instance)"
   },
   {
    "name": "command",
    "query": "label_values(mz_command_durations_bucket, command)"
   },
   {
    "name": "timely_workers",
    "label": "Timely Workers",
    "query": "label_values(mz_server_metadata_timely_worker_threads, count)"
   },
   {
    "name": "built_at",
    "label": "Built at",
    "query": "label_values(mz_server_metadata_seconds, build_time)"
   },
   {
    "name": "build_version",
    "label": "Version",
    "query": "label_values(mz_server_metadata_seconds, build_version)"
   },
   {
    "name": "build_sha",
    "label": "Git commit",
    "query": "label_values(mz_server_metadata_seconds, build_sha)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kafka Messages Ingested",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mz_kafka_messages_ingested{instance=~\"$instance\"})"
    },
    {
     "expr": "sum(mz_messages_ingested{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": " Kafka Consumer Lag",
   "type": "stat",
   "description": "This shows the maximum Kafka consumer lag across all instantiated sources. See the other Kafka Consumer Lag panel for per-source details.\n\nFor example, if there are 1,000 messages in kafka and materialized has processed 750, this value will be 250.\n\nThis is limited by the (low) frequency at which we request metadata from kafka -- it is common for all values to be zero, and there is only a problem if the number is not decreasing.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(clamp_min(\nmz_kafka_partition_offset_max{instance=~\"$instance\"} \n  - mz_kafka_partition_offset_ingested{instance=~\"$instance\"}, 0))",
     "legendFormat": "{{topic}}/{{partition_id}} source={{source_id}}"
    },
    {
     "expr": "max(clamp_min(\nmz_kafka_partition_offset_max{instance=~\"$instance\"} \n  - mz_partition_offset_ingested{instance=~\"$instance\"}, \n  0))",
     "legendFormat": "{{topic}}/{{partition_id}} source={{source_id}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "stat",
   "description": "This shows the CPU utilization as proportion of CPUs used. A value of `1.0` means that materialized is using the equivalent of 100% of 1 CPU.\n\nSee the CPU/Memory row below for more details.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SQL Queries/second",
   "type": "stat",
   "description": "Total number of sql data queries being executed per second.\n\nSee the client queries row for a detailed breakdown.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(mz_command_durations_count{instance=~\"$instance\",command=~\"execute|query\",status=\"success\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "SQL Query Error Rate",
   "type": "stat",
   "description": "This encapsulates every kind of query error that materialize returns. \n\nIt includes errors caused by invalid SQL queries, as well as internal materialized errors. All query errors are reported to the materialized log file.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(mz_command_durations_count{instance=~\"$instance\",status=\"error\"}[5m]))",
     "legendFormat": "{{purpose}}/{{test}}/{{workflow}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "alertlist",
   "description": "Alerts configured in the Alerts row.\n\nNote that you will probably want to edit the alerts to match your deployment.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 }
  },
  {
   "title": "Kafka Message Ingest Rate",
   "type": "stat",
   "description": "How many messages per second materialized is currently ingesting",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(mz_kafka_messages_ingested{instance=~\"$instance\"}[$__interval]))"
    },
    {
     "expr": "sum(rate(mz_messages_ingested{instance=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Memory use",
   "type": "stat",
   "description": "See the CPU/Memory row below for more details.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Query Latency",
   "type": "stat",
   "description": "Median query latency, see SQL Query Timing row for a detailed breakdown.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(mz_command_durations_bucket{instance=~\"$instance\",command=~\"execute|query\",status=\"success\"}[$__interval])) by (le))",
     "legendFormat": "median"
    }
   ]
  },
  {
   "title": "Materialize Build Info",
   "type": "text",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 5 },
   "content": "Timely Workers: $timely_workers<br/>\nBuilt At: $built_at<br/>\nBuild Version: $build_version<br/>\nBuild sha: $build_sha<br/>"
  },
  {
   "title": "SQL Query Timing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency Evolving Histogram ($command)",
     "type": "heatmap",
     "description": "This shows the distribution of query latencies over time. Brighter colors mean more queries fell into that latency bucket.\n\nThis panel complements the histogram quantiles panel by showing the distribution of latencies at any given time in the past.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(increase(mz_command_durations_bucket{instance=~\"$instance\",command=~\"$command\",status=\"success\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Query Latency Quantiles ($command)",
     "type": "graph",
     "description": "This shows what percent of queries finished in what amount of time.\n\nThe value in parentheses ($command) reflects the postgres commands that are being displayed, \"Execute + Query\" catches all commands that result in data being returned to SQL clients, other commands drive postgres connection to prepare for data or close connections.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(mz_command_durations_bucket{instance=~\"$instance\",command=~\"$command\",status=\"success\"}[$__interval])) by (le))",
       "legendFormat": "max"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(mz_command_durations_bucket{instance=~\"$instance\",command=~\"$command\",status=\"success\"}[$__interval])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(mz_command_durations_bucket{instance=~\"$instance\",command=~\"$command\",status=\"success\"}[$__interval])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(mz_command_durations_bucket{instance=~\"$instance\",command=~\"$command\",status=\"success\"}[$__interval])) by (le))",
       "legendFormat": "median"
      },
      {
       "expr": "histogram_quantile(0.001, sum(rate(mz_command_durations_bucket{instance=~\"$instance\",command=~\"$command\",status=\"success\"}[$__interval])) by (le))",
       "legendFormat": "p001"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(mz_command_durations_bucket{instance=~\"$instance\",command=~\"$command\",status=\"error\"}[$__interval])) by (le))",
       "legendFormat": "error p99"
      },
      {
       "expr": "histogram_quantile(1, sum(rate(mz_command_durations_bucket{instance=~\"$instance\",command=~\"$command\",status=\"error\"}[$__interval])) by (le))",
       "legendFormat": "error max"
      }
     ]
    },
    {
     "title": "queries/second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "rate(mz_command_durations_count{instance=~\"$instance\"}[$__interval])",
       "legendFormat": "{{command}}"
      }
     ]
    },
    {
     "title": "query rows|bytes/second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "rate(mz_pg_sent_rows{instance=~\"$instance\"}[$__interval])",
       "legendFormat": "rows/sec"
      },
      {
       "expr": "rate(mz_pg_sent_bytes{instance=~\"$instance\"}[$__interval])",
       "legendFormat": "bytes/sec"
      }
     ]
    }
   ]
  },
  {
   "title": "Ingest",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka Consumer Lag",
     "type": "graph",
     "description": "This shows the number of messages that materialize knows it is behind an kafka source.\n\nFor example, if there are 1,000 messages in kafka and materialized has processed 750, this value will be 250.\n\nThis is limited by the (low) frequency at which we request metadata from kafka -- it is common for all values to be zero, and there is only a problem if the number is not decreasing.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(50, clamp_min(\nmz_kafka_partition_offset_max{instance=~\"$instance\"} \n  - mz_kafka_partition_offset_ingested{instance=~\"$instance\"}, \n  0))",
       "legendFormat": "{{topic}}/{{partition_id}} source={{source_id}}"
      },
      {
       "expr": "topk(50, clamp_min(\nmz_kafka_partition_offset_max{instance=~\"$instance\"} \n  - mz_partition_offset_ingested{instance=~\"$instance\"}, \n  0))",
       "legendFormat": "{{topic}}/{{partition_id}} source={{source_id}}"
      }
     ]
    },
    {
     "title": "Kafka Message Ingest Rate",
     "type": "graph",
     "description": "Unlike the Messages Ingested by Format, this shows the number of messages materialized has ingested per topic.\n\nCurrently only shows Kafka",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "mps" }
     ],
     "targets": [
      {
       "expr": "rate(mz_kafka_messages_ingested{instance=~\"$instance\"}[$__interval])",
       "legendFormat": "rate {{topic}} {{source_id}} {{partition_id}}"
      },
      {
       "expr": "rate(mz_messages_ingested{instance=~\"$instance\"}[$__interval])",
       "legendFormat": "rate {{topic}} {{source_id}} {{partition_id}}"
      }
     ]
    },
    {
     "title": "Messages Ingested by Message Format",
     "type": "graph",
     "description": "For Materialize instances that have multiple different categories of source (json, avro, etc) this shows the total rate of message ingestion.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "rate(mz_dataflow_events_read_total{instance=~\"$instance\"}[$__interval])",
       "legendFormat": "{{format}} events {{status}} {{instance}}"
      }
     ]
    },
    {
     "title": "Kafka bytes read",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(mz_kafka_bytes_read_total{instance=~\"$instance\"}[$__interval])",
       "legendFormat": "rate {{instance}}"
      },
      {
       "expr": "mz_kafka_bytes_read_total{instance=~\"$instance\"}",
       "legendFormat": "total"
      },
      {
       "expr": "rate(mz_bytes_read_total{instance=~\"$instance\"}[$__interval])",
       "legendFormat": "rate {{instance}}"
      },
      {
       "expr": "mz_bytes_read_total{instance=~\"$instance\"}",
       "legendFormat": "total {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kinesis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time behind external source",
     "type": "graph",
     "description": "This is only reported for Kinesis sources at the moment.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "mz_kinesis_shard_millis_behind_latest{instance=~\"$instance\"}",
       "legendFormat": "{{ stream_name }} {{ shard_id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sinks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka Messages Written",
     "type": "graph",
     "description": "The number of messages we've written through a Kafka Sink.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "expr": "rate(mz_kafka_messages_sent_total{instance=~\"$instance\"}[$__interval])",
       "legendFormat": "{{sink_id}}/{{worker_id}} {{topic}}"
      },
      {
       "expr": "mz_kafka_messages_sent_total{instance=~\"$instance\"}",
       "legendFormat": "total {{sink_id}}/{{worker_id}} {{topic}}"
      }
     ]
    },
    {
     "title": "Kafka Message Write Errors",
     "type": "graph",
     "description": "The number of errors we've received when writing messages to Kafka",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "eps" }
     ],
     "targets": [
      {
       "expr": "rate(mz_kafka_message_send_errors_total{instance=~\"$instance\"}[$__interval])",
       "legendFormat": "{{sink_id}}/{{worker_id}} {{topic}}"
      },
      {
       "expr": "mz_kafka_message_send_errors_total{instance=~\"$instance\"}",
       "legendFormat": "total {{sink_id}}/{{worker_id}} {{topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU/Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "materialized: CPU usage",
     "type": "graph",
     "description": "See also the CPU row in the [node-state dashboard](/d/node-state?var-job=load_test). \n\nYou will need to filter to the current instance: $instances",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{instance=~\"$instance\"}[$__interval])",
       "legendFormat": "materialized"
      },
      {
       "expr": "rate(process_cpu_seconds_total{instance=~\".*16875\"}[$__interval])",
       "legendFormat": "peeker"
      }
     ]
    },
    {
     "title": "materialized: per-thread-name CPU usage",
     "type": "graph",
     "description": "Per-thread-name CPU usage, multiple trheads (e.g. in a pool) often share the same name. \n\nSee the thread-name-count panel for how many threads exist with a given name.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(process_thread_cpu_seconds_total{instance=~\"$instance\"}[$__interval])",
       "legendFormat": "{{thread_name}}"
      },
      {
       "expr": "rate(process_thread_cpu_seconds_total{instance=~\".*16875\"}[$__interval])",
       "legendFormat": "peeker"
      }
     ]
    },
    {
     "title": "materialized: memory",
     "type": "graph",
     "description": "See also the Memory/Meminfo row in the [node-state dashboard](/d/node-state?var-job=load_test). \n\nYou will need to filter to the current instance: $instances",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
       "legendFormat": "rss {{job}}"
      },
      {
       "expr": "process_swap_memory_bytes{instance=~\"$instance\"}",
       "legendFormat": "swap {{job}}"
      }
     ]
    },
    {
     "title": "materialized: thread-name counts",
     "type": "graph",
     "description": "How many threads exist with a given name in materialized.\n\nHelps think about per-thread CPU usage, in case it's over 100%",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_thread_count{instance=~\"$instance\"}",
       "legendFormat": "{{thread_name}}"
      },
      {
       "expr": "process_thread_count{instance=~\".*:16875\"}",
       "legendFormat": "peeker"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Materialize is running",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "up{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}\t{{git_ref}}"
      }
     ]
    },
    {
     "title": "Worker Queue Growth",
     "type": "graph",
     "description": "Shows how the worker queues are behaving. In general they should be stable, if they are growing continuously that means materialized is not keeping up.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(deriv(mz_worker_command_queue_size[5m]))",
       "legendFormat": "pending commands"
      },
      {
       "expr": "sum(deriv(mz_worker_pending_peeks_queue_size[5m]))",
       "legendFormat": "pending peeks"
      }
     ]
    }
   ]
  },
  {
   "title": "Internal Latency and Throughput Measures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Worker commands processing rate",
     "type": "graph",
     "description": "A worker is the underlying thread of computation in materialized. In general materialized should send similar amounts of work to each worker, and therefore the commands processed per worker should be similar.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(mz_worker_commands_processed_total{instance=~\"$instance\"}[$__interval])",
       "legendFormat": "{{command}}/{{worker}}"
      }
     ]
    },
    {
     "title": "Worker queue sizes",
     "type": "graph",
     "description": "A worker is the underlying thread of computation in materialized. In general materialized should send similar amounts of work to each worker, and the queue depths should be similar to each other.\n\nIf a queue is growing without bound, or queues are very unbalanced, that could signify a problem.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mz_worker_command_queue_size{instance=~\"$instance\"}",
       "legendFormat": "pending commands worker={{worker}}"
      },
      {
       "expr": "mz_worker_pending_peeks_queue_size{instance=~\"$instance\"}",
       "legendFormat": "pending peeks worker={{worker}}"
      }
     ]
    },
    {
     "title": "Time spent in maintenance",
     "type": "graph",
     "description": "Proportion of time spent in maintenance, per arrangement,  for the top 50 arrangements.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "topk(50, rate(mz_arrangement_maintenance_seconds_total{instance=~\"$instance\"}[$__interval]))",
       "legendFormat": "{{worker_id}}/{{arrangement_id}}"
      }
     ]
    },
    {
     "title": "Frontier lags",
     "type": "graph",
     "description": "This shows the top 10 dataflow operators that are introducing lag into the system.\n\nAn operator can introduce lag either because its source is running behind, or because it is doing lots of work.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "ms", "label": "Lag (from -> to)" }
     ],
     "targets": [
      {
       "expr": "topk(10, mz_perf_dependency_frontiers{instance=~\"$instance\"})",
       "legendFormat": "{{source}} -> {{dataflow}}"
      }
     ]
    },
    {
     "title": "Kafka Offsets Received",
     "type": "graph",
     "description": "The raw kafka offset as seen at ingest time by materialized.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mz_kafka_partition_offset_received{instance=~\"$instance\"}",
       "legendFormat": "{{topic}}/{{partition_id}} {{source_id}}"
      },
      {
       "expr": "mz_partition_offset_received{instance=~\"$instance\"}",
       "legendFormat": "{{topic}}/{{partition_id}} {{source_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Internal Debugging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Arrangement Batches",
     "type": "graph",
     "description": "A batch is a slab of memory, arrangements with a large number of batches have allocated a large number of records, which should be represented in the Arrangement Records panel.\n\nThis shows the top 10 arrangements by number of batches, and should be similar to the Arrangement Records panel.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, mz_perf_arrangements_batches{instance=~\"$instance\"})",
       "legendFormat": "w={{worker}} op={{operator}}"
      }
     ]
    },
    {
     "title": "Number of arrangements in mainenance",
     "type": "graph",
     "description": "This is expected to be primarily at zero, with very brief spikes.\n\nIf any time series is above zero for multiple points that suggests that we are stuck.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (worker_id) (mz_arrangement_maintenance_active_info{instance=~\"$instance\"})",
       "legendFormat": "worker {{worker_id}}"
      }
     ]
    },
    {
     "title": "Kafka Partition Imbalance Amount",
     "type": "graph",
     "description": "The difference between the most-consumed and least-consumed kafka partition, in terms of when we last released messages into the dataflow layer.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (topic, source_id) (mz_kafka_partition_closed_ts{instance=~\"$instance\"}) - min by (topic, source_id) (mz_kafka_partition_closed_ts{instance=~\"$instance\"})",
       "legendFormat": "{{topic}}-{{source_id}}"
      },
      {
       "expr": "max by (topic, source_id) (mz_partition_closed_ts{instance=~\"$instance\"}) - min by (topic, source_id) (mz_partition_closed_ts{instance=~\"$instance\"})",
       "legendFormat": "{{topic}}-{{source_id}}"
      }
     ]
    },
    {
     "title": "Source Scheduled Count",
     "type": "graph",
     "description": "The total number of times that a source has been scheduled, and the rate at which they're scheduled.\n\nIn a well-behaved system, sources should be activated approximately in proportion to how much data they have to read. If sources are being scheduled at significantly different proportions it could mean that the more-scheduled sources are having a hard time keeping up.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(mz_operator_scheduled_total{instance=~\"$instance\"}[$__interval])",
       "legendFormat": "kafka {{topic}} {{source_id}}"
      },
      {
       "expr": "mz_operator_scheduled_total{instance=~\"$instance\"}",
       "legendFormat": "kafka total {{topic}} {{source_id}}"
      }
     ]
    },
    {
     "title": "Dataflow Read Events",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short", "label": "Success" }
     ],
     "targets": [
      {
       "expr": "sum by (format, status) (rate(mz_dataflow_events_read_total{instance=~\"$instance\",status=\"error\"}[$__interval]))"
      },
      {
       "expr": "sum by (format, status) (rate(mz_dataflow_events_read_total{instance=~\"$instance\",status=\"success\"}[$__interval]))"
      }
     ]
    },
    {
     "title": " Capability Closing Rate",
     "type": "graph",
     "description": "This is a measure of when we last stated that ingested data was valid for computation. Another way of thinking about this is how many seconds of data do we ingest per second of real time. In a steady state this should be approximately 1s/s.\n\nAll sources that have a rate of 0 are *stalled* and are either not ingesting new data or have no new data to ingest.\n\nInternally, this is the capability, and the underlying measure is what capability we have released.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(mz_kafka_capability{instance=~\"$instance\"}[$__interval])",
       "legendFormat": "{{topic}}-{{source_id}}"
      },
      {
       "expr": "rate(mz_capability{instance=~\"$instance\"}[$__interval])",
       "legendFormat": "{{topic}}-{{source_id}}"
      }
     ]
    },
    {
     "title": "Arrangement Records",
     "type": "graph",
     "description": "An arrangement is where materialize stores state, records are equivalent to rows in a database or messages in a stream.\n\nThis shows the top 10 arrangements by number of records, and should be similar to the Arrangement Batches panel.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, mz_perf_arrangement_records{instance=~\"$instance\"})",
       "legendFormat": "w={{worker}} op={{operator}} name={{name}}"
      }
     ]
    },
    {
     "title": "Record increase/second",
     "type": "stat",
     "description": "A record is equivalent to a row in a traditional database",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 41 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(\nmz_perf_arrangement_records{instance=~\"$instance\"}[$__interval]))"
      }
     ]
    },
    {
     "title": "Total Number of Records",
     "type": "stat",
     "description": "A record is equivalent to a row in a traditional database",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 41 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(mz_perf_arrangement_records{instance=~\"$instance\"})"
      }
     ]
    }
   ]
  }
 ]
}