# Copyright Materialize, Inc. and contributors. All rights reserved.
#
# Use of this software is governed by the Business Source License
# included in the LICENSE file at the root of this repository.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0.

# Mirrored to DockerHub

# 2017 mssql images core on OSx, 2019 is the earliest that has passed
FROM mcr.microsoft.com/mssql/server:2019-CU32-ubuntu-20.04
