[package]
name = "mz-http-util"
description = "Utilities for running HTTP servers in Materialize."
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
askama.workspace = true
axum.workspace = true
axum-extra.workspace = true
headers.workspace = true
include_dir.workspace = true
mz-ore = { path = "../ore", default-features = false, features = ["metrics", "tracing"] }
mime.workspace = true
prometheus.workspace = true
serde.workspace = true
serde_json.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
http.workspace = true
mz-ore = { path = "../ore", default-features = false, features = ["test"] }
tokio.workspace = true
tower.workspace = true

[features]
default = []

[package.metadata.unused-deps]
# Only used in macro generated code
ignore = ["include_dir"]
