#!/usr/bin/env bash

# Copyright Materialize, Inc. and contributors. All rights reserved.
#
# Use of this software is governed by the Business Source License
# included in the LICENSE file at the root of this repository.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0.

set -euo pipefail

cd "$(dirname "$0")/../.."

. misc/shlib/shlib.bash
. test/cloudtest/config.bash

if ! kind get clusters | grep -q "$K8S_CLUSTER_NAME"; then
    run kind create cluster --name="$K8S_CLUSTER_NAME" --config=misc/kind/cluster.yaml --wait=60s
fi

for f in misc/kind/configmaps/*; do
    run kubectl --context="$K8S_CONTEXT" apply -f "$f"
done

run kubectl --context="$K8S_CONTEXT" rollout restart -n kube-system deployment/coredns
