#!/usr/bin/env python3

import argparse
import os

import psycopg2

def view_names(conn):
    """Return a generator containing all view names in Materialize."""
    with conn.cursor() as cursor:
        cursor.execute("SHOW VIEWS")
        for row in cursor:
            yield(row[0])

def snapshot_materialize_views(args):
    """Record the current table status of all views installed in Materialize."""

    with psycopg2.connect(f"postgresql://{args.host}:{args.port}/materialize") as conn:
        for view in view_names(conn):
            with conn.cursor() as cursor:
                with open(os.path.join(args.snapshot_dir, f"{view}.sql"), 'w') as f:
                    cursor.copy_expert(f"COPY (SELECT * FROM {view}) TO STDOUT", f)

if __name__ == '__main__':

    parser = argparse.ArgumentParser()
    parser.add_argument("--host", help="Materialize hostname", default="materialized", type=str)
    parser.add_argument("-p", "--port", help="Materialize port number", default=6875, type=int)

    parser.add_argument("-d", "--snapshot-dir", help="Directory containing view snapshots",
                        type=str, default="/snapshot")

    args = parser.parse_args()
    snapshot_materialize_views(args)
