// Copyright Materialize, Inc. and contributors. All rights reserved.
//
// Use of this software is governed by the Business Source License
// included in the LICENSE file.
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0.

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/census/blob": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve all active environments (persist shards) in the current cloud region */
        get: operations["get_census_s3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/census/consensus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve all active environments (CrDB resources) in the current cloud region */
        get: operations["get_census_crdb"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/region": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve all regions (EnvironmentAssignment resources) in the current cloud region */
        get: operations["get_regions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/region/:organization_id": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve the region (EnvironmentAssignment resource) for the provided organization_id
         * @description in the current cloud region
         */
        get: operations["get_region_by_org"];
        put?: never;
        post?: never;
        /**
         * Disable the region (EnvironmentAssignment resource) for the provided
         * @description organization_id in the current cloud region
         *     This sets the `disable_scheduled_at` field to a date 30 days from now
         */
        delete: operations["disable_region_for_org"];
        options?: never;
        head?: never;
        /**
         * Update (or create) the region (EnvironmentAssignment resource) for the provided
         * @description organization_id in the current cloud region
         */
        patch: operations["enable_region_for_org"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description All API responses that return a list use this standard pagination envelope */
        CensusEntries: {
            /** @description The data in this page. */
            data: components["schemas"]["CensusEntry"][];
            /** @description The cursor to provide to the next API call to retrieve the next
             *     page of results.
             *
             *     Set to `None` if there are no further pages. */
            nextCursor?: string | null;
        };
        CensusEntry: {
            /** Format: uuid */
            organizationId: string;
            /** Format: int32 */
            ordinal: number;
        };
        /** @enum {string} */
        OrgType: "customer" | "e2e_test";
        RegionInternal: {
            /** Format: uuid */
            organizationId: string;
            /** Format: date-time */
            enabledAt?: string | null;
            provisioned: boolean;
            /** Format: date-time */
            disableScheduledAt?: string | null;
            /** Format: date-time */
            deprovisionedAt?: string | null;
            environmentBase32Id: string;
            /** Format: int32 */
            ordinal: number;
            upToDate: boolean;
            orgType: components["schemas"]["OrgType"];
        };
        /** @description All API responses that return a list use this standard pagination envelope */
        RegionInternals: {
            /** @description The data in this page. */
            data: components["schemas"]["RegionInternal"][];
            /** @description The cursor to provide to the next API call to retrieve the next
             *     page of results.
             *
             *     Set to `None` if there are no further pages. */
            nextCursor?: string | null;
        };
        RegionRequest: {
            environmentdImageRef?: string | null;
            environmentdExtraArgs?: string[] | null;
            forceRollout?: boolean | null;
            cancelRollout?: boolean | null;
            inPlaceRollout?: boolean | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_census_s3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                limit: number | null;
                cursor: string | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Census of environments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CensusEntries"];
                };
            };
        };
    };
    get_census_crdb: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                limit: number | null;
                cursor: string | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Census of environments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CensusEntries"];
                };
            };
        };
    };
    get_regions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                limit: number | null;
                cursor: string | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Regions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionInternals"];
                };
            };
        };
    };
    get_region_by_org: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Region updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionInternal"];
                };
            };
            /** @description Region not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    disable_region_for_org: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seconds: number | null;
                /** @description Whether to do a real soft-deletion
                 *     use ?realSoftDelete=true to set this */
                realSoftDelete: boolean | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Region scheduled for disabling */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionInternal"];
                };
            };
            /** @description Region not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Region disabled but timed out while waiting for resource to update */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    enable_region_for_org: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegionRequest"];
            };
        };
        responses: {
            /** @description Region updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionInternal"];
                };
            };
            /** @description Region created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionInternal"];
                };
            };
            /** @description Not allowed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Region enabled but timed out while waiting for resource to update */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
