#!/usr/bin/env sh
# Copyright Materialize, Inc. All rights reserved.
#
# Use of this software is governed by the Business Source License
# included in the LICENSE file at the root of this repository.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0.

url="https://stream.wikimedia.org/v2/stream/recentchange"
echo "Streaming recent changes from Wikipedia using URL ${url}"

while true; do
  curl -s --max-time 9999999 -N "${url}" >> /tmp/wikidata/recentchanges
done
