# Copyright Materialize, Inc. All rights reserved.
#
# Use of this software is governed by the Business Source License
# included in the LICENSE file at the root of this repository.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0.

# Before building this image, run `create-certs.sh` in this directory to create
# the `secrets` dir.

FROM alpine:3.9
COPY /secrets /secrets
