[package]
name = "mz-metrics"
description = "Internal metrics libraries for Materialize."
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
lgalloc.workspace = true
libc.workspace = true
mz-dyncfg = { path = "../dyncfg" }
mz-ore = { path = "../ore", features = ["metrics"] }
nix.workspace = true
paste.workspace = true
prometheus.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
mz-ore = { path = "../ore", features = ["metrics", "test"] }

[features]
default = []
