{
 "title": "Materialized Diagnostic Queries",
 "description": "https://github.com/MaterializeInc/materialize/blob/main/doc/developer/diagnostic-queries.md",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "# Diagnosing apparent performance defects\n\nThe queries on this page are all derived from \nour [diagnosis page](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/diagnostic-queries.md)."
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "content": "## Things aren't going as fast as I would like!\n\nMaterialize spends time in various dataflow operators maintaining materialized views. The amount of time may be more than one expects, either because Materialize is behaving badly or because expectations aren't aligned with reality. These queries reveal which operators take the largest total amount of time."
  },
  {
   "title": "Scheduling Durations",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "select mdo.id, mdo.name, msh.duration_ns, sum(msh.count) as \"times scheduled\"\nfrom mz_scheduling_histogram as msh,\n     mz_dataflow_operators as mdo\nwhere\n    msh.id = mdo.id and\n    msh.worker = mdo.worker\ngroup by mdo.id, mdo.name, msh.duration_ns\norder by msh.duration_ns desc\nlimit 100;\n"
    }
   ]
  },
  {
   "title": "Total time spent in each dataflow operator",
   "type": "table",
   "description": "raw elapsed time information, by worker",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "select mdo.worker, mdo.id, mdo.name, mse.elapsed_ns\nfrom mz_scheduling_elapsed as mse,\n     mz_dataflow_operators as mdo\nwhere\n    mse.id = mdo.id and\n    mse.worker = mdo.worker\norder by elapsed_ns desc\nlimit 100;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 15 },
   "content": "## Materialize becomes unresponsive for seconds at a time!\n\nWhat causes Materialize to take control away for seconds at a time? Materialize operators get scheduled and try to behave themselves by returning control promptly, but for various reasons that doesn't always happen. These queries reveal how many times each operator was scheduled for each power-of-two elapsed time: high durations indicate an event that took roughly that amount of time before it yielded, and incriminate the subject."
  },
  {
   "title": "Raw scheduling histogram information, by worker",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "-- Extract raw scheduling histogram information, by worker.\nselect mdo.id, mdo.name, mdo.worker, msh.duration_ns, count as \"times scheduled\"\nfrom mz_scheduling_histogram as msh,\n     mz_dataflow_operators as mdo\nwhere\n    msh.id = mdo.id and\n    msh.worker = mdo.worker\norder by msh.duration_ns desc\nlimit 100;"
    }
   ]
  },
  {
   "title": "Extract raw scheduling histogram information, summed across workers",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "select mdo.id, mdo.name, msh.duration_ns, sum(msh.count) as \"times scheduled\"\nfrom mz_scheduling_histogram as msh,\n     mz_dataflow_operators as mdo\nwhere\n    msh.id = mdo.id and\n    msh.worker = mdo.worker\ngroup by mdo.id, mdo.name, msh.duration_ns\norder by msh.duration_ns desc\nlimit 100;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 26 },
   "content": "## Materialize is using lots of memory! What gives?\n\nThe majority of Materialize's memory live in \"arrangements\", which are differential dataflow structures that maintain indexes for data as they change. These queries extract the numbers of records and batches backing each of the arrangements. The reported records may exceed the number of logical records, as they reflect un-compacted state. The number of batches should be logarithmic-ish in this number, and anything significantly larger is probably a bug."
  },
  {
   "title": "Records and batches",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "-- Extract arrangement records and batches, by worker.\nselect mdo.worker, mdo.id, mdo.name, mas.records, mas.batches\nfrom mz_arrangement_sizes as mas,\n     mz_dataflow_operators as mdo\nwhere\n    mas.operator = mdo.id and\n    mas.worker = mdo.worker\norder by mas.records desc\nlimit 100;"
    }
   ]
  },
  {
   "title": "Records and batches, summed across workers",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "rawSql": "-- Extract arrangement records and batches, summed across workers.\nselect mdo.id, mdo.name, sum(mas.records) as records, sum(mas.batches) as batches\nfrom mz_arrangement_sizes as mas,\n     mz_dataflow_operators as mdo\nwhere\n    mas.operator = mdo.id and\n    mas.worker = mdo.worker\ngroup by mdo.id, mdo.name\norder by sum(mas.records) desc\nlimit 100;\n"
    }
   ]
  }
 ]
}