{
 "title": "Materialize Basic",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "command",
    "query": "label_values(mz_command_durations_bucket, command)"
   },
   {
    "name": "timely_workers",
    "label": "Timely Workers",
    "query": "label_values(mz_server_metadata_timely_worker_threads, count)"
   },
   {
    "name": "built_at",
    "label": "Built at",
    "query": "label_values(mz_server_metadata_seconds, build_time)"
   },
   {
    "name": "build_version",
    "label": "Version",
    "query": "label_values(mz_server_metadata_seconds, build_version)"
   },
   {
    "name": "build_sha",
    "label": "Git commit",
    "query": "label_values(mz_server_metadata_seconds, build_sha)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kafka Messages Ingested",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mz_kafka_messages_ingested)"
    },
    { "expr": "sum(mz_messages_ingested)" }
   ]
  },
  {
   "title": "Kafka Message Ingest Rate",
   "type": "stat",
   "description": "How many messages per second materialized is currently ingesting",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(mz_kafka_messages_ingested[$__interval]))"
    },
    {
     "expr": "sum(rate(mz_messages_ingested[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Number of Records",
   "type": "stat",
   "description": "A record is equivalent to a row in a traditional database",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(mz_perf_arrangement_records)"
    }
   ]
  },
  {
   "title": "Client queries per second",
   "type": "stat",
   "description": "Total number of sql data queries being executed per second.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(mz_command_durations_count{command=~\"execute|query\",status=\"success\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Query Error Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(mz_command_durations_count{status=\"error\"}[5m]))",
     "legendFormat": "{{purpose}}/{{test}}/{{workflow}}/{{id}}"
    }
   ]
  },
  {
   "title": "Materialize Build Info",
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "content": "Timely Workers: $timely_workers<br/>\nBuilt At: $built_at<br/>\nBuild Version: $build_version<br/>\nBuild sha: <code>$build_sha</code><br/>"
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "command=$command server latency heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(mz_command_durations_bucket{command=~\"$command\",status=\"success\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Messages behind Kafka",
   "type": "graph",
   "description": "This shows the number of messages that materialize knows it is behind an kafka source.\n\nFor example, if there are 1,000 messages in kafka and materialized has processed 750, this value will be 250.\n\nThis is limited by the (low) frequency at which we request metadata from kafka -- it is common for all values to be zero, and there is only a problem if the number is not decreasing.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(50, clamp_min(\nmz_kafka_partition_offset_max \n  - mz_kafka_partition_offset_ingested, \n  0))",
     "legendFormat": "{{topic}}/{{partition_id}} source={{source_id}}"
    },
    {
     "expr": "topk(50, clamp_min(\nmz_kafka_partition_offset_max \n  - mz_partition_offset_ingested, \n  0))",
     "legendFormat": "{{topic}}/{{partition_id}} source={{source_id}}"
    }
   ]
  },
  {
   "title": "materialized: CPU usage",
   "type": "graph",
   "description": "See also the CPU row in the [node-state dashboard](/d/node-state?var-job=load_test). \n\nYou will need to filter to the current instance: $instances",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=~\".*:6875\"}[$__interval])",
     "legendFormat": "materialized"
    },
    {
     "expr": "rate(process_cpu_seconds_total{instance=~\".*16875\"}[$__interval])",
     "legendFormat": "peeker"
    }
   ]
  },
  {
   "title": "materialized: memory",
   "type": "graph",
   "description": "See also the Memory/Meminfo row in the [node-state dashboard](/d/node-state?var-job=load_test). \n\nYou will need to filter to the current instance: $instances",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\".*:6875\"}",
     "legendFormat": "rss {{job}}"
    },
    {
     "expr": "process_swap_memory_bytes{instance=~\".*:6875\"}",
     "legendFormat": "swap {{job}}"
    }
   ]
  }
 ]
}