{
 "title": "Monitoring Monitoring",
 "description": "Metrics around the monitoring that we're performing",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Prometheus Scrape Durations",
   "type": "graph",
   "description": "How long it took prometheus to collect metrics",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "scrape_duration_seconds", "legendFormat": "{{job}} ({{instance}})" }
   ]
  },
  {
   "title": "Materialized internal metrics times",
   "type": "graph",
   "description": "How long preparing metrics for prometheus took. \n\nThis is limited to the work that happens only when prometheus is performing scrapes, not when metrics are being collected.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    { "expr": "mz_server_scrape_metrics_times", "legendFormat": "{{action}}" }
   ]
  },
  {
   "title": "Samples scraped",
   "type": "graph",
   "description": "Number of unique metrics that were collected on each prometheus scrape",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "scrape_samples_scraped", "legendFormat": "{{job}} {{instance}}" }
   ]
  }
 ]
}