#!/usr/bin/env bash
# Copyright 2019 Materialize, Inc. All rights reserved.
#
# This file is part of Materialize. Materialize may not be used or
# distributed without the express permission of Materialize, Inc.
#
# pre-push — sample Git hook to validate commits before pushing.
#
# To install this hook, copy or symlink it into .git/hooks/pre-push:
#
#     $ ln -s ../../misc/githooks/pre-push .git/hooks/pre-push
#

set -euo pipefail

oldsha=$(git rev-parse -q --verify refs/stash)
git stash save -q -u
newsha=$(git rev-parse -q --verify refs/stash)
unstash() {
  if [[ "$oldsha" != "$newsha" ]]; then
    git stash pop -q --index || true
  fi
}
trap unstash EXIT

bin/ci-test
