#!/usr/bin/env bash

# Copyright 2019 Materialize, Inc. All rights reserved.
#
# This file is part of Materialize. Materialize may not be used or
# distributed without the express permission of Materialize, Inc.
#
# pre-push — sample Git hook to validate commits before pushing.
#
# To install this hook, copy or symlink it into .git/hooks/pre-push:
#
#     $ ln -s ../../misc/githooks/pre-push .git/hooks/pre-push
#

set -euo pipefail

. misc/shlib/shlib.bash

# We declare some unused variables here to make it clear what fields
# are provided to us as input.
# shellcheck disable=SC2034
while read -r local_ref local_sha remote_ref remote_sha; do
    if [[ "$remote_ref" = refs/heads/master ]]; then
        oldlist=$(git stash list)
        git stash save --quiet --include-untracked
        newlist=$(git stash list)
        oldref=$(git symbolic-ref --quiet HEAD)
        if [[ -z "$oldref" ]]; then
            oldref=$(git rev-parse HEAD)
        fi
        git checkout --quiet "$local_sha"
        reset() {
            if [[ "$oldlist" != "$newlist" ]]; then
                git stash pop --quiet --index || true
            fi
            if [[ "$oldref" != "$local_sha" ]]; then
                git checkout --quiet -
            fi
        }
        trap reset EXIT
        bin/pre-push
    fi
done
