# Copyright Materialize, Inc. and contributors. All rights reserved.
#
# Use of this software is governed by the Business Source License
# included in the LICENSE file at the root of this repository.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0.

# Google's official storage-testbench provides both REST and gRPC APIs
# https://github.com/googleapis/storage-testbench
FROM gcr.io/cloud-devrel-public-resources/storage-testbench:v0.59.0

# HTTP/REST port
EXPOSE 9000
# gRPC port
EXPOSE 9001
