# Copyright Materialize, Inc. and contributors. All rights reserved.
#
# Use of this software is governed by the Business Source License
# included in the LICENSE file at the root of this repository.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0.

# fake-gcs-server provides a GCS-compatible API for testing
# https://github.com/fsouza/fake-gcs-server
FROM fsouza/fake-gcs-server:1.52.3

# The default port is 4443
EXPOSE 4443
